### ISSUE TITLE
un-aligned warp reduction

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#1063]
current codegen allows un-aligned warp reduction, which is not safe since the assuption of the implementation is all the threads in the same warp are participating. To illustrate this, a [repo](https://github.com/NVIDIA/Fuser/tree/llu/warp_diverge) with a [test](https://github.com/NVIDIA/Fuser/compare/main...llu/warp_diverge#:~:text=TEST_F(NVFuserTest%2C%20UnAlignedWarpReduce)) case named `TEST_F(NVFuserTest, UnAlignedWarpReduce) `has been added. This test conducts a warp reduction on 17 elements using 17 threads, while the remaining 15 threads in the same warp execute the `warp::warpReduceTIDX` from the else branch.

Although it is unsafe (the behavior of threads not participating is un-defined), the test can still pass, at least in my local node.

Generated code:

```
__global__ void kernel1(Tensor<float, 2, 2> T0, Tensor<float, 1, 1> T3) {
  alignas(16) extern __shared__ char array[];
  void* shared_mem = array;
  nvfuser_index_t i0;
  i0 = T0.alloc_stride[1LL] * ((nvfuser_index_t)threadIdx.x);
  bool b1;
  b1 = ((nvfuser_index_t)threadIdx.x) < T0.logical_size[1LL];
  bool b2;
  b2 = ((nvfuser_index_t)threadIdx.x) == 0LL;
  if (b1) {
    #pragma unroll 1
    for(nvfuser_index_t i3 = 0LL; i3 < T0.logical_size[0LL]; ++i3) {
      float T2[1LL];
      T2[0LL] = 0.000000000e+00f;
      float T1[1LL];
      T1[0LL] = 0.000000000e+00f;
      T1[0LL]
        = T0[(i0 + (T0.alloc_stride[0LL] * i3))]
        + (float) 1.00000000000000000e+00;
      warp::warpReduceTIDX<true, false>(T2[0LL], T1[0LL], [](float &a, float b) { a = a + b; }, static_cast<float*>(shared_mem), true, static_cast<float>(0.000000000e+00f));
      if (b2) {
        T3[i3]
          = T2[0LL]
          + (float) 1.00000000000000000e+00;
      }
    }
  } else {
    #pragma unroll 1
    for(nvfuser_index_t i3 = 0LL; i3 < T0.logical_size[0LL]; ++i3) {
      float T2[1LL];
      T2[0LL] = 0.000000000e+00f;
      float T1[1LL];
      T1[0LL] = 0.000000000e+00f;
      if (b1) {
        T1[0LL]
          = T0[(i0 + (T0.alloc_stride[0LL] * i3))]
          + (float) 1.00000000000000000e+00;
      }
      warp::warpReduceTIDX<true, false>(T2[0LL], T1[0LL], [](float &a, float b) { a = a + b; }, static_cast<float*>(shared_mem), true, static_cast<float>(0.000000000e+00f));
      if (b2) {
        T3[i3]
          = T2[0LL]
          + (float) 1.00000000000000000e+00;
      }
    }
  }
```

Added printf to mark two different diverged calls of `warp::warpReduceTIDX`. Threads 17 to 31 are calling from the `else` branch with inp_val = 0 and threads 0 to 16 are calling from the `if` branch with inp_val = 2.0
```
calling warpReduceTIDX from thread 17 with inp_val 0.000000
calling warpReduceTIDX from thread 18 with inp_val 0.000000
calling warpReduceTIDX from thread 19 with inp_val 0.000000
calling warpReduceTIDX from thread 20 with inp_val 0.000000
calling warpReduceTIDX from thread 21 with inp_val 0.000000
calling warpReduceTIDX from thread 22 with inp_val 0.000000
calling warpReduceTIDX from thread 23 with inp_val 0.000000
calling warpReduceTIDX from thread 24 with inp_val 0.000000
calling warpReduceTIDX from thread 25 with inp_val 0.000000
calling warpReduceTIDX from thread 26 with inp_val 0.000000
calling warpReduceTIDX from thread 27 with inp_val 0.000000
calling warpReduceTIDX from thread 28 with inp_val 0.000000
calling warpReduceTIDX from thread 29 with inp_val 0.000000
calling warpReduceTIDX from thread 30 with inp_val 0.000000
calling warpReduceTIDX from thread 31 with inp_val 0.000000

calling warpReduceTIDX from thread 0 with inp_val 2.000000
calling warpReduceTIDX from thread 1 with inp_val 2.000000
calling warpReduceTIDX from thread 2 with inp_val 2.000000
calling warpReduceTIDX from thread 3 with inp_val 2.000000
calling warpReduceTIDX from thread 4 with inp_val 2.000000
calling warpReduceTIDX from thread 5 with inp_val 2.000000
calling warpReduceTIDX from thread 6 with inp_val 2.000000
calling warpReduceTIDX from thread 7 with inp_val 2.000000
calling warpReduceTIDX from thread 8 with inp_val 2.000000
calling warpReduceTIDX from thread 9 with inp_val 2.000000
calling warpReduceTIDX from thread 10 with inp_val 2.000000
calling warpReduceTIDX from thread 11 with inp_val 2.000000
calling warpReduceTIDX from thread 12 with inp_val 2.000000
calling warpReduceTIDX from thread 13 with inp_val 2.000000
calling warpReduceTIDX from thread 14 with inp_val 2.000000
calling warpReduceTIDX from thread 15 with inp_val 2.000000
calling warpReduceTIDX from thread 16 with inp_val 2.000000
```

**Comment by naoyam** [comment]
If I read the code correctly, all threads call the warp reduction function exactly the same number of times. If so, that should be guaranteed to work.

https://developer.nvidia.com/blog/using-cuda-warp-level-primitives/
> On Volta and later GPU architectures, the data exchange primitives can be used in thread-divergent branches: branches where some threads in the warp take a different path than the others. Listing 4 shows an example where all the threads in a warp get the value of val from the thread at lane 0. The even- and odd-numbered threads take different branches of an if statement.

**Comment by liqiangxl** [comment]
You are right. So we don't have this problem. `warpReduceTIDX` is alwadys called from both if and else branches. 
But if we want to fully remove this potential issue just in case something like `if(thread condition) return; then other threads do warpReduceTIDX` is generated in the future. we can either:
(1) use `__ballot_sync(0xffffffff, true)` to set the participating threads
or
(2) aviod using `warpReduceTIDX` if no aligned.

**Comment by naoyam** [comment]
Thanks for checking. Yes, this should be supported. Closing.
