### ISSUE TITLE
Specify supported Python versions

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#1078]
I believe our integration currently is planned to support Python 3.10 <= version < 3.11, though that's probably not set in stone. Pytorch supports 3.8 and up.

**Comment by jacobhinkle** [comment]
cc @kevinstephano @jjsjann123

**Comment by jjsjann123** [comment]
There were some earlier conversation on something like 3.9+?!

I don't think we have nailed down the exact versions yet. Need to bring this conversation up to folks and double check on their requirement.

**Comment by jacobhinkle** [comment]
I believe we still only specify supported compiler versions, not supported Python versions.
