### ISSUE TITLE
cuda_graph_fuser.h header has been removed in pytorch, but is still included in our code

### ISSUE THREAD

**Issue by xwang233** [NVIDIA/Fuser#1105]
https://github.com/NVIDIA/Fuser/blob/9241dd79640dcb6c54d0f0e54b3ed07eb147102d/csrc/graph_fuser.cpp#L9

removed by https://github.com/pytorch/pytorch/pull/111093

cc @jjsjann123

**Comment by zasdfgbnm** [comment]
Is this fixed?

**Comment by jjsjann123** [comment]
I think so?! https://github.com/NVIDIA/Fuser/commit/9cf4b3d63ed8b0f164e0334d6f0fbf123d38adcd

**Comment by jjsjann123** [comment]
I"m closing it. feel free to re-open if it pops up again.
