### ISSUE TITLE
segmentation due to insufficient register size in `innerOuterPersistentHeuristic`

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#1136]
### **Background:**
The `innerOuterPersistentHeuristic` needs additional persistent tensors to store the intermediate outer reduction results apart from the original cached input tensors. The summary below outlines the number of persistent tensors requested and the maximum element count that can be processed assuming all 64K registers are used to store persistent buffers:

Model | Intermediate Tensor | CachedInput Tensor | Buffer Size Per Element | max elements if given 64K registers
-- | -- | -- | -- | --
LayerNormBwd | 2 fp32 | 3 fp16/32 | 14 (fp16), 20 (fp32) | 18.3K (fp16), 12.8K (fp32)
RMSNormBwd | 1 fp32 | 3 fp6/33 | 10 (fp16), 16 (fp32) | 25.6K (fp16), 16K (fp32)

In the current scheduler, the number of available registers has been adjusted to prevent segmentation for cases with large hidden sizes. For instance, with fp32, up to 70K registers are permissible. Yet, any further increment in the permitted register count can lead to significant register spills, resulting in performance regression. With segmentation, there's typically a 40% to 50% performance reduction.
To bypass segmentation, potential solutions include:

1. use both smem and register for persistent buffer.
2. Thread Block Cluster Reduction: This is a feature present in H100.
3. Cross Grid Reduction.

### **Design for Approach-1: Utilizing both Shared Memory (smem) and Registers for Persistent Buffer**

The fundamental algorithm will be anchored in the `getPersistentBufferStorageParams` function. This function will return a structure containing information about which tensor views (tv) should be transferred to shared memory, as well as the buffer sizes for shared memory and registers. It will also detail if the device has adequate registers and shared memory and if the buffers should be projected to inputs.

**Structure Definition**
```
struct PersistentBufferStorageParams {
  std::vector<TensorView*> smem_persistent_tvs; // Tensor views to be transferred to shared memory
  int64_t smem_buffer_size = -1;
  int64_t regs_buffer_size = -1;
  int64_t smem_overhead = -1;
  bool has_enough_regs_and_smem = false;
  bool project_to_input = false;
};
```
**Buffer Size Calculation & Insufficient Register Handling**

Should the registers be inadequate for holding the persistent buffers, the following procedure is executed:

**(1) Candidate Sorting:**

Populate `sorted_candidate_tvs` with candidate tensor views in a priority sequence determined by the `sort_buffer_tvs()` function.
The sorting criteria aim to reduce both global memory to shared memory (gmem->smem) and shared memory to register (smem->register) data transfers. The sorting encompasses three priority levels:
Priority level | Item | justification
-- | -- | -- 
1 | prioritize tvs with small data type sizes | minimize both gmem->smem and smem/register traffic
2 | prioritize tvs used in outer broadcast | minimize gmem->smem traffic. These tvs are reused in every grid loop.
3 |  prioritize tvs with less consumers | minimize smem->register traffic.

**(2) Buffer Size Accumulation:**
Compute the cumulative buffer size by aggregating across `sorted_candidate_tvs`. For instance, `acc_regs_buffer_sizes[i] `represents the cumulative buffer size of the first `i `buffers according to their sequence in `sorted_candidate_tvs`.

**(3) Shared Memory Allocation:**

- Identify the minimum number of tensor views that need to be transferred to comply with size constraints.
- Log these tensor views
- Mark them for shared memory storage in the `schedulePersistentKernel` function.

**Comment by naoyam** [comment]
How is the sorted tensor list used?

Please add some concrete example scenarios.

**Comment by liqiangxl** [comment]
> How is the sorted tensor list used?
> 
> Please add some concrete example scenarios.

We can use `NVFuserTest.CombinedSharedMemoryPersistent` as a concrete example.
(1) In this test, all 3 input tvs are persistent. tv2 is broadcasted in the outer dim,  tv1 has 1 consumer, and tv0 has 2 consumers.
So the  `sorted_candidate_tvs` is {tv2, tv1, tv0}.
(2) Then the buffer size of each tv is calculated and accumulated in `acc_regs_buffer_sizes`, where 
```
acc_regs_buffer_sizes[0] = 0
acc_regs_buffer_sizes[1] = bufferSizeOf(tv2) + acc_regs_buffer_sizes[0];
acc_regs_buffer_sizes[2] = bufferSizeOf(tv1) + acc_regs_buffer_sizes[1];
acc_regs_buffer_sizes[3] = bufferSizeOf(tv0) + acc_regs_buffer_sizes[2];
```
(3) Then, the number of tensors should be moved to shared memory is set by finding the smallest `i `where `total_regs_buffer_size - acc_regs_buffer_sizes[i] <= available_regs`, this expr means `after moving i-buffers to shared memory, the requested register buffer is less than or equal to avilable register.`

(4) At last, we also need to check if there are enough shared memory to host the moved tensors. If not, `has_enough_regs_and_smem` will be set to false.

**Comment by naoyam** [comment]
So, the list is sorted in the descending order of preference to use shared memory.

This goes back to my original question about the priority. I really don't understand the justifications.

**Comment by liqiangxl** [comment]
Based on our recent offline conversation, we have decided to modify the `sort_buffer_tvs() ` function. Instead of using the level-based sorting, we will adopt a score-based sorting method. The score assigned to each tensor will be determined by the frequency of read/write accesses and its data type.

**Comment by liqiangxl** [comment]
fixed in https://github.com/NVIDIA/Fuser/pull/1954
