### ISSUE TITLE
NVF_CHECK_LT and etc

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1169]
NVF_ERROR and NVF_CHECK are used everywhere, most of which compare two numerical values. In addition to saying `foo < bar` is false, it's useful to print out the runtime values of `foo` and `bar` and even better to do that automatically. 

For reference: https://github.com/abseil/abseil-cpp/blob/c8087ae8bd1e8b25f4e2f38e903b1360005dc4e1/absl/log/internal/check_impl.h#L53

**Comment by fnhirwa** [comment]
Hello @wujingyue is this item still open for contribution I would be happy to work on it 😊
Thanks

**Comment by wujingyue** [comment]
Yes, contribution is very well welcomed!
