### ISSUE TITLE
`uniform`'s Python API needs to be augmented to accept a `Vector` for Dynamic Shapes

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#1247]
[Link to Code](https://github.com/NVIDIA/Fuser/blob/52b98c77cfe312ab7a60171f4befd292c42c234f/csrc/python_frontend/python_bindings.cpp#L2588-L2635)

Specifically this needs to be changed: `std::vector<Scalar>& shape`.

**Comment by zasdfgbnm** [comment]
Potential risk for enabling dynamic shapes for tensor iterator: https://github.com/NVIDIA/Fuser/issues/720

**Comment by kevinstephano** [comment]
Completed.
