### ISSUE TITLE
`normal`'s Python API needs to be augmented to accept a `Vector` for Dynamic Shapes

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#1248]
[Code Link](https://github.com/NVIDIA/Fuser/blob/52b98c77cfe312ab7a60171f4befd292c42c234f/csrc/python_frontend/python_bindings.cpp#L2636-L2683)

Specifically this needs to change: `std::vector<Scalar>& shape`

**Comment by zasdfgbnm** [comment]
Potential risk for enabling dynamic shapes for tensor iterator: https://github.com/NVIDIA/Fuser/issues/720

**Comment by kevinstephano** [comment]
Completed.
