### ISSUE TITLE
Stride mismatch with contiguity info

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#1353]
Repro:

```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id815(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Half, is_cpu=False)
    S1 = fd.define_scalar(None, dtype=DataType.Int)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(None, dtype=DataType.Int)
    S4 = fd.define_scalar(None, dtype=DataType.Int)
    S5 = fd.define_scalar(None, dtype=DataType.Int)
    T6 = fd.ops.slice(T0, start_indices=[0, 0, 0], end_indices=[4, 6, 1], strides=[1, 1, 1])
    T7 = fd.ops.slice(T0, start_indices=[0, 0, 1], end_indices=[4, 6, 5], strides=[1, 1, 1])
    T8 = fd.ops.slice(T0, start_indices=[0, 0, 5], end_indices=[4, 6, 7], strides=[1, 1, 1])
    S9 = fd.define_scalar(0, dtype=DataType.Int)
    S10 = fd.define_scalar(4, dtype=DataType.Int)
    S11 = fd.define_scalar(6, dtype=DataType.Int)
    S12 = fd.define_scalar(0, dtype=DataType.Int)
    V13 = fd.define_vector([S10, S11, S12], dtype=DataType.Int)
    T14 = fd.ops.full(shape=V13, fill_value=S9, dtype=DataType.Half)
    S15 = fd.define_scalar(0, dtype=DataType.Int)
    S16 = fd.define_scalar(4, dtype=DataType.Int)
    S17 = fd.define_scalar(6, dtype=DataType.Int)
    S18 = fd.define_scalar(0, dtype=DataType.Int)
    V19 = fd.define_vector([S16, S17, S18], dtype=DataType.Int)
    T20 = fd.ops.full(shape=V19, fill_value=S15, dtype=DataType.Half)
    fd.add_output(T6)
    fd.add_output(T7)
    fd.add_output(T8)
    fd.add_output(T14)
    fd.add_output(T20)

with FusionDefinition() as fd:
    nvfuser_fusion_id815(fd)

inputs = [
    torch.randn((168,), dtype=torch.float16, device='cuda:0').as_strided((4, 6, 7), (42, 7, 1)),
    2,
    1,
    5,
    9,
    9,
]
fd.execute(inputs)
```
Error:
```bash
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
RuntimeError: Stride mismatch with contiguity info.  allocation domain: iS27{( i0 + ( ( fmax(0, ( fmin(i0, 4) )) ) + ( -i0 ) ) )}rf, iS28{( i1 + ( ( fmax(0, ( fmin(i1, 6) )) ) + ( -i1 ) ) )}rf, bS29{1}rf dim: 1 expected stride: 1 actual stride: 7
Exception raised from validateAllocationSizesAndStrides at /opt/pytorch/nvfuser/csrc/tensor_metadata.cpp:240 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x8d (0x7f6e4f036e2b in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::inferAndValidateAllocationSizesAndStrides(at::Tensor const&, nvfuser::TensorView*, nvfuser::ExpressionEvaluator) + 0x2d6a (0x7f6e4f53effa in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
```

**Comment by wujingyue** [comment]
I'll have to come up with a different reproducer. The one in OP failed: 

```
me @ swagtron : fixit | /opt/pytorch/nvfuser (fix1353*)
$ python repro.py
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/repro.py", line 33, in <module>
    nvfuser_fusion_id815(fd)
  File "/opt/pytorch/nvfuser/repro.py", line 19, in nvfuser_fusion_id815
    T14 = fd.ops.full(shape=V13, fill_value=S9, dtype=DataType.Half)
TypeError: object of type 'nvfuser._C.Vector' has no len()
```

This seems to be a separate problem of `fd.ops.full` not accepting vectors or our autogen generating a bad reproducer. 

A naive change below fixes the reproducer but it doesn't trigger the RuntimeError any more.  

```
diff --git a/repro.py b/repro.py
index a2b036c..4e13090 100644
--- a/repro.py
+++ b/repro.py
@@ -12,17 +12,9 @@ def nvfuser_fusion_id815(fd : FusionDefinition) -> None :
     T7 = fd.ops.slice(T0, start_indices=[0, 0, 1], end_indices=[4, 6, 5], strides=[1, 1, 1])
     T8 = fd.ops.slice(T0, start_indices=[0, 0, 5], end_indices=[4, 6, 7], strides=[1, 1, 1])
     S9 = fd.define_scalar(0, dtype=DataType.Int)
-    S10 = fd.define_scalar(4, dtype=DataType.Int)
-    S11 = fd.define_scalar(6, dtype=DataType.Int)
-    S12 = fd.define_scalar(0, dtype=DataType.Int)
-    V13 = fd.define_vector([S10, S11, S12], dtype=DataType.Int)
-    T14 = fd.ops.full(shape=V13, fill_value=S9, dtype=DataType.Half)
+    T14 = fd.ops.full(shape=[4, 6, 0], fill_value=S9, dtype=DataType.Half)
     S15 = fd.define_scalar(0, dtype=DataType.Int)
-    S16 = fd.define_scalar(4, dtype=DataType.Int)
-    S17 = fd.define_scalar(6, dtype=DataType.Int)
-    S18 = fd.define_scalar(0, dtype=DataType.Int)
-    V19 = fd.define_vector([S16, S17, S18], dtype=DataType.Int)
-    T20 = fd.ops.full(shape=V19, fill_value=S15, dtype=DataType.Half)
+    T20 = fd.ops.full(shape=[4, 6, 0], fill_value=S15, dtype=DataType.Half)
     fd.add_output(T6)
     fd.add_output(T7)
     fd.add_output(T8)
```

**Comment by wujingyue** [comment]
I was able to reproduce the problem after I rm -rf bin build and rebuild. 👀

**Comment by kevinstephano** [comment]
> I'll have to come up with a different reproducer. The one in OP failed:
> 
> ```
> me @ swagtron : fixit | /opt/pytorch/nvfuser (fix1353*)
> $ python repro.py
> Traceback (most recent call last):
>   File "/opt/pytorch/nvfuser/repro.py", line 33, in <module>
>     nvfuser_fusion_id815(fd)
>   File "/opt/pytorch/nvfuser/repro.py", line 19, in nvfuser_fusion_id815
>     T14 = fd.ops.full(shape=V13, fill_value=S9, dtype=DataType.Half)
> TypeError: object of type 'nvfuser._C.Vector' has no len()
> ```
> 
> This seems to be a separate problem of `fd.ops.full` not accepting vectors or our autogen generating a bad reproducer.
> 
> A naive change below fixes the reproducer but it doesn't trigger the RuntimeError any more. cc @kevinstephano
> 
> ```
> diff --git a/repro.py b/repro.py
> index a2b036c..4e13090 100644
> --- a/repro.py
> +++ b/repro.py
> @@ -12,17 +12,9 @@ def nvfuser_fusion_id815(fd : FusionDefinition) -> None :
>      T7 = fd.ops.slice(T0, start_indices=[0, 0, 1], end_indices=[4, 6, 5], strides=[1, 1, 1])
>      T8 = fd.ops.slice(T0, start_indices=[0, 0, 5], end_indices=[4, 6, 7], strides=[1, 1, 1])
>      S9 = fd.define_scalar(0, dtype=DataType.Int)
> -    S10 = fd.define_scalar(4, dtype=DataType.Int)
> -    S11 = fd.define_scalar(6, dtype=DataType.Int)
> -    S12 = fd.define_scalar(0, dtype=DataType.Int)
> -    V13 = fd.define_vector([S10, S11, S12], dtype=DataType.Int)
> -    T14 = fd.ops.full(shape=V13, fill_value=S9, dtype=DataType.Half)
> +    T14 = fd.ops.full(shape=[4, 6, 0], fill_value=S9, dtype=DataType.Half)
>      S15 = fd.define_scalar(0, dtype=DataType.Int)
> -    S16 = fd.define_scalar(4, dtype=DataType.Int)
> -    S17 = fd.define_scalar(6, dtype=DataType.Int)
> -    S18 = fd.define_scalar(0, dtype=DataType.Int)
> -    V19 = fd.define_vector([S16, S17, S18], dtype=DataType.Int)
> -    T20 = fd.ops.full(shape=V19, fill_value=S15, dtype=DataType.Half)
> +    T20 = fd.ops.full(shape=[4, 6, 0], fill_value=S15, dtype=DataType.Half)
>      fd.add_output(T6)
>      fd.add_output(T7)
>      fd.add_output(T8)
> ```

This issue seems to go away with when I pull nvFuser TOT.  I wonder if we were just seeing an issue related to an older nvFuser commit that did not have the Dynamic Shapes API.

**Comment by wujingyue** [comment]
> This issue seems to go away with when I pull nvFuser TOT. I wonder if we were just seeing an issue related to an older nvFuser commit that did not have the Dynamic Shapes API.

You are right -- I just confirmed that. Sorry for the noise, Kevin -- I still don't know how I ended up checking out an older commit. I'll make sure to rebuild with `rm -rf bin build` next time.
