### ISSUE TITLE
Alias analysis on inputs and intermediate tensors

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#1401]
Currently our alias analysis only handles output to input / output to output.

This is slightly different from what bookend optimization does, which seems to give better perf in some attention block. Bookend optimization would strip meta-operation (view/squeeze/slice e.t.c.) on the bookend of a fusion and pass in tensor with mutated strides.
This should be doable given the alias analysis information. We just need some mechanics to plumb this through our segmenter to know *when* and *where* to stop merging segments, as well as *when* to initiate segmentation even though the entire fusion could be scheduled as a single kernel.

For example, when we handle meta operations on inputs, we might need to consider whether stripping aliases are beneficial, even though they give a slightly smaller fusion IR.

```
  auto tv0 = makeSymbolicTensor(2);
  auto s0 = IrBuilder::create<Val>(DataType::Index);
  auto s1 = IrBuilder::create<Val>(DataType::Index);
  auto tv1 = unsqueeze(tv0, -1);
  auto tv2 = expand(tv1, {s0, s1});
  // ... some fusion uses both tv0 and tv2
```

If we decided to strip the unsqueeze and expand from the actual codegen kernel, we are going to pass two tensor inputs to the kernel `tv0` and `tv2` here.
Even though the two tensors are just aliasing and cache would help us, it might still be worth keeping these operations just so we have a single input to the fusion.

**Comment by jjsjann123** [comment]
cc'ing @wujingyue

**Comment by wujingyue** [comment]
We are going to talk about this soon, but just a preliminary thought: for this particular example, why do we **need** alias analysis to generate optimal code? Even without alias analysis, I expect nvFuser to already inline `unsqueeze` and `expand` (into downstream ops) and make them cheap index calculation.

**Comment by wujingyue** [comment]
@jjsjann123 and I looked at some other cases. Here's an interesting one: 

```
def nvfuser_fusion_id23(fd : FusionDefinition) -> None :
    S0 = fd.define_scalar(None, dtype=DataType.Double)
    S1 = fd.define_scalar(None, dtype=DataType.Double)
    S2 = fd.define_scalar(None, dtype=DataType.Double)
    T3 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False)
    T4 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.BFloat16, is_cpu=False)
    T5 = fd.ops.cast(T4, dtype=DataType.Float)
    T6 = fd.ops.mul(T5, T5)
    T7 = fd.ops.mul(T6, T5)
    S8 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T9 = fd.ops.mul(S8, T5)
    S10 = fd.define_scalar(0.0447150, dtype=DataType.Double)
    T11 = fd.ops.mul(S10, T7)
    T12 = fd.ops.add(T5, T11)
    S13 = fd.define_scalar(0.797885, dtype=DataType.Double)
    T14 = fd.ops.mul(S13, T12)
    T15 = fd.ops.tanh(T14)
    S16 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T17 = fd.ops.add(S16, T15)
    S18 = fd.define_scalar(16, dtype=DataType.Int)
    S19 = fd.define_scalar(128, dtype=DataType.Int)
    S20 = fd.define_scalar(3072, dtype=DataType.Int)
    V21 = fd.define_vector([S18, S19, S20], dtype=DataType.Int)
    T22 = fd.ops.reshape(T3, new_shape=V21)
    T23 = fd.ops.cast(T22, dtype=DataType.Float)
    T24 = fd.ops.mul(T23, T17)
    T25 = fd.ops.mul(T23, T9)
    T26 = fd.ops.mul(T15, T15)
    S27 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T28 = fd.ops.sub(S27, T26)
    T29 = fd.ops.mul(T25, T28)
    T30 = fd.ops.mul(T29, S2)
    T31 = fd.ops.mul(T30, S1)
    T32 = fd.ops.mul(T24, S0)
    T33 = fd.ops.add(T30, T32)
    T34 = fd.ops.mul(T31, T5)
    T35 = fd.ops.mul(T31, T6)
    T36 = fd.ops.add(T33, T35)
    T37 = fd.ops.mul(T34, T5)
    T38 = fd.ops.add(T36, T37)
    T39 = fd.ops.add(T38, T37)
    T40 = fd.ops.cast(T39, dtype=DataType.BFloat16)
    S41 = fd.define_scalar(2048, dtype=DataType.Int)
    S42 = fd.define_scalar(3072, dtype=DataType.Int)
    V43 = fd.define_vector([S41, S42], dtype=DataType.Int)
    T44 = fd.ops.reshape(T40, new_shape=V43)
    S45 = fd.define_scalar(2048, dtype=DataType.Int)
    S46 = fd.define_scalar(3072, dtype=DataType.Int)
    V47 = fd.define_vector([S45, S46], dtype=DataType.Int)
    T48 = fd.ops.reshape(T40, new_shape=V47)
    T49 = fd.ops.permute(T48, dims=[1, 0])
    T50 = fd.ops.sum(T39, axes=[0, 1], keepdim=False, dtype=DataType.Null)
    T51 = fd.ops.cast(T50, dtype=DataType.BFloat16)
    fd.add_output(T44)
    fd.add_output(T49)
    fd.add_output(T51)
```

`T44` and `T49` are both aliases of `T40`, so the optimal kernel should put data in one of them and make the other one an alias.

**Comment by wujingyue** [comment]
[My WIP](https://github.com/NVIDIA/Fuser/commit/8a98c6f375f6f83099651611b6913d18f39d7095) doesn't quite work. The problem is that ~device lowering~ scheduling breaks the aliasing chain between the two outputs (`T5_g` and `T3_g`), even though there was a chain from `T5_g` (well, it was probably called a different name) to `T3_g` **before** ~lowering~ scheduling. Therefore, when calling `ee.evaluate(T3_g)`, the result isn't derived from the tensor bound to `T5_g`. Will try moving alias analysis after lowering... 

```
(gdb) p kernel->printMath(true)
Inputs:
  T0_g[ iS69{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iS70{1}, iS68{1}, iS66{128} ], float
Outputs:
  T5_g[ iblockIdx.x34{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS35{1}, iS33{1}, ithreadIdx.x31{128} ] ca_pos( 2 ) produce_pos( 4 ), float
  T3_g[ iblockIdx.x83{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS84{1}, iS82{1}, ithreadIdx.x80{128} ] ca_pos( 2 ) produce_pos( 4 ), float

%kernel_math {
T4_l[ iblockIdx.x62{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS63{1}, iS61{1}, ithreadIdx.x59{128} ] ca_pos( 2 )
   = Set( T0_g[ iS69{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iS70{1}, iS68{1}, iS66{128} ], cache_op=Streaming )
T1_l[ iblockIdx.x55{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS56{1}, iS54{1}, ithreadIdx.x52{128} ] ca_pos( 4 ) produce_pos( 2 )
   = T4_l[ iblockIdx.x62{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS63{1}, iS61{1}, ithreadIdx.x59{128} ] ca_pos( 2 )
   + T4_l[ iblockIdx.x62{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS63{1}, iS61{1}, ithreadIdx.x59{128} ] ca_pos( 2 );
T2_l[ iblockIdx.x48{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS49{1}, iS47{1}, ithreadIdx.x45{128} ] ca_pos( 4 ) produce_pos( 4 ) = view( T1_l[ iblockIdx.x55{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS56{1}, iS54{1}, ithreadIdx.x52{128} ] ca_pos( 4 ) produce_pos( 2 ) )
T6_l[ iblockIdx.x41{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS42{1}, iS40{1}, ithreadIdx.x38{128} ] ca_pos( 4 ) produce_pos( 4 )
   = Set( T2_l[ iblockIdx.x48{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS49{1}, iS47{1}, ithreadIdx.x45{128} ] ca_pos( 4 ) produce_pos( 4 ), cache_op=Streaming )
T5_g[ iblockIdx.x34{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS35{1}, iS33{1}, ithreadIdx.x31{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T6_l[ iblockIdx.x41{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS42{1}, iS40{1}, ithreadIdx.x38{128} ] ca_pos( 4 ) produce_pos( 4 ), cache_op=Streaming )
T7_l[ iblockIdx.x76{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS77{1}, iS75{1}, ithreadIdx.x73{128} ] ca_pos( 4 ) produce_pos( 4 )
   = Set.Permute( T2_l[ iblockIdx.x48{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS49{1}, iS47{1}, ithreadIdx.x45{128} ] ca_pos( 4 ) produce_pos( 4 ), cache_op=Streaming )
T3_g[ iblockIdx.x83{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS84{1}, iS82{1}, ithreadIdx.x80{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T7_l[ iblockIdx.x76{( ceilDiv(( ceilDiv(( ceilDiv(( ( 2 * 3 ) * 5 ), 128) ), 1) ), 1) )}, iUS77{1}, iS75{1}, ithreadIdx.x73{128} ] ca_pos( 4 ) produce_pos( 4 ), cache_op=Streaming )
}
```

**Comment by jjsjann123** [comment]
Does it make sense for us to mutate/annotate the fusion so that lowering would leave something untouched?

*I think* the only reason lowering is changing it here is because we want to handle permutation. but if we don't need to do that would just instead use alias/ExpressionEvaluation, there's no point of applying that lowering logic in the first place.

WDYT @naoyam @xwang233

**Comment by wujingyue** [comment]
I might have spoken too soon about device lowering. I suspect the "chains" are broken because the scheduler tries to `cacheBefore` and `cacheAfter`, e.g., code around `T7_l = Set.Permute(T2_l)`. I think running alias analysis on the segmented and scheduled fusion should solve this particular case. This also helps to capture meta-op-only fusions after segmentation.

**Comment by jjsjann123** [comment]
ha, sorry I forgot about the context when we were chatting on the isle earlier.

> I think running alias analysis on the segmented and scheduled fusion should solve this particular case. This also helps to capture meta-op-only fusions after segmentation.

Agree'd on "running alias analysis on the segmented and scheduled fusion", we should probably do that, given that we are only limiting alias analysis on "kernel" I/O tensors.

In the meantime, my previous comment was trying to point out that, we *want* our alias analysis to assist scheduling as well. In the example we have, the only reason that `transpose scheduler` kicked in to insert the cacheBefore/cacheAfter is because of the  permutation op.
But since we are already aliasing the output from the permutation tensor, effectively we have removed the op from the fusion and we should no-longer using transpose scheduler there in the first place.

**Comment by wujingyue** [comment]
> we have removed the op from the fusion and we should no-longer using transpose scheduler there in the first place.

Gotcha! That makes a lot of sense. 

Alternatively, at least for this particular case, segmentation can separate out meta-op-only regions and turn it into an empty kernel. `NoOpScheduler` already accepts meta-op-only regions, so it's a matter of improving the segmentation algorithm to not over-merge. That may be a much larger effort to take.

**Comment by wujingyue** [comment]
I changed the title to "alias analysis between outputs" because that is what I fixed and is apparently enough for the gpt2-nanogpt benchmarks I've seen. If needed, let's file another issue about intermediate tensors.
