### ISSUE TITLE
Failed chain projections when project persistent buffer to its persistent producers

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#1406]
In normalization scheduler, persistent tvs can be projected to its immediate persistent producers if `project_persistent_buffers = False`.
However, current implentation fails if a chain projection is required. Consider the following case where T1, T2, T3 are persistent buffers, ideally, T2 and T3 should be projected to T1.
```
      T1 = f(T0); Tx = add(T1, broadcast(sum(T1)));
      T2 = f(T1); Ty = add(T2, broadcast(sum(T2)));
      T3 = f(T2); Tz = add(T3, broadcast(sum(T3)));
```
If T2 is projected to T1 before T3 is projected, we get:
```
      T1 = f(T0); Tx = add(T1, broadcast(sum(T1)));
      T2 = f(T1); Ty = add(f(T1), broadcast(sum(T2)));
      T3 = f(f(T1)); Tz = add(T3, broadcast(sum(T3)));
```
Then, T3's producer is changed to f(T1) which is not a persistent tensor. So T3 can't be projected back to T1.

To fix this issue, we should: set a projection order based on dependencies. In this case, the visiting order should be [T3, T2, T1]. After project T3 to its producers, we have:
```
 Tz = add(f(T2),broadcast(sum(T3)));
```
Then,  continue project T2 to its producers, we have:
```
      Tz = add(f(f(T1)),broadcast(sum(T3)));
      Ty = add(f(T1), broadcast(sum(T2)));
```

The only left persistent buffer is T1.

**Comment by naoyam** [comment]
Just to clarify, the T2 and T3 inputs to the sum ops should also be replaced, right?

**Comment by liqiangxl** [comment]
> Just to clarify, the T2 and T3 inputs to the sum ops should also be replaced, right?

why? For example:
After project T3 to its producers, in the fusion we have:
`T3 = f(T2); Tz = add(f(T2),broadcast(sum(T3)));`
Here `sum(T3)` is consuming T3 generated by `T3 = f(T2)`.

Then, continue project T2 to its producers, we have:
```
T2 = f(T1);  Ty = add(f(T1), broadcast(sum(T2)));
T3 = f(f(T1));  Tz = add(f(f(T1)),broadcast(sum(T3)));
```
similarly, `sum(T2)` is consuming T2 generated by `T2 = f(T1)`.

**Comment by naoyam** [comment]
Ah, OK, I didn't remember when replacing the uses of a persistent buffer we skip the reduction usage path.
