### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#1407]
There's a persisting OOM error recently. See for example https://github.com/NVIDIA/Fuser/actions/runs/7032815711, which was a CI test for PR #1319. The specific test failing is `GpuViewTest.FusionReshapeVectorize`. There was an attempt to fix the error (#1382), but apparently it was not enough.

The error message seems to suggest there's something occupying a large chunk of GPU memory aside from the PyTorch itself:

```
CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacity of 15.78 GiB of which 20.75 MiB is free. Process 3304 has 15.76 GiB memory in use. Of the allocated memory 8.76 GiB is allocated by PyTorch, and 55.88 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Here, PyTorch itself only used 8.75 GB, but the total usage was 15.76 GB, and we don't know where the remaining 7 GB went.

**Comment by naoyam** [comment]
CC: @jacobhinkle, @xwang233

**Comment by jacobhinkle** [comment]
I reproduced this on a dgx-v100 16GB with nothing else running.

**Comment by jacobhinkle** [comment]
I monitored the used memory with nvidia-smi while running the tests with this command line:
```
(build/nvfuser_tests | ts '%s ' | tee ~/mem_used_reshapevectorize.nvfuser_tests.stdout &); while true; do sleep 1;nvidia-smi --query-gpu=memory.used --format=csv,noheader -i 0; done | tee ~/mem_used_reshapevectorize.txt
```
The log shows that the process has 7185 MB allocated just before the failing test, which matches the amount of unallocated memory. Maybe there is a problem with how we clear the allocator.

**Comment by jacobhinkle** [comment]
Note that the used memory does decrease many times before this point, so the allocator is _actually_ being cleared most of the time.

**Comment by naoyam** [comment]
Is it deterministic?

**Comment by naoyam** [comment]
Does it happen when only the test is run?

**Comment by jacobhinkle** [comment]
> Does it happen when only the test is run?

No. No error if only the test is run, or if only the GpuViewTest group is run.

**Comment by naoyam** [comment]
Could you try some old commit of nvfuser, maybe a month old? I don't remember we saw these errors before, so if we use the same PyTorch build with an old nvfuser and still see the error, I think it's highly likely there's something wrong with the latest PyTorch itself.

**Comment by jacobhinkle** [comment]
This is mysterious. The simplest workaround would just be to reduce the sizes in the test. I reduced the size of the input to (256, 256, 256) and the error goes away.

**Comment by jacobhinkle** [comment]
No error in this container using f450ece8f. I will bisect from here.

**Comment by jacobhinkle** [comment]
Bisect found 2a47d43c (#1327) as the possible culprit. I can't explain why PyTorch doesn't list all of the memory, but that commit does increase the use of the automated reference computation using `evaluate()`. I can imagine that increasing memory use since it will evaluate each step of the fusion using ATen, whereas previously many of the references might use fused functions like `at::gelu` instead of the 5 ops that `gelu` expands to, for example.

cc @Priya2698  @zasdfgbnm

**Comment by naoyam** [comment]
@jacobhinkle Thanks for narrowing down to the commit. 

@zasdfgbnm Could this be an nvfuser issue?
