### ISSUE TITLE
InferShapeOfOutput returns a wrong shape. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1524]
This is triggered by #1503, but I managed to reproduce this on head. We haven't tested customizing allocation domains of segment boundaries, a fairly uncommon case until #1503. 

To reproduce this, 

```
git fetch origin infer_shape_bug
git checkout infer_shape_bug
python setup.py develop --debug && bin/nvfuser_tests --gtest_filter=AllocationDomainTest.Bug
```

I guess the root cause is that https://github.com/NVIDIA/Fuser/blob/582f29583ce337191c4d273781994ad03b121aee/csrc/executor.cpp#L589 should populate `symbolic_sizes` in rfactor order not allocation?

**Comment by wujingyue** [comment]
Do you agree on the root cause? I'm wondering how hard it is to fix this bug, because I'm inclined to submit #1503 after this is fixed, because #1503 will expose more patterns like this...

**Comment by jjsjann123** [comment]
Yeah the issue looks about right to me.

We should only use the allocation domain to compute strides, but for the actual shape, we should be using rfactor domain. I'll jump on this~

**Comment by jjsjann123** [comment]
FYI, the repro branch is `infer_shape` I think. Because I wasn't getting `infer_shape_bug` from our repo.

**Comment by jjsjann123** [comment]
:cry: 

Turns out I don't know what I was doing.... I thought I can mimic what's done with the output tensor here and get away with it but that seems to be not the case.

Maybe I missed something obvious, I'll follow up in PR #1531

**Comment by jjsjann123** [comment]
Turns out it did work. just missed the duplicated application of the transform. :laughing: 

sorry for the delayed turn-around, got really busy chatting with folks throughout the day.
