### ISSUE TITLE
Missing `C.cpython-39-x86_64-linux-gnu.so` after first install with clean build

### ISSUE THREAD

**Issue by rdspring1** [NVIDIA/Fuser#153]
Run `python setup.py install` with clean build

Check: `ls /home/rspring/miniconda3/lib/python3.9/site-packages/nvfuser-0.0.8+gitaa78d0f-py3.9-linux-x86_64.egg/nvfuser`
First install: 
`cmake  __init__.py  lib  nvfuser_version.py  __pycache__  pytorch_utils.py  version.py`
Second install:  
`_C.cpython-39-x86_64-linux-gnu.so  cmake  __init__.py  lib  nvfuser_version.py  __pycache__  pytorch_utils.py  version.py`

Triggers this error when importing nvfuser:
```
>>> import nvfuser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rspring/miniconda3/lib/python3.9/site-packages/nvfuser-0.0.8+gitaa78d0f-py3.9-linux-x86_64.egg/nvfuser/__init__.py", line 15, in <module>
    from . import _C
ImportError: cannot import name '_C' from partially initialized module 'nvfuser' (most likely due to a circular import) (/home/rspring/miniconda3/lib/python3.9/site-packages/nvfuser-0.0.8+gitaa78d0f-py3.9-linux-x86_64.egg/nvfuser/__init__.py)
```

**Comment by jjsjann123** [comment]
It doesn't look clear to me how this can easily be patched. Since we do need to copy it within `build_ext`, where it gives us the right file name to copy the pybind target. I'll ask this in dev channel, maybe someone else would know more about this. :crossed_fingers:

**Comment by crcrpar** [comment]
I'm a bit paranoid about the sanity of this `del` https://github.com/NVIDIA/Fuser/blob/13a90b6d18273acc6977269d90cfc28cb5e1c8b0/setup.py#L129-L130
since locally https://github.com/NVIDIA/Fuser/commit/d5794fc6626f11acdb2295a9883027e3d325acaf let `_C.*.so` be installed into `/path/to/site-packages/nvfuser-0.0.9+git582e88e-py3.9-linux-x86_64.egg/nvfuser` 

```
...
zip_safe flag not set; analyzing archive contents...
nvfuser.__pycache__._C.cpython-39: module references __file__
nvfuser.__pycache__.__init__.cpython-39: module references __file__
nvfuser.__pycache__.pytorch_utils.cpython-39: module references __file__
nvfuser.__pycache__.utils.cpython-39: module references __file__
nvfuser_python_utils.__pycache__.patch_nvfuser.cpython-39: module references __file__

mkozuki@mkozuki-desktop ~/ghq/github.com/crcrpar/fuser support_install_ ⇡
torchdev ❯ ls -g ~/miniconda3/envs/torchdev/lib/python3.9/site-packages/nvfuser-0.0.9+gitd5794fc-py3.9-linux-x86_64.egg/nvfuser
total 60
-rwxr-xr-x 1 14952 Apr 27 21:58 _C.cpython-39-x86_64-linux-gnu.so
-rw-rw-r-- 1   427 Apr 27 21:58 _C.py
drwxrwxr-x 3  4096 Apr 27 21:58 include
-rw-rw-r-- 1  7202 Apr 27 21:58 __init__.py
drwxrwxr-x 2  4096 Apr 27 21:58 lib
-rw-rw-r-- 1  2151 Apr 27 21:58 nvfuser_version.py
drwxrwxr-x 2  4096 Apr 27 21:58 __pycache__
-rw-rw-r-- 1  1443 Apr 27 21:58 pytorch_utils.py
drwxrwxr-x 3  4096 Apr 27 21:58 share
-rw-rw-r-- 1   151 Apr 27 21:58 utils.py
-rw-rw-r-- 1    34 Apr 27 21:58 version.py

```

**Comment by jjsjann123** [comment]
@crcrpar 's PR is merged, can we close this issue now?

**Comment by rdspring1** [comment]
I'm seeing this error in the tutorial build:
```
CMake Error at /home/rspring/miniconda3/lib/python3.9/site-packages/nvfuser-0.0.9+git3998bcb-py3.9-linux-x86_64.egg/nvfuser/share/cmake/nvfuser/NvfuserConfig.cmake:83 (message):
  The imported target "nvfuser" references the file

     "/home/rspring/miniconda3/lib/python3.9/site-packages/nvfuser-0.0.9+git3998bcb-py3.9-linux-x86_64.egg/nvfuser/lib/libnvfuser.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/rspring/miniconda3/lib/python3.9/site-packages/nvfuser-0.0.9+git3998bcb-py3.9-linux-x86_64.egg/nvfuser/share/cmake/nvfuser/NvfuserConfig.cmake"

  but not all the files it references.
```

**Comment by crcrpar** [comment]
what is "the tutorial build"?

**Comment by jjsjann123** [comment]
hmmm. why are we linking against the pybind library in the cmake example?!  `libnvfuser.so`

That shouldn't be needed. I thought we are only linking against the codegen lib https://github.com/NVIDIA/Fuser/blob/main/examples/sinh_libtorch/CMakeLists.txt#L13

**Comment by jjsjann123** [comment]
ah... it's probably failing that in the find package thing...

https://github.com/NVIDIA/Fuser/blob/3998bcbaaf58a7b33f7649825334d4e45d7145e4/CMakeLists.txt#L310
I think we need to tell cmake not to look for the python interface target as a target for the config file

**Comment by rdspring1** [comment]
The tutorial build is https://github.com/NVIDIA/Fuser/tree/main/examples/sinh_libtorch.
We want to build and run this tutorial when installing nvfuser.

**Comment by crcrpar** [comment]
is this finally solved?

... ah we have to deal with [libc10_cuda](https://github.com/NVIDIA/Fuser/pull/275#issuecomment-1534472357)?

**Comment by jjsjann123** [comment]
Now I don't remember where `libc10_cuda` issue was showing up from. I'm guessing it's with our tests?!

But the `.so` issue should be resolved. At least it worked for my pip wheel build. I'll let @rdspring1 verify and close this one

**Comment by jjsjann123** [comment]
ah, that makes sense. So that's a different issue from what's reported here. We can track on the side.

Meanwhile, we can verify and close this one. I think it's all cleared.

**Comment by rdspring1** [comment]
It works for me.
