### ISSUE TITLE
OOM with increasing number of tests in Python Benchmarks

### ISSUE THREAD

**Issue by Priya2698** [NVIDIA/Fuser#1537]
PR #1488 ran into the pytest process being killed due to OOM with increase in number of tests in a single file. Possible reasons:

1. Kernel cache entries: https://github.com/NVIDIA/Fuser/pull/1532#issuecomment-1857349564
2. Pytest collects and maintains a test status for each test to generate a report at the end. However it is unlikely to alone consume ~30GB memory for 12.5k tests.

**Comment by naoyam** [comment]
Is it CPU or GPU memory?

**Comment by Priya2698** [comment]
> Is it CPU or GPU memory?

CPU memory.

**Comment by naoyam** [comment]
#1407 was an issue with GPU memory. Compiled kernels are loaded into GPU memory, and eventually it took a significant portion of the available memory.

I don't think I have seen CPU OOM errors. Can you get more detailed information such as the physical memory capacity, how much was used for pytest, etc?

**Comment by Priya2698** [comment]
Update: PR #1543 resolves the GPU OOM errors seen in PR #1488. The GPU memory usage pattern does not indicate that the errors are due to kernels being cached since the memory is eventually released. However, larger tests run consecutively still fail if memory allocated on the GPU in a previous test is not released before the next test executes.

**Comment by jacobhinkle** [comment]
So collecting garbage then clearing cache reduces the host memory enough to prevent OOM? If so then I think that implies the underlying cause is not the kernel cache. In a failing test how many Fusions/kernels do we have when it fails?

**Comment by csarofeen** [comment]
I wonder if it's the pytorch caching allocator failing due to fragmentation.

**Comment by Priya2698** [comment]
> Update: PR #1543 resolves the GPU OOM errors seen in PR #1488. The GPU memory usage pattern does not indicate that the errors are due to kernels being cached since the memory is eventually released. However, larger tests run consecutively still fail if memory allocated on the GPU in a previous test is not released before the next test executes.

Each benchmark has only one fusion being executed for a range of input sizes. So the kernel cache size should not be large or result in OOM.

**Comment by csarofeen** [comment]
Okay, yeah, if adding `torch.cuda.empty_cache()` resolves it then it's likely the PyTorch caching allocator.

**Comment by naoyam** [comment]
Should this be closed?
