### ISSUE TITLE
MbarrierTest.Simple hangs on H100

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#1552]
Nvfuser binary test on H100 stuck at `MBarrierTest.Simple`

@xwang233, @zasdfgbnm

**Comment by zasdfgbnm** [comment]
Looks like I didn't `__syncthreads` after mbarrier init. This might be the reason. Self-assign to write a fix.

**Comment by naoyam** [comment]
Close for now. Will open if the error happens again.
