### ISSUE TITLE
Failed to give segment boundaries a non-contiguous allocation domain. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1568]
```
$ git fetch origin wjy/allocation_on_segment
$ git checkout wjy/allocation_on_segment
$ _bn && bin/nvfuser_tests --gtest_filter=*Boundary
```

It fails the assertion here: https://github.com/NVIDIA/Fuser/blob/101530ec09a7eab9937f277715be0e3ecc1478b6/csrc/scheduler/registry_utils.cpp#L124-L125

I'm not sure whether this is a bug or WAI. This is related to #1502 where we may want to explicit set the allocation domain of a concat input to enable aliases. Let me know what you think, @jjsjann123

**Comment by jjsjann123** [comment]
The comment sounds like this is just for sanity check on our previous assumption. We should lift this.
