### ISSUE TITLE
`lessThan` ran into infinite recursion.

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1572]
```
$ git fetch origin wjy/recurse
$ git checkout wjy/recurse
$ _bn && NVFUSER_DISABLE=parallel_compile python repro.py
```

`NVFUSER_DISABLE=parallel_compile` is there to display the call stack better. 

To make debugging easier, I limited recursion of `lessEqual` to 100 levels. The reproducer is still valid but slower with that check removed.

**Comment by wujingyue** [comment]
When I `gdb`ed this, the top frames of the call stack alternate between `lessEqual(0, i4089)` and `lessEqual(blockIdx.x, i4089)`. Below is the containing fusion: 

```
(gdb) p x->fusion()->printMath(true)
Inputs:
  T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], __bfloat
Outputs:
  T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 ), __bfloat

%kernel_math {
s3546 = getMetaData(T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ])
a3547 = s3546.logical_size
i3549 = a3547[0]
i823 = fmin(i3549, 16);
i825 = fmax(0, i823);
i837 = fmin(32, 32);
i839 = fmax(0, i837);
a3551 = s3546.logical_size
i3553 = a3551[2]
i851 = fmin(i3553, 4096);
i853 = fmax(0, i851);
a3555 = s3546.logical_size
i3557 = a3555[3]
i862 = fmin(i3557, 0);
i864 = fmax(0, i862);
T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 )
   = slice( T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], { {0, i825, 1} {0, i839, 1} {0, i853, 1} {0, i864, 1} } )
T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 ), cache_op=Streaming )
}
```

**Comment by wujingyue** [comment]
With https://github.com/NVIDIA/Fuser/commit/a8b19a3422bbb8bec6eca268980131c2f6ac0a69, I managed to print out the known less-thans and less-equals. They look wrong -- `blockIdx.x < 0` and `0 <= blockIdx.x` can't happen at the same time. 

```
known: 0 < i2
known: 0 < i3553
known: 0 < i3549
known: threadIdx.z < blockDim.z
known: 0 < blockDim.z
known: threadIdx.y < blockDim.y
known: 0 < blockDim.y
known: threadIdx.x < blockDim.x
known: 0 < blockDim.x
known: blockIdx.z < gridDim.z
known: 0 < gridDim.z
known: blockIdx.y < gridDim.y
known: 0 < gridDim.y
known: blockIdx.x < gridDim.x
known: 0 < gridDim.x
known: blockIdx.x < 0
known: threadIdx.x < 128
known: 0 <= threadIdx.z
known: 0 <= threadIdx.y
known: 0 <= threadIdx.x
known: 0 <= blockIdx.z
known: 0 <= blockIdx.y
known: 0 <= blockIdx.x
```

**Comment by jacobhinkle** [comment]
Just dumping a little more info here since I took a few minutes to check this out.

The scheduled segment hitting this error looks like this:
```
Inputs:
  T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], __bfloat
Outputs:
  T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 ), __bfloat

%kernel_math {
s3546 = getMetaData(T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ])
a3547 = s3546.logical_size
i3549 = a3547[0]
i823 = fmin(i3549, 16);
i825 = fmax(0, i823);
i837 = fmin(32, 32);
i839 = fmax(0, i837);
a3551 = s3546.logical_size
i3553 = a3551[2]
i851 = fmin(i3553, 4096);
i853 = fmax(0, i851);
a3555 = s3546.logical_size
i3557 = a3555[3]
i862 = fmin(i3557, 0);
i864 = fmax(0, i862);
T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 )
   = slice( T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], { {0, i825, 1} {0, i839, 1} {0, i853, 1} {0, i864, 1} } )
T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 ), cache_op=Streaming )
}
```
It's a simple `set(slice(input))` kernel, but in this case the extent `( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1)` simplifies to zero. It is zero because of the factor `T6.size[3] + max(0, min(T6.size[3], 0)) - T6.size[3]` which clearly is zero.

The relevant part of the concretized, unsegmented fusion looks like this:
```
T9_l[ iS148{i0}rf, iS149{32}rf, iS150{i1}rf, iS151{( ceilDiv(( ceilDiv(i2, 32) ), 3) )}rf ]                                             
   = slice( T6_l[ iS140{i0}, iS141{32}, iS142{i1}, iS143{( ceilDiv(( ceilDiv(i2, 32) ), 3) )} ], { {0, i339, 1} {0, i353, 1} {0, i367, 1
} {0, i381, 1} } )
```
At first I thought this might be an empty tensor bug, but it doesn't look like T6 or T9 (hence T45) are empty. It could be a bug in slice extent expressions (see #460), but at first glance those seem fine in the concretized fusion.

**Comment by wujingyue** [comment]
The assumptions are generated by [function `getAssumptions`](https://github.com/NVIDIA/Fuser/blob/101530ec09a7eab9937f277715be0e3ecc1478b6/csrc/device_lower/pass/scalar_hoist.cpp#L301). 

With `NVFUSER_DUMP=lower_verbose NVFUSER_DISABLE=parallel_compile`, I was able to dump the exprs before IndexLowering, where the crash happened. 

```
After processMisalignedVectorization:
i837 = ALLOCATE(buffer=i837, mem_type=register, size=1, zero_init=false)

i837 = fmin(32, 32);

i839 = ALLOCATE(buffer=i839, mem_type=register, size=1, zero_init=false)

i839 = fmax(0, i837);

s3546 = ALLOCATE(buffer=s3546, mem_type=register, size=1, zero_init=false)

s3546 = getMetaData(T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ])

a3555 = ALLOCATE(buffer=a3555, mem_type=register, size=1, zero_init=false)

a3555 = s3546.logical_size

i3557 = ALLOCATE(buffer=i3557, mem_type=register, size=1, zero_init=false)

i3557 = a3555[3]

i862 = ALLOCATE(buffer=i862, mem_type=register, size=1, zero_init=false)

i862 = fmin(i3557, 0);

i864 = ALLOCATE(buffer=i864, mem_type=register, size=1, zero_init=false)

i864 = fmax(0, i862);

a3547 = ALLOCATE(buffer=a3547, mem_type=register, size=1, zero_init=false)

a3547 = s3546.logical_size

i3549 = ALLOCATE(buffer=i3549, mem_type=register, size=1, zero_init=false)

i3549 = a3547[0]

i823 = ALLOCATE(buffer=i823, mem_type=register, size=1, zero_init=false)

i823 = fmin(i3549, 16);

i825 = ALLOCATE(buffer=i825, mem_type=register, size=1, zero_init=false)

i825 = fmax(0, i823);

a3551 = ALLOCATE(buffer=a3551, mem_type=register, size=1, zero_init=false)

a3551 = s3546.logical_size

i3553 = ALLOCATE(buffer=i3553, mem_type=register, size=1, zero_init=false)

i3553 = a3551[2]

i851 = ALLOCATE(buffer=i851, mem_type=register, size=1, zero_init=false)

i851 = fmin(i3553, 4096);

i853 = ALLOCATE(buffer=i853, mem_type=register, size=1, zero_init=false)

i853 = fmax(0, i851);

FOR blockIdx.x in iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}:
  IF Unswitch:
    FOR i3849 in iUS384{1}:
      FOR i3848 in iS382{1}:
        FOR threadIdx.x in ithreadIdx.x380{128}:
          T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 ) = ALLOCATE(buffer=T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 ), mem_type=register, size=1, zero_init=false)
          IF Manual true:
            T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 )
               = slice( T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], { {0, i825, 1} {0, i839, 1} {0, i853, 1} {0, i864, 1} } )
          IF Manual true:
            T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 )
               = Set( T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 ), cache_op=Streaming )
```

**Comment by wujingyue** [comment]
> Just dumping a little more info here since I took a few minutes to check this out.
> 
> The scheduled segment hitting this error looks like this:
> 
> ```
> Inputs:
>   T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], __bfloat
> Outputs:
>   T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 ), __bfloat
> 
> %kernel_math {
> s3546 = getMetaData(T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ])
> a3547 = s3546.logical_size
> i3549 = a3547[0]
> i823 = fmin(i3549, 16);
> i825 = fmax(0, i823);
> i837 = fmin(32, 32);
> i839 = fmax(0, i837);
> a3551 = s3546.logical_size
> i3553 = a3551[2]
> i851 = fmin(i3553, 4096);
> i853 = fmax(0, i851);
> a3555 = s3546.logical_size
> i3557 = a3555[3]
> i862 = fmin(i3557, 0);
> i864 = fmax(0, i862);
> T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 )
>    = slice( T6_g[ iS419{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ), 128) ), 1) ), 1) )}, iS420{1}, iS418{1}, iS416{128} ], { {0, i825, 1} {0, i839, 1} {0, i853, 1} {0, i864, 1} } )
> T21_g[ iblockIdx.x383{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS384{1}, iS382{1}, ithreadIdx.x380{128} ] ca_pos( 2 ) produce_pos( 4 )
>    = Set( T45_l[ iblockIdx.x392{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS393{1}, iS391{1}, ithreadIdx.x389{128} ] ca_pos( 4 ), cache_op=Streaming )
> }
> ```
> 
> It's a simple `set(slice(input))` kernel, but in this case the extent `( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T6) )).logical_size ))[0] ) * ( 32 * ( ( (( (( getMetaData(T6) )).logical_size ))[2] ) * ( ( (( (( getMetaData(T6) )).logical_size ))[3] ) + ( ( fmax(0, ( fmin(( (( (( getMetaData(T6) )).logical_size ))[3] ), 0) )) ) + ( -( (( (( getMetaData(T6) )).logical_size ))[3] ) ) ) ) ) ) ), 128) ), 1) ), 1)` simplifies to zero. It is zero because of the factor `T6.size[3] + max(0, min(T6.size[3], 0)) - T6.size[3]` which clearly is zero.
> 
> The relevant part of the concretized, unsegmented fusion looks like this:
> 
> ```
> T9_l[ iS148{i0}rf, iS149{32}rf, iS150{i1}rf, iS151{( ceilDiv(( ceilDiv(i2, 32) ), 3) )}rf ]                                             
>    = slice( T6_l[ iS140{i0}, iS141{32}, iS142{i1}, iS143{( ceilDiv(( ceilDiv(i2, 32) ), 3) )} ], { {0, i339, 1} {0, i353, 1} {0, i367, 1
> } {0, i381, 1} } )
> ```
> 
> At first I thought this might be an empty tensor bug, but it doesn't look like T6 or T9 (hence T45) are empty. It could be a bug in slice extent expressions (see #460), but at first glance those seem fine in the concretized fusion.

Thanks for the help! The reproducer script indeed defines two empty tensors via `fd.ops.slice`: https://github.com/NVIDIA/Fuser/blob/wjy/recurse/repro.py#L47-L48. That may have triggered the bug...

**Comment by jacobhinkle** [comment]
> Thanks for the help! The reproducer script indeed defines two empty tensors via `fd.ops.slice`: https://github.com/NVIDIA/Fuser/blob/wjy/recurse/repro.py#L47-L48. That may have triggered the bug... 

Ah, then this probably should have been caught be empty tensor concretization after all. Will investigate today...

**Comment by jacobhinkle** [comment]
I think this is actually a concretization bug after all. The empty tensor extents _are_ being recognized during concretization, but they are not winding up concretized as constant zero, but instead have some non-constant expressions. That means they don't get caught in `RemoveEmptyPass`, leading to this bug. We could potentially try and find contradictions inside `assume(Val*)` in order to give an informative error and avoid infinite recursion in cases like these, but I think this particular bug is in concretization.
