### ISSUE TITLE
Accuracy mismatch with scalar division

### ISSUE THREAD

**Issue by IvanYashchuk** [NVIDIA/Fuser#160]
In the example code nvFuser produces a result with one element incorrect on 3080ti
```py
from nvfuser import FusionDefinition, DataType
import torch
torch.manual_seed(1)

def nvfuser_fusion(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, 1], contiguous=[True, True, True, None], dtype=DataType.BFloat16, is_cpu=False)
    T3 = fd.ops.cast(T0, dtype=DataType.Float)
    T4 = fd.ops.sum(T3, axes=[1, 3], keepdim=False, dtype=DataType.Null)
    S5 = fd.define_constant(7.00000, dtype=DataType.Double)
    T6 = fd.ops.div(T4, S5)
    T7 = fd.ops.cast(T6, dtype=DataType.BFloat16)
    fd.add_output(T7)

def mean_reference(a, dim):
    a_f32 = a.to(torch.float32)
    a_sum = a_f32.sum(dim)
    reduced_elements = 7.0
    return (a_sum / reduced_elements).to(a.dtype)

a = torch.randn(8, 7, 5, 1, dtype=torch.bfloat16, device="cuda")

with FusionDefinition() as fd:
    nvfuser_fusion(fd)

nv_out = fd.execute([a])[0]
ref_out = mean_reference(a, [1, 3])
torch.testing.assert_close(nv_out, ref_out, atol=1e-3, rtol=0.0)
```
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 1 / 40 (2.5%)
Greatest absolute difference: 0.00390625 at index (2, 3) (up to 0.001 allowed)
Greatest relative difference: 0.0052490234375 at index (2, 3) (up to 0.0 allowed)
```

Changing `T6 = fd.ops.div(T4, S5)` to `T6 = fd.ops.mul(T4, fd.ops.reciprocal(S5))` fixes the problem.

The same problem is with `var_mean`:
```py
from nvfuser import FusionDefinition, DataType
import torch
torch.manual_seed(1)

a = torch.randn(8, 7, 5, 1, dtype=torch.bfloat16, device="cuda")

def mean_reference(a, dim):
    a_f32 = a.to(torch.float32)
    a_sum = a_f32.sum(dim)
    reduced_elements = 7.0
    return (a_sum / reduced_elements).to(a.dtype)

ref_out = mean_reference(a, [1, 3])

def nvfuser_fusion_var_mean(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(symbolic_sizes=[-1, -1, -1, 1], contiguous=[True, True, True, None], dtype=DataType.BFloat16, is_cpu=False)
    T3 = fd.ops.cast(T0, dtype=DataType.Float)
    _, mean = fd.ops.var_mean(T3, axes=[1, 3], keepdim=False, correction=0)
    mean = fd.ops.cast(mean, dtype=DataType.BFloat16)
    fd.add_output(mean)

with FusionDefinition() as fd:
    nvfuser_fusion_var_mean(fd)

# This also fails
nv_out = fd.execute([a])[0]
torch.testing.assert_close(nv_out, ref_out, atol=1e-3, rtol=0.0)
```

**Comment by naoyam** [comment]
Looks like with `T6 = fd.ops.mul(T4, fd.ops.reciprocal(S5))`, the reciprocal part is computed in double precision, whereas `fd.ops.div(T4, S5)` is just an fp32 division.

Can you compute the reference in double precision?

**Comment by IvanYashchuk** [comment]
Using `S5 = fd.define_constant(7.00000, dtype=DataType.Float)` (float instead of double) doesn't change anything.

**Comment by IvanYashchuk** [comment]
Using reference in double precision for comparison shows no mismatches.
```py
def mean_reference(a, dim):
    a_f64 = a.to(torch.float64)
    a_sum = a_f64.sum(dim)
    reduced_elements = 7.0
    return (a_sum / reduced_elements).to(a.dtype)
```

**Comment by naoyam** [comment]
Thanks for the check.

Which precision is used in `a_sum / reduced_elements` in the expression below? I assume `reduced_elements` is double precision, so is the division also double precision?

```
def mean_reference(a, dim):
    a_f32 = a.to(torch.float32)
    a_sum = a_f32.sum(dim)
    reduced_elements = 7.0
    return (a_sum / reduced_elements).to(a.dtype)
```

**Comment by naoyam** [comment]
Does PyTorch happen to use the fast math option or even directly use some of the math approximating intrinsics (https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__INTRINSIC__SINGLE.html)? I don't think nvFuser is using any of such intrinsics. There are intrinsics for division and reciprocal among others.

If not, I think this is all just due to the rounding error by the sum reduction. It may just be that `mul + reciprocal` happened to mask some of the large errors compared to just a division.

**Comment by IvanYashchuk** [comment]
I'm not sure but PyTorch may use these intrinsics.

Computing the reference on the CPU matches the nvFuser result exactly. So it's not an nvFuser's problem. Thank you for taking a look at this! I will close the issue now.
