### ISSUE TITLE
`Cannot find scheduler` in `layernorm + dropout + add` benchmarks

### ISSUE THREAD

**Issue by Priya2698** [NVIDIA/Fuser#1607]
The following error occurs for several input sizes in PR #1606.

Repro:
```
ERROR    nvfuser:__init__.py:196 An error occurred while executing nvFuser FusionDefinition 0.
If you believe this is a bug or need assistance, please file an issue at https://github.com/NVIDIA/Fuser/issues/new
Here's a script to reproduce the error:


import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Bool, is_cpu=False)
    T1 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
    T2 = fd.define_tensor(shape=[-1, 1], contiguity=[True, None], dtype=DataType.Float, is_cpu=False)
    T3 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False)
    T4 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.Float, is_cpu=False)
    T5 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.Float, is_cpu=False)
    T6 = fd.ops.mul(T5, T0)
    S7 = fd.define_scalar(1.11111, dtype=DataType.Double)
    T8 = fd.ops.mul(T6, S7)
    T9 = fd.ops.add(T5, T8)
    S10 = fd.ops.size(T5, dim=0)
    S11 = fd.define_scalar(1, dtype=DataType.Int)
    V12 = fd.define_vector([S10, S11], dtype=DataType.Int)
    T13 = fd.ops.broadcast_in_dim(T1, shape=V12, broadcast_dims=[0])
    V14 = fd.ops.shape(T5)
    T15 = fd.ops.broadcast_in_dim(T13, shape=V14, broadcast_dims=[0, 1])
    T16 = fd.ops.sub(T9, T15)
    T17 = fd.ops.broadcast_in_dim(T2, shape=V14, broadcast_dims=[0, 1])
    T18 = fd.ops.mul(T16, T17)
    T19 = fd.ops.broadcast_in_dim(T4, shape=V14, broadcast_dims=[1])
    T20 = fd.ops.sum(T3, axes=[0], keepdim=False, dtype=DataType.Null)
    T21 = fd.ops.mul(T3, T19)
    T22 = fd.ops.mul(T3, T18)
    T23 = fd.ops.sum(T22, axes=[0], keepdim=False, dtype=DataType.Null)
    T24 = fd.ops.mul(T21, T17)
    T25 = fd.ops.mul(T21, T16)
    T26 = fd.ops.sum(T25, axes=[1], keepdim=False, dtype=DataType.Null)
    T27 = fd.ops.broadcast_in_dim(T26, shape=V12, broadcast_dims=[0])
    T28 = fd.ops.neg(T24)
    T29 = fd.ops.sum(T28, axes=[1], keepdim=False, dtype=DataType.Null)
    T30 = fd.ops.broadcast_in_dim(T29, shape=V12, broadcast_dims=[0])
    S31 = fd.define_scalar(-0.500000, dtype=DataType.Double)
    T32 = fd.ops.mul(S31, T27)
    S33 = fd.define_scalar(3.00000, dtype=DataType.Double)
    T34 = fd.ops.pow(T2, S33)
    T35 = fd.ops.mul(T32, T34)
    T36 = fd.ops.sum(T30, axes=[1], keepdim=False, dtype=DataType.Null)
    T37 = fd.ops.sum(T35, axes=[1], keepdim=False, dtype=DataType.Null)
    T38 = fd.ops.broadcast_in_dim(T37, shape=V12, broadcast_dims=[0])
    T39 = fd.ops.broadcast_in_dim(T38, shape=V14, broadcast_dims=[0, 1])
    T40 = fd.ops.broadcast_in_dim(T1, shape=V12, broadcast_dims=[0])
    T41 = fd.ops.broadcast_in_dim(T40, shape=V14, broadcast_dims=[0, 1])
    S42 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T43 = fd.ops.mul(S42, T39)
    T44 = fd.ops.sub(T9, T41)
    T45 = fd.ops.mul(T43, T44)
    S46 = fd.ops.size(T5, dim=1)
    S47 = fd.ops.reciprocal(S46)
    T48 = fd.ops.mul(T45, S47)
    T49 = fd.ops.broadcast_in_dim(T36, shape=V12, broadcast_dims=[0])
    T50 = fd.ops.broadcast_in_dim(T49, shape=V14, broadcast_dims=[0, 1])
    T51 = fd.ops.mul(S47, T50)
    T52 = fd.ops.add(T48, T51)
    T53 = fd.ops.add(T24, T52)
    T54 = fd.ops.mul(T53, S7)
    T55 = fd.ops.mul(T54, T0)
    T56 = fd.ops.add(T53, T55)
    fd.add_output(T56)
    fd.add_output(T23)
    fd.add_output(T20)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randint(0, 2, (249856,), dtype=torch.bool, device='cuda:0').as_strided((16, 15616), (15616, 1)),
    torch.randn((16,), dtype=torch.float32, device='cuda:0').as_strided((16,), (1,)),
    torch.randn((16,), dtype=torch.float32, device='cuda:0').as_strided((16, 1), (1, 1)),
    torch.randn((249856,), dtype=torch.float32, device='cuda:0').as_strided((16, 15616), (15616, 1)),
    torch.randn((15616,), dtype=torch.float32, device='cuda:0').as_strided((15616,), (1,)),
    torch.randn((249856,), dtype=torch.float32, device='cuda:0').as_strided((16, 15616), (15616, 1)),
]
fd.execute(inputs)

Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 137, in execute
    result = self._execute(
RuntimeError: h.has_value() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp":3556, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Can not find a scheduler to schedule fusion segment
Exception raised from deriveHeuristic at /opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp:3556 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fed177d6a0d in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7fed179275f3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::SegmentCandidateFinder::deriveHeuristic(nvfuser::SegmentedGroup*) + 0xd0 (0x7fed17d00540 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::SegmentCandidateFinder::finalize() + 0x7a2 (0x7fed17d06b32 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::SegmentCandidateFinder::findSegments() + 0x581 (0x7fed17d123d1 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: nvfuser::SegmentCandidateFinder::SegmentCandidateFinder(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SegmentCandidateFinderOptions) + 0x3b4 (0x7fed17d12b24 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #6: nvfuser::SegmentCandidateFinder::segment(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SegmentCandidateFinderOptions) + 0x6d (0x7fed1799312d in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #7: nvfuser::SegmentCandidateFinder::segment(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::SchedulerRuntimeInfo&) + 0x6a (0x7fed17d12c3a in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #8: nvfuser::FusionKernelRuntime::FusionKernelRuntime(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const&, nvfuser::serde::FusionKernelRuntime const*, std::optional<nvfuser::PrimDataType>, long, long, long) + 0xf59 (0x7fed17a94269 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #9: nvfuser::FusionExecutorCache::getKernelRuntimeFor(nvfuser::KernelArgumentHolder const&, std::optional<nvfuser::PrimDataType>) + 0x9b9 (0x7fed17a977b9 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #10: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x1ea (0x7fed17a984da in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #11: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x16c (0x7fed17da675c in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)

```

**Comment by jacobhinkle** [comment]
@liqiangxl is this related to persistent scheduler?
```
Scheduler _no_op_ ***rejected*** because : reduction of non-zero elements is not supported
Scheduler _reduction_ ***rejected*** because : Un-mapped multi-reduction: T23_g[ rS44{i7}, iS45{i8} ] T26_g[ iS50{i7}, rS51{i8} ]
Scheduler _transpose_ ***rejected*** because : no support for reduction ops
Scheduler _pointwise_ ***rejected*** because : no support for reduction ops
Scheduler _inner_persistent_ ***rejected*** because : schedule_heuristic doesn't match with reduction type.
Scheduler _outer_persistent_ ***rejected*** because : schedule_heuristic doesn't match with reduction type.
Scheduler _inner_outer_persistent_ ***rejected*** because : not enough registers or shared memory for persistence. Needed 265472 bytes but only 262144 bytes are available.
Scheduler _matmul_ ***rejected*** because : Matmul scheduler supports fusions only with a single MMA op, got: 0
```

**Comment by liqiangxl** [comment]
Probabally, based on the name of the model, it should be processed by inner persistent, let me take a look.

**Comment by liqiangxl** [comment]
**Reason:**
The error comes from the fusion segmenter. 
In `SegmentCandidateFinder::findSegments()`, there are 3 non-empty groups after After `finalMerge()`:
(1)
```
T6_g[ iS10{i0}, iS11{i1} ]
  = (float)(T0_g[ iS0{i0}, iS1{i1} ]);
```

(2)
```
T58_g[ iS112{i0}, iS113{i1} ]
  = (float)(T0_g[ iS0{i0}, iS1{i1} ]);
```
 
(3)
```
T20_g[ rS38{i7}, iS39{i8} ]
  = reduction( T3_g[ iS5{i7}, iS6{i8} ], op = add, initial value = float(0), allreduce = false )
T7_l[ iS12{i10}, iS13{i11} ]
  = T5_g[ iS8{i10}, iS9{i11} ]
  * T6_g[ iS10{i0}, iS11{i1} ];
…
T59_g[ iS114{i7}, iS115{i8} ]
  = T57_g[ iS110{i7}, iS111{i8} ]
  * T58_g[ iS112{i0}, iS113{i1} ];
T60_g[ iS116{i7}, iS117{i8} ]
  = T56_g[ iS108{i7}, iS109{i8} ]
  + T59_g[ iS114{i7}, iS115{i8} ];
```
Then groups (1) and (2) becomes empty after `cleanupForwardedInputs();`

Then in `resolveInputsInGroup`, `T6_g` and `T58_g` are recomputed from `T0_g`. This recompute makes `T0_g` a persistent tensor, however, the buffer size is not being rechecked before making this change and finally lead to a fusion that can't be scheduled by the inner_outer_persistent scheduler.

Proposed Fix:
The direct cause is adding forwarded inputs to the segmented fusion group without checking the potential increase of persistent buffer size. This can only happen when the forwarded input tensor has more than one consumer. So we can skip input forward if an input has more than one consumer.

**Comment by naoyam** [comment]
> **Reason:** The error comes from the fusion segmenter. In `SegmentCandidateFinder::findSegments()`, there are 3 non-empty groups after After `finalMerge()`: (1)
> 
> ```
> T6_g[ iS10{i0}, iS11{i1} ]
>   = (float)(T0_g[ iS0{i0}, iS1{i1} ]);
> ```
> 
> (2)
> 
> ```
> T58_g[ iS112{i0}, iS113{i1} ]
>   = (float)(T0_g[ iS0{i0}, iS1{i1} ]);
> ```
> 
> (3)
> 
> ```
> T20_g[ rS38{i7}, iS39{i8} ]
>   = reduction( T3_g[ iS5{i7}, iS6{i8} ], op = add, initial value = float(0), allreduce = false )
> T7_l[ iS12{i10}, iS13{i11} ]
>   = T5_g[ iS8{i10}, iS9{i11} ]
>   * T6_g[ iS10{i0}, iS11{i1} ];
> …
> T59_g[ iS114{i7}, iS115{i8} ]
>   = T57_g[ iS110{i7}, iS111{i8} ]
>   * T58_g[ iS112{i0}, iS113{i1} ];
> T60_g[ iS116{i7}, iS117{i8} ]
>   = T56_g[ iS108{i7}, iS109{i8} ]
>   + T59_g[ iS114{i7}, iS115{i8} ];
> ```

I wonder why we make the first two segments. Why can't they be merged to the last one? Assuming the last one is scheduled as a persistent segment, why merging the first 2 segments would increase the buffer size? Is the type of `T0` `bool`?

**Comment by liqiangxl** [comment]
> > **Reason:** The error comes from the fusion segmenter. In `SegmentCandidateFinder::findSegments()`, there are 3 non-empty groups after After `finalMerge()`: (1)
> > ```
> > T6_g[ iS10{i0}, iS11{i1} ]
> >   = (float)(T0_g[ iS0{i0}, iS1{i1} ]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (2)
> > ```
> > T58_g[ iS112{i0}, iS113{i1} ]
> >   = (float)(T0_g[ iS0{i0}, iS1{i1} ]);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (3)
> > ```
> > T20_g[ rS38{i7}, iS39{i8} ]
> >   = reduction( T3_g[ iS5{i7}, iS6{i8} ], op = add, initial value = float(0), allreduce = false )
> > T7_l[ iS12{i10}, iS13{i11} ]
> >   = T5_g[ iS8{i10}, iS9{i11} ]
> >   * T6_g[ iS10{i0}, iS11{i1} ];
> > …
> > T59_g[ iS114{i7}, iS115{i8} ]
> >   = T57_g[ iS110{i7}, iS111{i8} ]
> >   * T58_g[ iS112{i0}, iS113{i1} ];
> > T60_g[ iS116{i7}, iS117{i8} ]
> >   = T56_g[ iS108{i7}, iS109{i8} ]
> >   + T59_g[ iS114{i7}, iS115{i8} ];
> > ```
> 
> I wonder why we make the first two segments. Why can't they be merged to the last one? Assuming the last one is scheduled as a persistent segment, why merging the first 2 segments would increase the buffer size? Is the type of `T0` `bool`?

If merged, T0 becomes a persistent buffer.

**Comment by naoyam** [comment]
> If merged, T0 becomes a persistent buffer.

Can you give more details why it's a problem? This segmentation seems quite suboptimal as it would generate two kernels just doing a single copy.

**Comment by liqiangxl** [comment]
> > If merged, T0 becomes a persistent buffer.
> 
> Can you give more details why it's a problem? This segmentation seems quite suboptimal as it would generate two kernels just doing a single copy.

The first 2 segments are special, they are actually `excluded_inp_unary_exprs_`:
```
  // Expressions to exclude from segmentation because they're just derived from
  // unary ops on inputs to the complete fusion
  VectorOfUniqueEntries<Expr*> excluded_inp_unary_exprs_;
```


Here is what happens:
(1) `T6_g[ iS10{i0}, iS11{i1} ] = (float)(T0_g[ iS0{i0}, iS1{i1} ]);` and `T58_g[ iS112{i0}, iS113{i1} ]  = (float)(T0_g[ iS0{i0}, iS1{i1} ]);` are `expresions that are simply unary ops from inputs`. For these exprs, we have special treatment in `void forwardInputs();`, see function comments:
```
  //! Find all expresions that are simply unary ops from
  //! inputs. Don't segment
  //! these as they're easy targets for recomputation. Only go until the first
  //! expression that has multiple uses.
  //!
  //! The ending tensors, or the forwarded tensors, are considered
  //! fusion inputs for the sake of segmentation, and the expressions
  //! between the real inputs and the forwarded tensors are excluded
  //! from the segmentation steps until the finalization, at which
  //! point they are simply prepended to each final segment using the
  //! forwarded inputs.
  void forwardInputs();
```
So, here `T6` and `T58` are ending tensors and are considered as fusion inputs.

(2) `T6` and `T58` are recomputed from the actual input (`T0` in this case) at the finalization stage. However, the segmenter didn't check the influence on persistent buffer sizes. In this case, `T0_g` is used by both `T6_g` and `T58_g` and it should be persistent in the updated segment. It then leads to larger buffer size than available registers.

(3) After apply the proposed fix, expresions  to calculate `T6` and `T58` are no longer being excluded from the segmentation steps. The generated fusions are: pointwise, inner reduction, and outer reduction, which is resonable.

**Comment by naoyam** [comment]
> > > If merged, T0 becomes a persistent buffer.
> > 
> > 
> > Can you give more details why it's a problem? This segmentation seems quite suboptimal as it would generate two kernels just doing a single copy.
> 
> The first 2 segments are special, they are actually `excluded_inp_unary_exprs_`:
> 
> ```
>   // Expressions to exclude from segmentation because they're just derived from
>   // unary ops on inputs to the complete fusion
>   VectorOfUniqueEntries<Expr*> excluded_inp_unary_exprs_;
> ```
> 
> Here is what happens: (1) `T6_g[ iS10{i0}, iS11{i1} ] = (float)(T0_g[ iS0{i0}, iS1{i1} ]);` and `T58_g[ iS112{i0}, iS113{i1} ] = (float)(T0_g[ iS0{i0}, iS1{i1} ]);` are `expresions that are simply unary ops from inputs`. For these exprs, we have special treatment in `void forwardInputs();`, see function comments:
> 
> ```
>   //! Find all expresions that are simply unary ops from
>   //! inputs. Don't segment
>   //! these as they're easy targets for recomputation. Only go until the first
>   //! expression that has multiple uses.
>   //!
>   //! The ending tensors, or the forwarded tensors, are considered
>   //! fusion inputs for the sake of segmentation, and the expressions
>   //! between the real inputs and the forwarded tensors are excluded
>   //! from the segmentation steps until the finalization, at which
>   //! point they are simply prepended to each final segment using the
>   //! forwarded inputs.
>   void forwardInputs();
> ```
> 
> So, here `T6` and `T58` are ending tensors and are considered as fusion inputs.
> 
> (2) `T6` and `T58` are recomputed from the actual input (`T0` in this case) at the finalization stage. However, the segmenter didn't check the influence on persistent buffer sizes. In this case, `T0_g` is used by both `T6_g` and `T58_g` and it should be persistent in the updated segment. It then leads to larger buffer size than available registers.
> 
> (3) After apply the proposed fix, expresions to calculate `T6` and `T58` are no longer being excluded from the segmentation steps. The generated fusions are: pointwise, inner reduction, and outer reduction, which is resonable.

Which scheduler was used for the main segment?

```
(3)

T20_g[ rS38{i7}, iS39{i8} ]
  = reduction( T3_g[ iS5{i7}, iS6{i8} ], op = add, initial value = float(0), allreduce = false )
T7_l[ iS12{i10}, iS13{i11} ]
  = T5_g[ iS8{i10}, iS9{i11} ]
  * T6_g[ iS10{i0}, iS11{i1} ];
…
T59_g[ iS114{i7}, iS115{i8} ]
  = T57_g[ iS110{i7}, iS111{i8} ]
  * T58_g[ iS112{i0}, iS113{i1} ];
T60_g[ iS116{i7}, iS117{i8} ]
  = T56_g[ iS108{i7}, iS109{i8} ]
  + T59_g[ iS114{i7}, iS115{i8} ];
```

**Comment by liqiangxl** [comment]
> 
> Which scheduler was used for the main segment?
> 
> ```
> (3)
> 
> T20_g[ rS38{i7}, iS39{i8} ]
>   = reduction( T3_g[ iS5{i7}, iS6{i8} ], op = add, initial value = float(0), allreduce = false )
> T7_l[ iS12{i10}, iS13{i11} ]
>   = T5_g[ iS8{i10}, iS9{i11} ]
>   * T6_g[ iS10{i0}, iS11{i1} ];
> …
> T59_g[ iS114{i7}, iS115{i8} ]
>   = T57_g[ iS110{i7}, iS111{i8} ]
>   * T58_g[ iS112{i0}, iS113{i1} ];
> T60_g[ iS116{i7}, iS117{i8} ]
>   = T56_g[ iS108{i7}, iS109{i8} ]
>   + T59_g[ iS114{i7}, iS115{i8} ];
> ```

inner_outer_persistent

**Comment by naoyam** [comment]
@Priya2698 @liqiangxl Is this issue fixed? If so please close
