### ISSUE TITLE
Extra S->S copy introduced by tmaLoad->broadcast->mma. 

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#1628]
When we define matmul, we have inputs of shape `[M, K]` and `[K, N]`, and we broadcast it to `[M, K, 1]` and `[1, K, N]`, then we do a `mul` and `sum` to obtain the matmul result. From `[M, K]` to `[M, K, 1]`, there must be a `BroadcastOp`. Unfortunately, this does not work with Hopper, because for fast Hopper matmul kernel, we must use TMA for global -> shared memory loading and use MMA instructions to directly pull data from shared mem. If we are unable to fuse the `global -> shared` with broadcasting op, we will end up having a kernel like:
```C++
T1_s = tmaLoad(T0_g);
T2_s = broadcast(T1_s);
... = mma(T2_s, ...);
```
That is, we need to double the smem usage to store the same data twice (`T1 ` and `T2`), one for TMA consumer, another for MMA producer, and do a S->S copy between these two memory.

I am still learning but according to my current understanding, the smem data written by TMA is supposed to be used by MMA directly, so this extra S->S copy introduced by the `BroadcastOp` does not make sense.

What I am proposing is to go through the same process as I did in the past for `TransposeOp`: In the past, transposes must be done in a `TransposeOp`, but after my change, any op can have a fused transpose by specifying the order in its rFactor domain. Most commonly, the op having a fused transpose is a `LoadStoreOp`, but it is not required to be so.

I want broadcasting (and to be consistent, squeeze as well) to follow the same contract: There will no longer be a `BroadcastOp` or `SqueezeOp`, instead, broadcasting `IterDomain`s is allowed to be created or annihilated at any `TensorView`. (The term "created" and "annihilated" is borrowed from particle physics, because I am feeling that broadcasting `IterDomain` is like a Boson, it can be created from nowhere, and it can just disappear as it wants). For example, if we want to do a broadcast, we can define:
```C++
T1 = LoadStoreOp(T0)

T0: root domain [I1, I2]
T1: root domain [I3, I4]
    rFactor domain [I3, b5, I4]
```
we can also do fused squeeze-broadcast
```C++
T1 = LoadStoreOp(T0)

T0: root domain [I1, b3, I2]
T1: root domain [I4, b5, I6]
    rFactor domain [I4, b7, I6]
// squeeze b5, broadcast b7
```

The main use case I want to support is `LoadStoreOp` with fused broadcasting or squeeze, but I do not see any reason why `LoadStoreOp` is special, so my expectation is, when this work is done, an arbitrary tensor op can have fused  broadcasting or squeeze.

Calling for review: @naoyam @jacobhinkle @wujingyue @protonu @drzejan2

**Comment by naoyam** [comment]
QQ:

> ```c++
> T1_s = tmaLoad(T0_g);
> T2_s = broadcast(T1_s);
> ... = mma(T2_s, ...);
> ```
> 
> That is, we need to double the smem usage to store the same data twice (`T1 ` and `T2`), one for TMA consumer, another for MMA producer, and do a S->S copy between these two memory.

Doesn't the alias analysis allow reusing the same buffer? (CC: @jacobhinkle )

**Comment by zasdfgbnm** [comment]
> In theory it could. Currently though, broadcasts prevent inner aliasing like this since they can alter indexing in ways that make it difficult to guarantee the alias is safe. We could try updating that logic though.

Besides, that, for this program, the last read of `T1_s` is line 2 (`T2_s = broadcast(T1_s);`), the first write of `T2_s` is also this line. IIRC, `[first write, last read]` is considered a closed interval, so the life of `T1_s` and `T2_s` has overlap and can not be reused.

**Comment by zasdfgbnm** [comment]
> Doesn't the alias analysis allow reusing the same buffer? (CC: @jacobhinkle )

Even if it does, I would still prefer not to rely on alias analysis. One reason is, compared with not creating two buffers in the first place, this can be fragile. Second reason is, both `T1_s` and `T2_s` needs to have swizzle in it, and the propagation of swizzle can be tricky (1. currently, transform propagator does not propagate swizzle. 2. we just want to propagate swizzle from `T2_s` to `T1_s`, but not further to `T0_g`, this is doable but not convenient)

**Comment by wujingyue** [comment]
To avoid https://xyproblem.info/, I think the real problem here is that no IR today represents a `ldmatrix` with an implicit broadcast. 

**One** solution to that is to overload `LoadStoreOp` to support implicit broadcasting, which is part of @zasdfgbnm 's suggestion. In fact, `LoadStoreOp` has already been overloaded to represent semantics at different levels, from identity in math, to transferring data between address spaces, to transferring data between different layouts. #1343 is a similar example showing that `LoadStoreOp` was made to support a non-trivial rfactor domain so it can represent `ldmatrix.trans`. 

Another common solution is to introduce a separate op for `ldmatrix`. We haven't seemed to discuss that yet -- what do you all think? 

That being said, killing `BroadcastOp` is an orthogonal heavy lifting for arguable wins, so I wouldn't do it from the practical perspective. There's merit to keeping high-level op semantics simple, separate and composable. It makes analysis and optimization easier. For example, `AliasFinder` today is able to separately handle `LoadStoreOp`, `BroadcastOp`, and `SqueezeOp`. (IMHO, it would be even cleaner if we hadn't removed `TransposeOp`.) To help clarify the contract between `BroadcastOp` and `LoadStoreOp`, we could restrict `BroadcastOp` to only be used in certain stages, e.g., before device lowering.

**Comment by zasdfgbnm** [comment]
> I think the real problem here is that no IR today represents a `ldmatrix` with an implicit broadcast.

Almost correct, except that is is not a `ldmatrix` but a `cp.async.bulk.tensor`.

> Another common solution is to introduce a separate op for `ldmatrix`. We haven't seemed to discuss that yet -- what do you all think?

As I just mentioned, what I wanted was for `cp.async.bulk.tensor`, not for `ldmatrix.trans`. So let me split this question into two questions:
1. What if we have not killed `TransposeOp`, but instead, we created a separate `LdMatrixOp`, what benefit will we get and what trouble will we have?
2. How about `cp.async.bulk.tensor`? Does the reasoning of `ldmatrix` applies to `cp.async.bulk.tensor`?

For 1, AFAICT, the benefit we will get is:
- `LoadStoreOp` will be stupid and simple: it is just a very trivial op that will not change the semantics of anything.
  - This will make some analysis simpler, because it would be just a `if (expr->isA<LoadStoreOp>()) { return false; }`, instead of having to go through the IterDomains and check if there are transposes.
  - But be warned that we still can not assume `LoadStoreOp` is a no-op, because the allocation domain of the producer and consumer might be different. `LoadStoreOp` means "no semantic permutation", but not "no physical permutation".

But the thing that will lose is:
- We will be unable to vectorize transposes. For example, if I have `T1_s = transpose(T0_l)`, I won't be able to vectorize the write to smem.
- Needs special handling `TransposeOp` and `LdMatrixOp` in `PairwiseRootDomainMap`
- We will be unable to use `cacheBefore` or `cacheAfter` for smem->register loading in the matmul scheduler.
- **Without allowing a fused transpose in `MmaOp`, we can not support `NN` format of matmul, because the output of matmul will be [N, M] instead of [M, N]**

In general, at least at the time when I did that change, killing `TransposeOp` is a net reduction of the overall complexity of the system. As we can see in https://github.com/NVIDIA/Fuser/pull/148, 200+ lines of code is removed.

For 2, I am still typing, will post in the next reply.

**Comment by zasdfgbnm** [comment]
(continue my reasoning for 2)

Regarding `cp.async.bulk.tensor`, unlike `ldmatrix`, which is a very specific op that does a very specific thing and is only useful to matmul kernels, `cp.async.bulk.tensor` is much wider and will be widely used for all kernels (however, the need for fusing a broadcast is limited to matmul). For most of the time, `cp.async.bulk.tensor` will be used for its non-broadcasting case. From this perspective, `cp.async.bulk.tensor` is mostly just a `LoadStoreOp`.

Another side benefit of making `LoadStoreOp` capable of having a fused broadcast is, I can make `ldmatrix` have a fused broadcast as well. This way, I can avoid a line of code like `T2[i1] = T1[i1]` generated from broadcast. This improves code readability, because when a human writes code, they will not write something like that.

===================

From a higher level perspective, another reason why I want to make a broadcasting IterDomain capable of being created or annihilated arbitrarily is because I don't care when a broadcasting IterDomain start to exist. What is interesting to me is when it is resolved (i.e. a broadcasting ID is added to a concrete ID and becomes concrete). So in general, I believe we should focus our attention on broadcasting concretization, not the appearance of a new broadcasting IterDomain. Making this move de-emphasize the appearance of a broadcasting IterDomain.

**Comment by naoyam** [comment]
Asked Xiang to schedule a meeting, but first of all I'd emphasize Jingyue's comment:

> There's merit to keeping high-level op semantics simple, separate and composable. It makes analysis and optimization easier.

Technically, it is possible to mix many of IterDomain ops with TensorView ops. For example, we could mix `Resize` with normal pointwise ops. However, in principle, I believe we should keep each op as simple as possible without overloading too many capabilities.

So, in principle, I'd keep `BroadcastOp` as is and oppose to let `LoadStoreOp` to take it over. However, I'd need to understand if that's really the only way to work around the problems.

One immediate concern on removing `BroadcastOp` is, if we do so, we would lose track of mappings between broadcast domains over producer-consumer tensors. Per Xiang:

> So in general, I believe we should focus our attention on broadcasting concretization, not the appearance of a new broadcasting IterDomain. Making this move de-emphasize the appearance of a broadcasting IterDomain.

It is true that the concretization is important information but we also track which domains are eventually concretized. I'm not sure if this information is not necessary. I need to think about it more.

**Comment by wujingyue** [comment]
> All the above points are solvable, but the solution is mostly like replicating whatever already exist for LoadStoreOp and applying it to TransposeOp and LdMatrixOp

Get it -- that's a fair and practical point. Given `cp.async.bulk` and `ldmatrix` are already implemented as `LoadStoreOp`'s subtypes, extending it to support implicit broadcasting seems to have higher ROI than creating a separate op.

**Comment by zasdfgbnm** [comment]
Just an update about our recent offline discussion: 

We decided to make `MatmulScheduler::canScheduleCompileTime` reject the `BroadcastOp` and take the mma, so that the fusion inputs will become 3D (for example `[M, 1, K]` and `[1, K, N]`). This way, there won't be the problem as described here. This approach also helps with https://github.com/NVIDIA/Fuser/issues/1707

![image](https://github.com/NVIDIA/Fuser/assets/1032377/32b2339c-618e-42ef-98ce-6b2be39f4630)

**Comment by wujingyue** [comment]
Great! Just to be more precise, I changed the title to reflect the problem not an outdated proposal.

**Comment by zasdfgbnm** [comment]
> Great! Just to be more precise, I changed the title to reflect the problem not an outdated proposal.

Thank you for updating the title!

===

This issue is not resolved. Reopen it now.
