### ISSUE TITLE
`fd.ops.uniform` generates 1 in output

### ISSUE THREAD

**Issue by Priya2698** [NVIDIA/Fuser#1653]
Repro script:

```
from nvfuser import FusionDefinition, DataType
import torch

def fusion_fn(fd: FusionDefinition):
    shape = fd.define_vector([16, 1024], dtype=DataType.Int)
    S0 = fd.define_scalar(0.00000, dtype=DataType.Double)
    S1 = fd.define_scalar(1.00000, dtype=DataType.Double)
    output = fd.ops.uniform(S0, S1, shape=shape, dtype=DataType.BFloat16)
    fd.add_output(output)

with FusionDefinition() as fd:
    fusion_fn(fd)
output = fd.execute([])[0]
assert torch.max(output) < 1.0, f'Min: {torch.min(output)} Max: {torch.max(output)}'
```
Error: `AssertionError: Min: 0.0001888275146484375 Max: 1.0`

**Comment by jacobhinkle** [comment]
```
Inputs:                                                             
Outputs:                                                                                                                                 
  T0_g[ iS0{16}, iS1{1024} ], __bfloat                                                                                                   
                                                                                                                                         
%kernel_math {                                                                                                                           
T0_g[ iS0{16}, iS1{1024} ]                                          
   = rng_uniform_range({16, 1024}, double(0), double(1), __bfloat);
}
```
It is indeed using uniform_range even though this is a standard uniform.
```c++
      nvfuser_index_t linear_index128 = (i6 + (i8 + nvfuser_zero));                                                                      
      nvfuser_index_t rng_subseq128 = linear_index128 / 4;                                                                               
      nvfuser_index_t rng_component128 = linear_index128 % 4;                                                                            
      nvfuser_index_t rng_offset128 = (((ptr2 == nullptr) ? i3 : ((*ptr2) + i3)) / 4LL);                                                 
      if (rng_subseq != rng_subseq128 || rng_offset != rng_offset128) {                                                                  
        rng_result = philox(((ptr0 == nullptr) ? i1 : (*ptr0)), rng_subseq128, rng_offset128);                                           
        rng_subseq = rng_subseq128;                                                                                                      
        rng_offset = rng_offset128;                                                                                                            }                                                                                                                                  
      T1[i8] = rng_uniform_range(rng_result, rng_component128, 0.00000000000000000e+00, 1.00000000000000000e+00);  
```
For efficiency and accuracy's sake, we should probably translate this to call `rng_uniform(rng_result, rng_component128)` instead. `rng_uniform_range` is the following:
```c++
__device__ double uniform(unsigned int x, unsigned int y) {
  constexpr double kRan2Pow53Inv = 1.1102230246251565e-16;
  const unsigned long long z =
      (unsigned long long)x ^ ((unsigned long long)y << (53 - 32));
  double result = z * kRan2Pow53Inv + (kRan2Pow53Inv / 2.0);
  return result == 1 ? 0.0 : result;
}

__device__ double rng_uniform(const uint4& rng_result, int rng_component) {
  return uniform(
      (&rng_result.x)[rng_component * 2],
      (&rng_result.x)[rng_component * 2 + 1]);
}

__device__ double rng_uniform_range(
    const uint4& rng_result,
    int rng_component,
    double from,
    double to) {
  auto range = to - from;
  auto uniform01 = rng_uniform(rng_result, rng_component);
  return from + range * uniform01;
}
```
This should be computing `range = 1.0 - 0.0 = 1.0` (exactly), and returning `0.0 + 1.0 * uniform01`, so I still can't really see why we'd return a 1.0 yet.

Even if we do satisfy the bounds, it is concerning that we do not match the actual generated values produced by PyTorch. We have a frontend test that tries to guarantee that, but maybe it is not strict enough.

**Comment by Priya2698** [comment]
With `float32` the kernel is using `rng_uniform_range` though.
```
Inputs:
Outputs:
  T0_g[ iblockIdx.x9{( ceilDiv(( ceilDiv(( ceilDiv(( 16 * 1024 ), 128) ), 1) ), 1) )}, iUS10{1}, iS8{1}, ithreadIdx.x6{128} ] ca_pos( 2 ) produce_pos( 4 ), float

%kernel_math {
T1_l[ iblockIdx.x16{( ceilDiv(( ceilDiv(( ceilDiv(( 16 * 1024 ), 128) ), 1) ), 1) )}, iUS17{1}, iS15{1}, ithreadIdx.x13{128} ] ca_pos( 4 )
   = rng_uniform_range({16, 1024}, double(0), double(1), float);
T0_g[ iblockIdx.x9{( ceilDiv(( ceilDiv(( ceilDiv(( 16 * 1024 ), 128) ), 1) ), 1) )}, iUS10{1}, iS8{1}, ithreadIdx.x6{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T1_l[ iblockIdx.x16{( ceilDiv(( ceilDiv(( ceilDiv(( 16 * 1024 ), 128) ), 1) ), 1) )}, iUS17{1}, iS15{1}, ithreadIdx.x13{128} ] ca_pos( 4 ), cache_op=Streaming )
}
```

**Comment by jacobhinkle** [comment]
I think the issue is the cast back to lower precision. We are probably not generating 1.0 as double, but something close enough to cast down to it. We may need to. Generate differently for lower precision.

**Comment by jacobhinkle** [comment]
One interesting thing here is that we are generating as double instead of float even if the start and stop values are given in `Float`.

**Comment by jacobhinkle** [comment]
I slightly modified the example to try and make it match PyTorch. We can insert a `where` to easily match the bounds of course, but matching the exact generated values is harder. In this script I'm hardcoding the seed and offset to 0 which should result in the exact same values.
```python
from nvfuser import FusionDefinition, DataType
import torch

M = 16
N = 1024

def fusion_fn(fd: FusionDefinition):
    shape = fd.define_vector([M, N], dtype=DataType.Int)
    S0 = fd.define_scalar(0.00000, dtype=DataType.Float)
    S1 = fd.define_scalar(1.00000, dtype=DataType.Float)
    S2 = fd.define_scalar(0, dtype=DataType.Int)
    output = fd.ops.uniform(S0, S1, shape=shape, dtype=DataType.BFloat16, rng_seed=S2, rng_offset=S2)
    #output = fd.ops.where(fd.ops.eq(output, S1), S0, output)
    fd.add_output(output)

with FusionDefinition() as fd:
    fusion_fn(fd)
output = fd.execute([])[0]

torch.manual_seed(0)
aten_output = torch.rand((M, N), dtype=torch.bfloat16, device='cuda')
matches = (aten_output == output).sum()
print(matches.item(), "elements out of", aten_output.numel(), "match")
print("pytorch:\n", aten_output)
print("nvfuser:\n", output)
assert torch.max(output) < 1.0, f'Min: {torch.min(output)} Max: {torch.max(output)}'
```
The output is concerning:
```
28 elements out of 16384 match
pytorch:
 tensor([[0.3984, 0.5156, 0.0249,  ..., 0.1377, 0.4492, 0.9883],
        [0.5352, 0.6328, 0.1455,  ..., 0.2402, 0.8633, 0.2324],
        [0.3008, 0.2275, 0.9453,  ..., 0.7109, 0.0160, 0.3594],
        ...,
        [0.3164, 0.5898, 0.6055,  ..., 0.1924, 0.3086, 0.3418],
        [0.3750, 0.1348, 0.4062,  ..., 0.4805, 0.0306, 0.3242],
        [0.6250, 0.7344, 0.7109,  ..., 0.6367, 0.5781, 0.0076]],
       device='cuda:0', dtype=torch.bfloat16)
nvfuser:
 tensor([[8.7891e-01, 6.0547e-01, 5.5511e-17,  ..., 3.4180e-01, 2.8422e-14,
         7.4609e-01],
        [1.7090e-02, 5.3406e-03, 5.5511e-17,  ..., 5.4297e-01, 5.6843e-14,
         1.5234e-01],
        [7.5391e-01, 1.5332e-01, 5.5511e-17,  ..., 9.9219e-01, 8.5265e-14,
         1.9531e-01],
        ...,
        [6.6406e-01, 2.4219e-01, 5.5511e-17,  ..., 4.6094e-01, 3.9790e-13,
         2.8125e-01],
        [6.4453e-01, 9.2188e-01, 5.5511e-17,  ..., 6.5234e-01, 4.2633e-13,
         8.9062e-01],
        [8.2812e-01, 5.7812e-01, 5.5511e-17,  ..., 7.6953e-01, 4.5475e-13,
         1.9043e-01]], device='cuda:0', dtype=torch.bfloat16)
Traceback (most recent call last):
  File "/root/randrepro_issue1653.py", line 27, in <module>
    assert torch.max(output) < 1.0, f'Min: {torch.min(output)} Max: {torch.max(output)}'
AssertionError: Min: 5.551115123125783e-17 Max: 1.0
```
It seems we have a repeated value in the third column `[2, :]`. Switching to M=8, N=8, we have even more repeats:
```
0 elements out of 64 match
pytorch:
 tensor([[0.3984, 0.5156, 0.0249, 0.9414, 0.9453, 0.7969, 0.4141, 0.8203],
        [0.2295, 0.9102, 0.1182, 0.0752, 0.4102, 0.9609, 0.2090, 0.1943],
        [0.8906, 0.4395, 0.3574, 0.5469, 0.8281, 0.2100, 0.7695, 0.4297],
        [0.2119, 0.6602, 0.1650, 0.4258, 0.9922, 0.6953, 0.2471, 0.7031],
        [0.7500, 0.9297, 0.0493, 0.0752, 0.7227, 0.9492, 0.3652, 0.2217],
        [0.7773, 0.6406, 0.2080, 0.7031, 0.9609, 0.0593, 0.3359, 0.0615],
        [0.7031, 0.5625, 0.0101, 0.8555, 0.5195, 0.5000, 0.1143, 0.2754],
        [0.5352, 0.8594, 0.8477, 0.1846, 0.6367, 0.6797, 0.4414, 0.5000]],
       device='cuda:0', dtype=torch.bfloat16)
nvfuser:
 tensor([[0.8789, 0.6055, 0.8789, 0.8789, 0.9414, 0.5156, 0.9414, 0.9414],
        [0.7148, 0.4648, 0.7148, 0.7148, 0.0679, 0.7188, 0.0679, 0.0679],
        [0.5586, 0.0771, 0.5586, 0.5586, 0.6641, 0.1064, 0.6641, 0.6641],
        [0.5781, 0.9883, 0.5781, 0.5781, 0.5859, 0.1943, 0.5859, 0.5859],
        [0.8906, 0.9180, 0.8906, 0.8906, 0.6562, 0.9180, 0.6562, 0.6562],
        [0.8516, 0.2695, 0.8516, 0.8516, 0.2637, 0.1445, 0.2637, 0.2637],
        [0.0374, 0.6289, 0.0374, 0.0374, 0.8867, 0.5117, 0.8867, 0.8867],
        [0.3711, 0.1719, 0.3711, 0.3711, 0.3867, 0.2314, 0.3867, 0.3867]],
       device='cuda:0', dtype=torch.bfloat16)
```
This could be a separate bug in specifying, so I tried removing the `rng_seed` and `rng_offset` arguments. In that case I don't expect any matches, but we also don't expect repeated values (at least in small samples), but here is the output:
```
0 elements out of 64 matchpytorch:
 tensor([[0.3984, 0.5156, 0.0249, 0.9414, 0.9453, 0.7969, 0.4141, 0.8203],        [0.2295, 0.9102, 0.1182, 0.0752, 0.4102, 0.9609, 0.2090, 0.1943],
        [0.8906, 0.4395, 0.3574, 0.5469, 0.8281, 0.2100, 0.7695, 0.4297],
        [0.2119, 0.6602, 0.1650, 0.4258, 0.9922, 0.6953, 0.2471, 0.7031],
        [0.7500, 0.9297, 0.0493, 0.0752, 0.7227, 0.9492, 0.3652, 0.2217],
        [0.7773, 0.6406, 0.2080, 0.7031, 0.9609, 0.0593, 0.3359, 0.0615],
        [0.7031, 0.5625, 0.0101, 0.8555, 0.5195, 0.5000, 0.1143, 0.2754],
        [0.5352, 0.8594, 0.8477, 0.1846, 0.6367, 0.6797, 0.4414, 0.5000]],
       device='cuda:0', dtype=torch.bfloat16)
nvfuser:
 tensor([[0.9258, 0.5820, 0.9258, 0.9258, 0.6797, 0.2334, 0.6797, 0.6797],
        [0.7461, 0.5820, 0.7461, 0.7461, 0.7500, 0.0356, 0.7500, 0.7500],
        [0.8047, 0.5078, 0.8047, 0.8047, 0.9688, 0.3906, 0.9688, 0.9688],
        [0.2598, 0.5078, 0.2598, 0.2598, 0.4473, 0.8828, 0.4473, 0.4473],
        [0.1816, 0.7070, 0.1816, 0.1816, 0.4844, 0.5312, 0.4844, 0.4844],
        [0.2695, 0.6289, 0.2695, 0.2695, 0.3926, 0.8789, 0.3926, 0.3926],
        [0.7656, 0.2539, 0.7656, 0.7656, 0.6055, 0.0625, 0.6055, 0.6055],
        [0.1064, 0.7734, 0.1064, 0.1064, 0.2314, 0.5820, 0.2314, 0.2314]],
       device='cuda:0', dtype=torch.bfloat16)
```

**Comment by zasdfgbnm** [comment]
> I slightly modified the example to try and make it match PyTorch. We can insert a `where` to easily match the bounds of course, but matching the exact generated values is harder. In this script I'm hardcoding the seed and offset to 0 which should result in the exact same values.
> 
> ```python
> from nvfuser import FusionDefinition, DataType
> import torch
> 
> M = 16
> N = 1024
> 
> def fusion_fn(fd: FusionDefinition):
>     shape = fd.define_vector([M, N], dtype=DataType.Int)
>     S0 = fd.define_scalar(0.00000, dtype=DataType.Float)
>     S1 = fd.define_scalar(1.00000, dtype=DataType.Float)
>     S2 = fd.define_scalar(0, dtype=DataType.Int)
>     output = fd.ops.uniform(S0, S1, shape=shape, dtype=DataType.BFloat16, rng_seed=S2, rng_offset=S2)
>     #output = fd.ops.where(fd.ops.eq(output, S1), S0, output)
>     fd.add_output(output)
> 
> with FusionDefinition() as fd:
>     fusion_fn(fd)
> output = fd.execute([])[0]
> 
> torch.manual_seed(0)
> aten_output = torch.rand((M, N), dtype=torch.bfloat16, device='cuda')
> matches = (aten_output == output).sum()
> print(matches.item(), "elements out of", aten_output.numel(), "match")
> print("pytorch:\n", aten_output)
> print("nvfuser:\n", output)
> assert torch.max(output) < 1.0, f'Min: {torch.min(output)} Max: {torch.max(output)}'
> ```
> 
> The output is concerning:
> 
> ```
> 28 elements out of 16384 match
> pytorch:
>  tensor([[0.3984, 0.5156, 0.0249,  ..., 0.1377, 0.4492, 0.9883],
>         [0.5352, 0.6328, 0.1455,  ..., 0.2402, 0.8633, 0.2324],
>         [0.3008, 0.2275, 0.9453,  ..., 0.7109, 0.0160, 0.3594],
>         ...,
>         [0.3164, 0.5898, 0.6055,  ..., 0.1924, 0.3086, 0.3418],
>         [0.3750, 0.1348, 0.4062,  ..., 0.4805, 0.0306, 0.3242],
>         [0.6250, 0.7344, 0.7109,  ..., 0.6367, 0.5781, 0.0076]],
>        device='cuda:0', dtype=torch.bfloat16)
> nvfuser:
>  tensor([[8.7891e-01, 6.0547e-01, 5.5511e-17,  ..., 3.4180e-01, 2.8422e-14,
>          7.4609e-01],
>         [1.7090e-02, 5.3406e-03, 5.5511e-17,  ..., 5.4297e-01, 5.6843e-14,
>          1.5234e-01],
>         [7.5391e-01, 1.5332e-01, 5.5511e-17,  ..., 9.9219e-01, 8.5265e-14,
>          1.9531e-01],
>         ...,
>         [6.6406e-01, 2.4219e-01, 5.5511e-17,  ..., 4.6094e-01, 3.9790e-13,
>          2.8125e-01],
>         [6.4453e-01, 9.2188e-01, 5.5511e-17,  ..., 6.5234e-01, 4.2633e-13,
>          8.9062e-01],
>         [8.2812e-01, 5.7812e-01, 5.5511e-17,  ..., 7.6953e-01, 4.5475e-13,
>          1.9043e-01]], device='cuda:0', dtype=torch.bfloat16)
> Traceback (most recent call last):
>   File "/root/randrepro_issue1653.py", line 27, in <module>
>     assert torch.max(output) < 1.0, f'Min: {torch.min(output)} Max: {torch.max(output)}'
> AssertionError: Min: 5.551115123125783e-17 Max: 1.0
> ```
> 
> It seems we have a repeated value in the third column `[2, :]`. Switching to M=8, N=8, we have even more repeats:
> 
> ```
> 0 elements out of 64 match
> pytorch:
>  tensor([[0.3984, 0.5156, 0.0249, 0.9414, 0.9453, 0.7969, 0.4141, 0.8203],
>         [0.2295, 0.9102, 0.1182, 0.0752, 0.4102, 0.9609, 0.2090, 0.1943],
>         [0.8906, 0.4395, 0.3574, 0.5469, 0.8281, 0.2100, 0.7695, 0.4297],
>         [0.2119, 0.6602, 0.1650, 0.4258, 0.9922, 0.6953, 0.2471, 0.7031],
>         [0.7500, 0.9297, 0.0493, 0.0752, 0.7227, 0.9492, 0.3652, 0.2217],
>         [0.7773, 0.6406, 0.2080, 0.7031, 0.9609, 0.0593, 0.3359, 0.0615],
>         [0.7031, 0.5625, 0.0101, 0.8555, 0.5195, 0.5000, 0.1143, 0.2754],
>         [0.5352, 0.8594, 0.8477, 0.1846, 0.6367, 0.6797, 0.4414, 0.5000]],
>        device='cuda:0', dtype=torch.bfloat16)
> nvfuser:
>  tensor([[0.8789, 0.6055, 0.8789, 0.8789, 0.9414, 0.5156, 0.9414, 0.9414],
>         [0.7148, 0.4648, 0.7148, 0.7148, 0.0679, 0.7188, 0.0679, 0.0679],
>         [0.5586, 0.0771, 0.5586, 0.5586, 0.6641, 0.1064, 0.6641, 0.6641],
>         [0.5781, 0.9883, 0.5781, 0.5781, 0.5859, 0.1943, 0.5859, 0.5859],
>         [0.8906, 0.9180, 0.8906, 0.8906, 0.6562, 0.9180, 0.6562, 0.6562],
>         [0.8516, 0.2695, 0.8516, 0.8516, 0.2637, 0.1445, 0.2637, 0.2637],
>         [0.0374, 0.6289, 0.0374, 0.0374, 0.8867, 0.5117, 0.8867, 0.8867],
>         [0.3711, 0.1719, 0.3711, 0.3711, 0.3867, 0.2314, 0.3867, 0.3867]],
>        device='cuda:0', dtype=torch.bfloat16)
> ```
> 
> This could be a separate bug in specifying, so I tried removing the `rng_seed` and `rng_offset` arguments. In that case I don't expect any matches, but we also don't expect repeated values (at least in small samples), but here is the output:
> 
> ```
> 0 elements out of 64 matchpytorch:
>  tensor([[0.3984, 0.5156, 0.0249, 0.9414, 0.9453, 0.7969, 0.4141, 0.8203],
>         [0.2295, 0.9102, 0.1182, 0.0752, 0.4102, 0.9609, 0.2090, 0.1943],
>         [0.8906, 0.4395, 0.3574, 0.5469, 0.8281, 0.2100, 0.7695, 0.4297],
>         [0.2119, 0.6602, 0.1650, 0.4258, 0.9922, 0.6953, 0.2471, 0.7031],
>         [0.7500, 0.9297, 0.0493, 0.0752, 0.7227, 0.9492, 0.3652, 0.2217],
>         [0.7773, 0.6406, 0.2080, 0.7031, 0.9609, 0.0593, 0.3359, 0.0615],
>         [0.7031, 0.5625, 0.0101, 0.8555, 0.5195, 0.5000, 0.1143, 0.2754],
>         [0.5352, 0.8594, 0.8477, 0.1846, 0.6367, 0.6797, 0.4414, 0.5000]],
>        device='cuda:0', dtype=torch.bfloat16)
> nvfuser:
>  tensor([[0.9258, 0.5820, 0.9258, 0.9258, 0.6797, 0.2334, 0.6797, 0.6797],
>         [0.7461, 0.5820, 0.7461, 0.7461, 0.7500, 0.0356, 0.7500, 0.7500],
>         [0.8047, 0.5078, 0.8047, 0.8047, 0.9688, 0.3906, 0.9688, 0.9688],
>         [0.2598, 0.5078, 0.2598, 0.2598, 0.4473, 0.8828, 0.4473, 0.4473],
>         [0.1816, 0.7070, 0.1816, 0.1816, 0.4844, 0.5312, 0.4844, 0.4844],
>         [0.2695, 0.6289, 0.2695, 0.2695, 0.3926, 0.8789, 0.3926, 0.3926],
>         [0.7656, 0.2539, 0.7656, 0.7656, 0.6055, 0.0625, 0.6055, 0.6055],
>         [0.1064, 0.7734, 0.1064, 0.1064, 0.2314, 0.5820, 0.2314, 0.2314]],
>        device='cuda:0', dtype=torch.bfloat16)
> ```

The repeating values are due to mismatches in:
https://github.com/NVIDIA/Fuser/blob/d8589a48cdbaaedef63cdf32f6772949b034c6ac/csrc/codegen.cpp#L770-L772
https://github.com/NVIDIA/Fuser/blob/d8589a48cdbaaedef63cdf32f6772949b034c6ac/csrc/ir/internal_nodes.h#L760-L762
which I believe when implemented, there were an implicit assumption that the dtype can only be float or double

**Comment by zasdfgbnm** [comment]
But on the other hand, I don't think we have to generate exactly the same random values as PyTorch. nvFuser's random value is bound to tensor's linear index, but PyTorch's one is bound to specific thread allocation of that specific thread. I think nvFuser's way makes more sense.

**Comment by zasdfgbnm** [comment]
> But on the other hand, I don't think we have to generate exactly the same random values as PyTorch. nvFuser's random value is bound to tensor's linear index, but PyTorch's one is bound to specific thread allocation of that specific thread. I think nvFuser's way makes more sense.

Providing some historical note: We used to generate exactly the same random values as PyTorch. But that approach had a problem with broadcasting https://github.com/pytorch/pytorch/issues/82784, that's why we moved to an approach that bound random values with tensor's linear index.

**Comment by zasdfgbnm** [comment]
BTW, this is an example why I disliked PyTorch's RNG kernels:

```python
>>> import torch
>>> a = torch.empty((3, 3), device='cuda')
>>> b = torch.empty_strided((3, 3), stride=(1, 3), device='cuda')
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x7f4b24fb94b0>
>>> a.random_()
tensor([[ 2615407.,  4527453.,  6411889.],
        [11078092.,  2326039., 16159553.],
        [ 4087101., 16538380., 10655256.]], device='cuda:0')
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x7f4b24fb94b0>
>>> a.random_()
tensor([[ 2615407.,  4527453.,  6411889.],
        [11078092.,  2326039., 16159553.],
        [ 4087101., 16538380., 10655256.]], device='cuda:0')
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x7f4b24fb94b0>
>>> b.random_()
tensor([[ 2615407., 11078092.,  4087101.],
        [ 4527453.,  2326039., 16538380.],
        [ 6411889., 16159553., 10655256.]], device='cuda:0')
>>> torch.manual_seed(0)
<torch._C.Generator object at 0x7f4b24fb94b0>
>>> b.random_()
tensor([[ 2615407., 11078092.,  4087101.],
        [ 4527453.,  2326039., 16538380.],
        [ 6411889., 16159553., 10655256.]], device='cuda:0')
```
For the same seed, the random values actually depend on the stride order of the tensor...

**Comment by jacobhinkle** [comment]
> repeated values 

So as you say, @zasdfgbnm this is an easy fix, just changing that `== DataType.Float` condition to `!= DataType.Double`. But I really like your other idea of having `RNGOp` node just provide a pair of uints and a component, then we normalize or compute Box-Muller, etc. using regular pointwise ops in the IR.

**Comment by Priya2698** [comment]
@jacobhinkle Did you have a PR for this? We are still seeing this issue.

**Comment by jacobhinkle** [comment]
It's worth considering whether we can just avoid casting to half precision at all in these scenarios. This is a factory method so if there are no uses and this is a fusion output it's probably a one-expression segment; then we could have just run `torch.uniform`. If there _is_ fusion, then very likely the only uses for the generated values are to cast to float, in which case we should probably just generate the values in float precision to begin with. This could be done with a peephole opt preseg pass that replaces `cast(float, uniform(half))` with `uniform(float)`. It could probably even be done in the round-trip cast pass. Even though this technically is a non-idempotent round trip, since we are generating the values anyway it should be considered safe.
