### ISSUE TITLE
resolution points of persistent buffers are not correctly identified

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#1665]
**Issue:** In the following fusion we have two resolution points, t4 and t5. Current main branch only detects t4. After project to inputs, tv1 remains a persistent buffer as it cannot be inlined with t5.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/5aac6aa6-a36f-4d3a-b8f5-734de79d0489)

**Reason:** outputs of expression with resolution point are still on reduction path. **Current code only puts the outputs to persistent path.**

**Fix:** Put outputs ( of expression with resolution point ) to **both reduction path and persistent path**

**Comment by liqiangxl** [comment]
Summay of some discussions:
(1) Do we need to put outputs ( of expression with resolution point ) to both reduction path and persistent path?
Yes. we should do this.
I did this at the beginning, but then it leads to a result that all the tvs after the first resolution point becomes resolution point. This doesn't cause any problem for us and in fact they should be resolution points. Otherwise, the calculated persistent buffer size is not right. For example in the following figure, the left part underestimated the persistent buffer size.
```
  // There are two persistent buffers: tv0 and tv1.
  // For tv0, the reduction path is 2 -> 4 -> 6 -> 8 -> 9.
  // For tv0, the persistent path is 0 -> 6 -> 8 -> 9.
  // It has 3 resolution points: 6, 8, and 9.
  // For tv1, the reduction path is 3 -> 5 -> 7 -> 9.
  // For tv1, the persistent path is 1 -> 7 -> 9.
  // It has 2 resolution points: 7 and 9.
  // At resolution point 9, both tv0 and tv1 should be active.
  // The persistent buffer should be tv0 + tv1.
```
![image](https://github.com/NVIDIA/Fuser/assets/116412316/a2e632cd-9902-4599-a12e-58b0732e9e7a)

we can't reason like: `8` only depends on `6`, so after point `6`, buffer `0` is no longer required and is resolved.
Because, `6,8,9` are inlined and computed under the same for-loop. we can't complete `6` then move to the compute of `8`. (if doing so, `6` becomes a persistent buffer)

**Comment by naoyam** [comment]
What was the original case where this issue showed up?

**Comment by liqiangxl** [comment]
> What was the original case where this issue showed up?

I created this issue while working on https://github.com/NVIDIA/Fuser/issues/1631
The root cause of #1631 is when project persistent buffer to inputs, we should replace all persistent uses, but it missed to replace all the persistent uses.

**Comment by naoyam** [comment]
> > What was the original case where this issue showed up?
> 
> I created this issue while working on #1631 The root cause of #1631 is when project persistent buffer to inputs, we should replace all persistent uses, but it missed to replace some of the persistent uses.

Why does it result in the error with expression sorting?

**Comment by liqiangxl** [comment]
> > > What was the original case where this issue showed up?
> > 
> > 
> > I created this issue while working on #1631 The root cause of #1631 is when project persistent buffer to inputs, we should replace all persistent uses, but it missed to replace some of the persistent uses.
> 
> Why does it result in the error with expression sorting?

Still working on it, [here](https://docs.google.com/document/d/1tZoJKmyX6EFf1OZipaIg2Ts3fm7LN6BuuyfQa94_oQg/edit?usp=sharing) is what i have found so far.

**Comment by liqiangxl** [comment]
> > > What was the original case where this issue showed up?
> > 
> > 
> > I created this issue while working on #1631 The root cause of #1631 is when project persistent buffer to inputs, we should replace all persistent uses, but it missed to replace some of the persistent uses.
> 
> Why does it result in the error with expression sorting?

Here is the reason: https://github.com/NVIDIA/Fuser/pull/1762
