### ISSUE TITLE
Segmenter failed to propose the right segment to MatmulScheduler. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1707]
This causes a "Can not find a scheduler to schedule fusion segment" error. 

The full test can be found in the `wjy/segment_matmul` branch. I'm copying the gist of it here for convenience: 

```
TensorView* a = makeContigTensor(2, DataType::Half);
fusion->addInput(a);
TensorView* b = makeContigTensor(2, DataType::Half);
fusion->addInput(b);

TensorView* c = matmul(
    a, b, MmaLayout::TT, /*turing_or_later=*/true, /*as_mul_sum=*/false);
c = segment_set(c);
c = castOp(DataType::Half, c);
fusion->addOutput(c);
```

@jacobhinkle created a great illustration explaining what happened for a slightly different[^1] test: 
![image](https://github.com/NVIDIA/Fuser/assets/2772612/578ac0db-da4a-41ec-addb-397713f92d64)

[^1]: The figure uses Sum after SegmentSet and the test above uses Cast. However, it's a minor difference that doesn't affect the diagnosis. 

As designed, the segmenter tries to merge one edge at a time. So, it tried to schedule region 4 and region 5 separately, both of which failed [this check](https://github.com/NVIDIA/Fuser/blob/37f5c39385041e5c365a85b49dbc4af80561b059/csrc/scheduler/matmul_utils.cpp#L288) where MatmulScheduler requires both MmaOp inputs to be broadcast. After those failures, the segmenter didn't even attempt to schedule the union of 4 and 5, which would succeed. 

# To reproduce

```shell
git fetch origin wjy/segment_matmul
git checkout wjy/segment_matmul
_bn && bin/test_matmul --gtest_filter=*SegmentBroadcastMatmul 
```

**Comment by zasdfgbnm** [comment]
Self assign for now as I am working on https://github.com/NVIDIA/Fuser/issues/1628 whose solution would help on this.

**Comment by wujingyue** [comment]
Thanks, @zasdfgbnm, for picking this up! 

It'll probably be the best fix for the time being. The current segmentation algorithm assumes `canSchedule` is _contiguous_. That is, for a segmented region (note: the complete fusion is special-cased) to be accepted by a scheduler, there must be a sequence of merging from a singleton region to that region such that (1) each step merges one edge, and (2) each region in the sequence is accepted by the scheduler. This assumption doesn't hold for [this check](https://github.com/NVIDIA/Fuser/blob/37f5c39385041e5c365a85b49dbc4af80561b059/csrc/scheduler/matmul_utils.cpp#L288) in `MatmulScheduler::canSchedule`. 

We could avoid this assumption at the cost of making segmentation more expensive. For example, as a special case for matmul, segmentation could try to merge both input edges of a matmul region at once. I'll keep this potential improvement in the backlog until we have more needs to be able to generalize.

**Comment by naoyam** [comment]
> We could avoid this assumption at the cost of making segmentation more expensive. For example, as a special case for matmul, segmentation could try to merge both input edges of a matmul region at once. I'll keep this potential improvement in the backlog until we have more needs to be able to generalize.

There's already shortcuts like this. For example, see https://github.com/NVIDIA/Fuser/blob/main/csrc/fusion_segmenter.cpp#L2899-L2907. That's for effectively detecting normalization patterns, which would have similar issues as matmul if not having the special case. 

It seems to me that we would want to have some sort of a mixed approach. There are a certain set of patterns that we know we want to schedule in a specific way, like normalization and matmul. Let's say core patterns. There's also a bunch of operations that can be fused with those core patterns, which we may be able to discover by iteratively trying to fuse them. Currently, we have a core pattern for normalization. We probably want to have one for matmul as well. We would also need to rethink about the overall organization of this mixed approach, but I hope that could be done incrementally.

**Comment by wujingyue** [comment]
> That's for effectively detecting normalization patterns

Thanks for bringing up more use cases! They are valuable for figuring out a generalized solution. 

> There's also a bunch of operations that can be fused with those core patterns, which we may be able to discover by iteratively trying to fuse them

Yes, that's a great idea. Instead of starting from singletons, we can first let each scheduler propose core patterns (which are very scheduler specific) and then let the segmenter incrementally merge surrounding ops (which is a general piece of logic that should live in the segmenter).
