### ISSUE TITLE
nvFuser produces (slightly) wrong numbers in test_rope.py. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1742]
I was able to work around by increasing the threshold, but I think this is still worth attention. I believe there's a real bug rather than a floating-point representation error. 

To reproduce, run the following
```
$ git fetch origin wjy/mismatch
$ git checkout wjy/mismatch
$ pytest python_benchmarks/test_rope.py -k with_cat -s
...
>           torch.testing.assert_close(nvf_out, [ref_out], atol=0, rtol=0)
E           AssertionError: Tensor-likes are not equal!
E
E           Mismatched elements: 121664043 / 536870912 (22.7%)
E           Greatest absolute difference: 0.03125 at index (0, 0, 2444, 88)
E           Greatest relative difference: inf at index (0, 0, 122, 124)
E
E           The failure occurred for item [0]
```

`atol=0, rtol=0` may appear to be too strict but it's really not. `out = q * cos + q_rotated * sin` is the only reduction-ish op. Since it's adding two numbers piecewise, I expect a bit-exact match between the nvFuser output and the eager output. 

Now comes the most interesting part. If I remove the cast to bfloat at the end of the fusion and [that in the reference implementation](https://github.com/NVIDIA/Fuser/blob/wjy/mismatch/python_benchmarks/test_rope.py#L174), the two outputs match bit-exact. So I went to print the element at (0,0,122,124) before the cast and after the cast. 

```
python_benchmarks/test_rope.py before cast: 0
after cast in ref: 0
after cast in nvf: -0.0004119873046875
```

The eager output clearly makes more sense: `float2bfloat(0)` should be 0 not -0.0004119873046875. 

My first suspicion was the cast op. However, a smaller fusion I wrote just doing the cast failed to reproduce the problem.

**Comment by jacobhinkle** [comment]
What does the nvfuser output look like without the cast? Is it 0.0f?

**Comment by jjsjann123** [comment]
This is hard to say who's doing the right thing here... is nvf output before cast also `0`?

Maybe it's worth bump the reference implementation precision and use that as a ground truth.

**Comment by jjsjann123** [comment]
> Since it's adding two numbers piecewise, I expect a bit-exact match between the nvFuser output and the eager output.

This would generally also not be the case. MUFU instructions and some simple FMA would produce numerical differences as well. We used to disable all optimization in our unit test, which did help but is still not bullet-proof.

**Comment by wujingyue** [comment]
> What does the nvfuser output look like without the cast? Is it 0.0f? Edit: ok I see you say they match so its 0. Could this be due to an extra cast somewhere due to segmentation?

Not sure what you are looking for exactly. The last segment looks normal -- it runs the following two statements with `*` and `+` on float32. 

```
out = q * cos + q_rotated * sin
out = fd.ops.cast(out, DataType.BFloat16)
```

```
Inputs:
  T2_g[ iS784{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iS783{8}, iS785{blockDim.x} ], __bfloat
  T4_g[ iS731{( ceilDiv(( ceilDiv(( 4096 * 64 ), 8) ), blockDim.x) )}, iS734{( ceilDiv(( 32 * 32 ), 1) )}, iS735{1}, iS730{8}, iS732{blockDim.x} ], __bfloat
  T8_g[ iS747{( ceilDiv(( ceilDiv(( 4096 * 64 ), 8) ), blockDim.x) )}, iS750{( ceilDiv(( 32 * 32 ), 1) )}, iS751{1}, iS746{8}, iS748{blockDim.x} ], __bfloat
  T155_g[ iS771{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iS774{( ceilDiv(( 32 * 32 ), 1) )}, iS775{1}, iS770{8}, iS772{blockDim.x} ], __bfloat
Outputs:
  T23_g[ iblockIdx.y652{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x654{( ceilDiv(( 32 * 32 ), 1) )}, iUS655{1}, iV651{8}, ithreadIdx.x653{blockDim.x} ] ca_pos( 3 ) produce_pos( 3 ), __bfloat

%kernel_math {
T157_l[ iblockIdx.y763{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x766{( ceilDiv(( 32 * 32 ), 1) )}, iUS767{1}, iV762{8}, ithreadIdx.x764{blockDim.x} ] ca_pos( 3 )
   = Set( T155_g[ iS771{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iS774{( ceilDiv(( 32 * 32 ), 1) )}, iS775{1}, iS770{8}, iS772{blockDim.x} ], cache_op=Streaming )
T154_l[ iblockIdx.y755{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x758{( ceilDiv(( 32 * 32 ), 1) )}, iUS759{1}, iS754{8}, ithreadIdx.x756{blockDim.x} ] ca_pos( 5 ) produce_pos( 3 )
   = __bfloat2float(T157_l[ iblockIdx.y763{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x766{( ceilDiv(( 32 * 32 ), 1) )}, iUS767{1}, iV762{8}, ithreadIdx.x764{blockDim.x} ] ca_pos( 3 ));
T9_l[ iblockIdx.y739{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x742{( ceilDiv(( 32 * 32 ), 1) )}, iUS743{1}, iS738{8}, ithreadIdx.x740{blockDim.x} ] ca_pos( 5 )
   = pad( T8_g[ iS747{( ceilDiv(( ceilDiv(( 4096 * 64 ), 8) ), blockDim.x) )}, iS750{( ceilDiv(( 32 * 32 ), 1) )}, iS751{1}, iS746{8}, iS748{blockDim.x} ], {0, 0, 0, 0, 0, 0, 0, 64} )
i146 = 0 + 64;
T10_l[ iblockIdx.y723{( ceilDiv(( ceilDiv(( 4096 * ( ( 0 + 64 ) + 64 ) ), 8) ), blockDim.x) )}, iblockIdx.x726{( ceilDiv(( 32 * 32 ), 1) )}, iUS727{1}, iS722{8}, ithreadIdx.x724{blockDim.x} ] ca_pos( 5 )
   = pad( T4_g[ iS731{( ceilDiv(( ceilDiv(( 4096 * 64 ), 8) ), blockDim.x) )}, iS734{( ceilDiv(( 32 * 32 ), 1) )}, iS735{1}, iS730{8}, iS732{blockDim.x} ], {0, 0, 0, 0, 0, 0, i146, 0} )
T11_l[ iblockIdx.y715{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x718{( ceilDiv(( 32 * 32 ), 1) )}, iUS719{1}, iS714{8}, ithreadIdx.x716{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   = cat( T9_l[ iblockIdx.y739{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x742{( ceilDiv(( 32 * 32 ), 1) )}, iUS743{1}, iS738{8}, ithreadIdx.x740{blockDim.x} ] ca_pos( 5 ), T10_l[ iblockIdx.y723{( ceilDiv(( ceilDiv(( 4096 * ( ( 0 + 64 ) + 64 ) ), 8) ), blockDim.x) )}, iblockIdx.x726{( ceilDiv(( 32 * 32 ), 1) )}, iUS727{1}, iS722{8}, ithreadIdx.x724{blockDim.x} ] ca_pos( 5 ), 3 )
T19_l[ iblockIdx.y707{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x710{( ceilDiv(( 32 * 32 ), 1) )}, iUS711{1}, iS706{8}, ithreadIdx.x708{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   = __bfloat2float(T11_l[ iblockIdx.y715{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x718{( ceilDiv(( 32 * 32 ), 1) )}, iUS719{1}, iS714{8}, ithreadIdx.x716{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 ));
T156_l[ iblockIdx.y779{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iS778{8}, ithreadIdx.x780{blockDim.x} ] ca_pos( 1 )
   = Set( T2_g[ iS784{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iS783{8}, iS785{blockDim.x} ], cache_op=AllLevels )
T14_l[ iblockIdx.y699{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, bblockIdx.x702{( ceilDiv(( 1 * 1 ), 1) )}, bUS703{1}, iS698{8}, ithreadIdx.x700{blockDim.x} ] ca_pos( 5 ) produce_pos( 1 )
   = broadcast( T156_l[ iblockIdx.y779{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iS778{8}, ithreadIdx.x780{blockDim.x} ] ca_pos( 1 ) )
T15_l[ iblockIdx.y691{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, bblockIdx.x694{( ceilDiv(( 1 * 1 ), 1) )}, bUS695{1}, iS690{8}, ithreadIdx.x692{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   = Set( T14_l[ iblockIdx.y699{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, bblockIdx.x702{( ceilDiv(( 1 * 1 ), 1) )}, bUS703{1}, iS698{8}, ithreadIdx.x700{blockDim.x} ] ca_pos( 5 ) produce_pos( 1 ), cache_op=Streaming )
T20_l[ iblockIdx.y683{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, bblockIdx.x686{( ceilDiv(( 1 * 1 ), 1) )}, bUS687{1}, iS682{8}, ithreadIdx.x684{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   = __bfloat2float(T15_l[ iblockIdx.y691{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, bblockIdx.x694{( ceilDiv(( 1 * 1 ), 1) )}, bUS695{1}, iS690{8}, ithreadIdx.x692{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 ));
T21_l[ iblockIdx.y675{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x678{( ceilDiv(( 32 * 32 ), 1) )}, iUS679{1}, iS674{8}, ithreadIdx.x676{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   = T19_l[ iblockIdx.y707{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x710{( ceilDiv(( 32 * 32 ), 1) )}, iUS711{1}, iS706{8}, ithreadIdx.x708{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   * T20_l[ iblockIdx.y683{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, bblockIdx.x686{( ceilDiv(( 1 * 1 ), 1) )}, bUS687{1}, iS682{8}, ithreadIdx.x684{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 );
T22_l[ iblockIdx.y667{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x670{( ceilDiv(( 32 * 32 ), 1) )}, iUS671{1}, iS666{8}, ithreadIdx.x668{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 )
   = T154_l[ iblockIdx.y755{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x758{( ceilDiv(( 32 * 32 ), 1) )}, iUS759{1}, iS754{8}, ithreadIdx.x756{blockDim.x} ] ca_pos( 5 ) produce_pos( 3 )
   + T21_l[ iblockIdx.y675{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x678{( ceilDiv(( 32 * 32 ), 1) )}, iUS679{1}, iS674{8}, ithreadIdx.x676{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 );
T158_l[ iblockIdx.y659{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x662{( ceilDiv(( 32 * 32 ), 1) )}, iUS663{1}, iS658{8}, ithreadIdx.x660{blockDim.x} ] ca_pos( 3 ) produce_pos( 5 )
   = __float2bfloat(T22_l[ iblockIdx.y667{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x670{( ceilDiv(( 32 * 32 ), 1) )}, iUS671{1}, iS666{8}, ithreadIdx.x668{blockDim.x} ] ca_pos( 5 ) produce_pos( 5 ));
T23_g[ iblockIdx.y652{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x654{( ceilDiv(( 32 * 32 ), 1) )}, iUS655{1}, iV651{8}, ithreadIdx.x653{blockDim.x} ] ca_pos( 3 ) produce_pos( 3 )
   = Set( T158_l[ iblockIdx.y659{( ceilDiv(( ceilDiv(( 4096 * 128 ), 8) ), blockDim.x) )}, iblockIdx.x662{( ceilDiv(( 32 * 32 ), 1) )}, iUS663{1}, iS658{8}, ithreadIdx.x660{blockDim.x} ] ca_pos( 3 ) produce_pos( 5 ), cache_op=Streaming )
}
```

**Comment by wujingyue** [comment]
> This is hard to say who's doing the right thing here... is nvf output before cast also `0`?

Yes. "If I remove the cast to bfloat at the end of the fusion and [that in the reference implementation](https://github.com/NVIDIA/Fuser/blob/wjy/mismatch/python_benchmarks/test_rope.py#L174), the two outputs match bit-exact"

**Comment by wujingyue** [comment]
SASS looks normal too.

With cast, nvFuser runs `FFMA` followed by `F2FP`. 

```
        /*2bf0*/                   FFMA R3, R26, R3, R15 ;
        /*2c00*/                   FFMA R22, R22, R17, R33 ;
        /*2c10*/                   FFMA R55, R55, R8, R32 ;
        /*2c20*/                   FFMA R6, R21, R14, R6 ;
        /*2c30*/                   FFMA R11, R4, R11, R19 ;
        /*2c40*/                   FFMA R0, R7, R0, R12 ;
        /*2c50*/                   F2FP.BF16.F32.PACK_AB R5, R22, R3 ;
        /*2c60*/                   F2FP.BF16.F32.PACK_AB R4, R55, R10 ;
        /*2c70*/                   F2FP.BF16.F32.PACK_AB R6, R9, R6 ;
        /*2c80*/                   IADD3.X R3, R40, c[0x0][0x264], RZ, P0, !PT ;
        /*2c90*/                   F2FP.BF16.F32.PACK_AB R7, R0, R11 ;
        /*2ca0*/                   STG.E.EF.128 [R2.64], R4 ;
        /*2cb0*/                   EXIT ;
```

Without cast, nvFuser runs the same type of `FFMA` (just without `F2FP`). 
```
        /*1690*/                   IADD3 R18, P0, R18, c[0x0][0x260], RZ ;
        /*16a0*/                   FFMA R12, R5, R4, R12 ;
        /*16b0*/                   FFMA R14, R7, R2, R14 ;
        /*16c0*/                   FFMA R15, R0, R3, R15 ;
        /*16d0*/                   IADD3.X R19, R24, c[0x0][0x264], RZ, P0, !PT ;
        /*16e0*/                   STG.E.EF.128 [R18.64], R12 ;
        /*16f0*/                   EXIT ;
```
```

**Comment by jjsjann123** [comment]
don't see anything suspicious with the instructions.

But if you look at the segmentation, it adds some complexity. The cast at the end seems to also affect an intermediate tensor saved by `kernel2` as `float32` instead of `bf16`. Which is later used to compute the fma in `kernel3`. :wink:

So it's not that we are just casting at the very end.

**Comment by jjsjann123** [comment]
Try running with `NVFUSER_DUMP=segmented_fusion`, you should see how intermediate tensors are demoted to `bf16`, which should explain the numerical difference.

**Comment by wujingyue** [comment]
> The cast at the end seems to also affect intermediate tensors saved by kernel2 as bf16

You two are amazing! I never suspected segmentation could **add** bf16 roundtrips. I thought it merely split the graph -- TIL. 

Just to spell it out, without the cast at the end, the fusion looks like
```
...
segment_out = float(q) * float(cos)
return segment_out + float(q_rotated) * float(sin)
```

With the cast at the end, the fusion (more precisely, the rewritten complete fusion) looks like
```
...
segment_out = bfloat(float(q) * float(cos))
return bfloat(float(segment_out) + float(q_rotated) * float(sin))
```
Note that the latter code snippet has *two* `bfloat(...)`. I expected the `bfloat` on the return value because that's what the added cast does. I did *not* expect the `bfloat` on `segment_out`. That seems to appear only after segmentation.

**Comment by wujingyue** [comment]
Circling back on this, https://github.com/NVIDIA/Fuser/blob/9fac12bdd98a63fdc88dde265b8add6a0e3f41cf/csrc/fusion_segmenter.cpp#L4392-L4399 explains the behavior we saw. With the cast to bfloat at the end, `tmp` is annotated as force-half, because it has a use chain to the bfloat return value. As a result, [this function](https://github.com/NVIDIA/Fuser/blob/9fac12bdd98a63fdc88dde265b8add6a0e3f41cf/csrc/fusion_segmenter.cpp#L1202) inserts a bfloat roundtrip (and thus `segment_out` of type bfloat). 

IIUC, `ForceHalfAnnotation` was built with a good intention to reduce global data transfer. However, this heuristic, which forces a segment boundary to be half/bfloat when it's used by a half/bfloat fusion output, seems to be too aggressive. It indeed causes precision loss in this particular example. Wdyt, @naoyam ?

**Comment by jacobhinkle** [comment]
> This would generally also not be the case. MUFU instructions and some simple FMA would produce numerical differences as well. We used to disable all optimization in our unit test, which did help but is still not bullet-proof.

Given that 77.3% of the elements match bitwise even with `annotateFP16IntermediateTensors()`, does that mean this is WAI? It does seem a bit cavalier to introduce casts on `DataType::Float` tensor edges. I wonder what is the perf impact of disabling this pass i.e. commenting out this line https://github.com/NVIDIA/Fuser/blob/9fac12bdd98a63fdc88dde265b8add6a0e3f41cf/csrc/fusion_segmenter.cpp#L455.

**Comment by naoyam** [comment]
I thought this is considered acceptable but I don't remember if there's any explicit contract. We should probably ask the Pytorch core folks.

**Comment by wujingyue** [comment]
> does that mean this is WAI?

For mixed-precision training and inference, it's critical to give users that level of control to trade between accuracy and speed. Therefore, IMHO, a compiler should respect the precision that the API has specified. Currently, `castInputOutputToLowerPrecision` lowers precision **implicitly**, which may hurt UX down the road. 

(Auto mixed precision is a different story. It happens at a higher level and auto-selects precision for the user. But even that it assumes the underlying compiler respects the precision it picks.)

> It does seem a bit cavalier to introduce casts on DataType::Float tensor edges. I wonder what is the perf impact of disabling this pass i.e. commenting out this line

Yeah, that's a good practical consideration -- maybe we are relying on the wrong behavior to deliver good performance :) 

Just to dump my brain, I **think** we don't have to remove force-half annotation entirely. The current logic of tracking the def-use chain etc is **safe** for data movement operations like reshape and permute.
