### ISSUE TITLE
supports `device` argument for factory methods

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#175]
nvfuser should support `device` argument.

We could have factory methods in fusion that doesn't have a tensor input, so `device` argument would be necessary to determine GPU device for kernel generation.

e.g. in cpp tests
https://github.com/NVIDIA/Fuser/blob/44e99fed361ce6969b74fb2ad30ca762bdf9233e/test/test_gpu_tensor_factories.cpp#L51-L56

Note that these arguments should also be plumbed all the way through to python API.

**Comment by jacobhinkle** [comment]
Could this live _only_ in the Python API?

Currently we determine the device at Fusion level by looking at all the input devices when it's run (defaulting to device 0). It seems like the device for factory-produced TVs will often be determined by other inputs in this way. We could add `device=None` kwargs to the Python wrapped factory (and RNG) ops that just stores a default device if given, that it then uses later as a `CompileOption` in the corresponding call to `runFusion`.

**Comment by jjsjann123** [comment]
That sound reasonable to what we currently support.

Although I'm a little bit hesitant to make a premature call here, since I don't have a good idea how multi-device support will look like from the codegen perspective. cc'ing @naoyam

**Comment by jacobhinkle** [comment]
Yeah for sure; I don't know much about the plans for multi-device. In the frontend I'm assuming we'd prob need some way to create `MultiClusterFusion` objects first. Until then I was just thinking we need to assume the Fusion runs on a single device.

**Comment by naoyam** [comment]
Ignoring multi-device extensions, I think what Jacob mentioned makes sense. From the codegen side, there's basically no notion of "different" devices, but there's only one device.

For multi-device extensions, the current plan is to abstract away from the user the fact that there are multiple devices so that we could determine how to distribute tensors. I don't think we want to allow the user to specify where to allocate a tensor. This may change, but for the mean time, I don't think we would need to think too much about it.

**Comment by jacobhinkle** [comment]
> I don't think we want to allow the user to specify where to allocate a tensor. 

With that in mind, @jjsjann123 how important is it to match the eager mode behavior (i.e. `device=` argument on factory ops) vs. just enabling Python code to tell us where to execute no-TV-input Fusions? If not at all, then I think putting the `device` arg in `fd.execute()` is the simplest on our end.

**Comment by jjsjann123** [comment]
> We could add device=None kwargs to the Python wrapped factory (and RNG) ops that just stores a default device if given, that it then uses later as a CompileOption in the corresponding call to runFusion.

Just want to point out, we might want to support device as a runtime input for factory methods as well?! That could be a low priority though.

> how important is it to match the eager mode behavior (i.e. device= argument on factory ops) vs. just enabling Python code to tell us where to execute no-TV-input Fusions?

If we assume that there's no cross device operations, I guess we can safely ignore/detach the `device` arg from a certain op, but just rely on the assumption that all ops within a fusion would be on a single device.
I'm not sure how extensive our horizontal fusion is for python API. i.e. if we have two independent data flow in a fusion, we might need to use `device` argument to segment the fusion if they ended up on two different devices.

^^^ So just to be future proof, I'm slightly uncomfortable with us detaching `device` argument from the actual op but treats that as a `fusion` property.

**Comment by kevinstephano** [comment]
Why would not having the output tensor specified as having a device be sufficient?

**Comment by naoyam** [comment]
>  we might want to support device as a runtime input for factory methods as well?!

This seems to have large implications. Would we need to support, say, a case where inputs were on device 0 and generating a tensor on device 1, and returning an output on device, where?

**Comment by jjsjann123** [comment]
> Why would not having the output tensor specified as having a device be sufficient?

That is sufficient, but it's more work :rofl: I think Jacob is trying to go with a less intrusive way to do this.
I think I'm trying to argue that we do need to annotate ALL tensors with a device property. (maybe something on python IR would be enough?)

>> we might want to support device as a runtime input for factory methods as well?!
>
>This seems to have large implications. Would we need to support, say, a case where inputs were on device 0 and generating >a tensor on device 1, and returning an output on device, where?

The question raised here are not limited to the runtime input `device` args, right?
We might as well have a static time device tag, but still ended up with a graph where tensors could be on different devices. We do need to segment (I think we can do this at integration level) and from there I think we can still keep our codegen to be single device.

**Comment by naoyam** [comment]
If it's done at the integration level, what do you think the codegen side needs to provide?
