### ISSUE TITLE
Validate use of bf16 (and other relatively new hardware features)

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#1760]
(Originally in #1758)

The bf16 type is only supported on sm80 and later. Currently, nvFuser will just fail when we compile a generated kernel with nvrtc. While we do not care too much about pre-A100 generations, we should at least do:

- More informative error messages rather than just nvrtc compilation failure
- Explicitly define the required minimum architecture version

When we lower a `Fusion` to a `Kernel`, we should define the minimum required version. The default should be sm70, i.e., the V100 version. When the `Kernel` has `bf16` vals, it should at least be `sm80`. Other recent architecture features such as memcpy_async and TMA should also set the minimum version accordingly.

This minimum version should then be checked before the `Kernel` is compiled by nvrtc. Now that we have the information about the required minimum version, we should be able to give more helpful information.

**Comment by wujingyue** [comment]
From @naoyam: 

> I initially thought when we create castOp in the Fusion IR, we should just throw an error if a cast op to  bf16 is created on non-supported devices, but maybe that should not be considered a hard error as there should be nothing wrong to generate a kernel that's not supported by a given hardware. It should not be an error until it's compiled and executed.

Thanks for the note. Failing at creation doesn't sound like a bad idea at least :) Given caching the error at the compilation time is more work, what's the practical benefit of doing that? E.g. would we want to build the fusion on one machine (even without a GPU!), serialize it and ship it to a different machine to run?

**Comment by naoyam** [comment]
> Failing at creation doesn't sound like a bad idea at least

Yes.

> E.g. would we want to build the fusion on one machine (even without a GPU!), serialize it and ship it to a different machine to run?

Yes, that kind of things are what I have in mind. Not necessary ATM, but I feel not allowing to create such ops at all is too restrictive.

Another benefit would be we would have a single lowering pass that would do this analysis, so these architecture checks would be placed in a single location with a consistent error message. Generally speaking, when a `Fusion` is lowered to a `Kernel`, we do basic sanity checks like [this](https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/validation.cpp#L176). I think it's natural to have a check here for hardware features as well.
