### ISSUE TITLE
IdModel falsely maps two IterDomains. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1801]
For #1768, I'd like to use IdModel to decide whether two def-use chains manipulate two slices in the same way. Below is a failed attempt. I'm not sure it's a IdModel bug or a wrong usage so PTAL. 

```
git fetch origin wjy/map
git checkout wjy/map
_bn && bin/nvfuser_tests --gtest_filter=IdModelTest*PermutedDifferently
```

For #1768, I don't expect t0's first axis and t1's first axis mapped, because t0 and t1 apply different permutations on the slices: https://github.com/NVIDIA/Fuser/blob/wjy/map/test/test_id_model.cpp#L954-L955. However, they are mapped apparently because of the `cat` operation and therefore triggered [this error](https://github.com/NVIDIA/Fuser/blob/wjy/map/test/test_id_model.cpp#L981-L982).

**Comment by zasdfgbnm** [comment]
Looks like this is a fancier version of `x + x.transpose()`

**Comment by wujingyue** [comment]
Closing this as a WAI.
