### ISSUE TITLE
Skip compiling fusion segments that are marked for EE

### ISSUE THREAD

**Issue by Priya2698** [NVIDIA/Fuser#1812]
PR #1743 ran into errors in `GpuLower::analysis`. In the short term, the workaround is to skip Mma specific validation in `analysis`.

Ideally if intend to use the EE, then we should not be compiling a fusion / ~launching a kernel~ (already skipped after #1723) . This will require us to modify some downstream calls and `FusionExecutor` interface to integrate using EE alongside nvFuser kernels seamlessly. 

CC: @jacobhinkle @wujingyue

**Comment by wujingyue** [comment]
(Nit: I modified the title to focus on the problem not a solution. There could be other valid solutions -- I don't want to discount them immediately)

**Comment by wujingyue** [comment]
FYI, kernel launching is already skipped after https://github.com/NVIDIA/Fuser/pull/1723. It's the unnecessary compilation that we want to avoid here.
