### ISSUE TITLE
ReplayTransformations don't set isRFactorProduct correctly. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1857]
E.g. https://github.com/NVIDIA/Fuser/blob/71d9b555b401655c0d664b94e8abb7021ce29637/csrc/transform_iter.cpp#L53-L54 uses the default `rfactor_domain=false`. I guess this has been fine for now because we only use it to replay leaf transformations. However, this caused my pending https://github.com/NVIDIA/Fuser/pull/1846 to fail when replaying a pointwise unary op. 

I added a reproducer in #1846. The error message is
```
C++ exception with description "id_a->definition() == nullptr || id_a->isRFactorProduct() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/root_domain_map.cpp":546, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Non-root domain is not supported: iS37{2}
```

Apparently, when scheduling a pointwise kernel, ComputeAtMap relies on isRFactorProduct to skip mapping certain IterDomains.

**Comment by jacobhinkle** [comment]
Oh yeah I meant to experiment with removing that flag but I forgot. Will have a look soon

**Comment by naoyam** [comment]
Here's one example usage of the flag: https://github.com/NVIDIA/Fuser/blob/main/csrc/transform_iter.cpp#L504-L511

IIRC, It isn't strictly required but for optimization. We can recover the same information by traversing from the corresponding root domains to the rfactor domains.

**Comment by naoyam** [comment]
> Any root-to-rfactor transform must have rf input IterDomains and rf output IterDomains.

Yes.

> A root IterDomain must have rf if its corresponding producer IterDomain (in one of the input TensorViews) has rf.

I don't think so? Do you have an example?

**Comment by wujingyue** [comment]
> I don't think so? Do you have an example?

I think you are right. I got that wrong impression from https://github.com/NVIDIA/Fuser/pull/1846#discussion_r1506772900. With hindsight, the rf flags are likely due to rfactor transforms within that TensorView instead of the input.
