### ISSUE TITLE
Consolidate Test and Benchmark Directories.

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#1926]
We have test and benchmark directories that are separate for python and C++ it would be good to have one set of organized directories for each.

```
tests/cpp <--- test
tests/cpp/python_frontend <--- csrc/python_frontend/test
tests/cpp/kernel_db <--- csrc/kernel_db/test
tests/python <--- python_tests
benchmarks/cpp <--- benchmark
benchmarks/python <--- python_benchmarks
```

**Comment by ashishpetwal** [comment]
I think we will be reconstructing it like this:

**Tests**: Merge tests/cpp and tests/python into tests, maintaining subdirectories for language-specific tests:

**Benchmarks**: Similarly, merge benchmarks/cpp and benchmarks/python into benchmarks, again keeping language-specific subdirectories.

if it is fine, I can take on this issue.

**Comment by kevinstephano** [comment]
> I think we will be reconstructing it like this:
> 
> **Tests**: Merge tests/cpp and tests/python into tests, maintaining subdirectories for language-specific tests:
> 
> **Benchmarks**: Similarly, merge benchmarks/cpp and benchmarks/python into benchmarks, again keeping language-specific subdirectories.
> 
> if it is fine, I can take on this issue.

I did not see this comment in a timely fashion, I already addressed the issue with PR #1944.

**Comment by ashishpetwal** [comment]
Sure, I got it.

**Comment by kevinstephano** [comment]
PR #1944 was merged.  Closing!
