### ISSUE TITLE
DisableOption::MatmulExprEval not respected with parallel compile

### ISSUE THREAD

**Issue by cowanmeg** [NVIDIA/Fuser#1986]
The matmul expression evaluator pathway is incorrectly used when `DisableOption::MatmulExprEval)` is set. I noticed this is only triggered when there are multiple kernels in the fusion.

If `DisableOption::ParallelCompile` is set, then matmul expression evaluator is properly not used. 
It looks like the error occurs in `FusionKernelRuntime::compileFusionParallel` at this else branch. Maybe it could be solved by having each parallel compile thread launched re-read the options?
https://github.com/NVIDIA/Fuser/blob/8226e61a2a843e8e4ad8c6c2801b019f654828d1/csrc/kernel_cache.cpp#L1275 

cc'ing @protonu

**Comment by protonu** [comment]
Thanks for pointing this out. I had a draft PR for this (https://github.com/NVIDIA/Fuser/pull/1969). I'll wrap it up soon.

**Comment by jacobhinkle** [comment]
Let's revert https://github.com/NVIDIA/Fuser/pull/1913 for the time being.
