### ISSUE TITLE
Matmul NN support

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#203]
# The purpose of this issue

The purpose of this issue is to communicate about the planned change on nvFuser I'd like to make to enable matmul NN support. The entire change would take multiple PRs, and this issue is to provide a big picture and help understand the motivation of these PRs. Another purpose is to review the design early.

# The challenge

## NN support

The challenge about NN is not "how to schedule an NN matmul", but instead "how to define an NN matmul". Currently, `MmaOp` can be considered as a fused multiply-sum, and the entire matmul is defined as broadcasts followed by `MmaOp`:
<img src="https://user-images.githubusercontent.com/1032377/233734940-7e7d2c2f-448c-4f0d-9153-4ea7e497e657.png" width="250"/>

The currently supported layouts are TT, TN, NT:
- For TT, the input shapes are `[M, K]` and `[K, N]`, we broadcast inputs into `[M, K, 1]` and `[1, K, N]`, after multiplication, we have `[M, K, N]`, and after reduction, we get `[M, N]`. 
- For TN, the input shapes are `[M, K]` and `[N, K]`, we broadcast inputs into `[M, 1, K]` and `[1, N, K]`, after multiplication, we have `[M, N, K]`, and after reduction, we get `[M, N]`.
- For NT, the input shapes are `[K, M]` and `[K, N]`, we broadcast inputs into `[K, M, 1]` and `[K, 1, N]`, after multiplication, we have `[K, M, N]`, and after reduction, we get `[M, N]`.

But for NN, the input shapes are `[K, M]` and `[N, K]`, there is no such way to get an output of `[M, N]`. It is only possible to get `[N, M]`. In order to support NN, there must be changes in fusion definition.

## Forward compatibility

Our design should be compatible with our future needs, although these needs might not be our priority today. Below are some examples that I think is related to this topic:

1. **Matmul-transpose fusion**: For example, `(A.T @ B).T`. We should allow users to insert transposes anywhere in the fusion definition, and nvFuser should be able to find the correct layout for matmul with these transposes taken into consideration.
2. **Transpose support in other schedulers**: Currently, transpose is supported in a separate scheduler. This is not optimal. We should handle transpose and generate optimal code for all schedulers.
3. **View support in other schedulers**: Similar to above, currently, we are only supporting specific patterns of view. Any infrastructure change that could potentially be useful to more complete view support is welcome.

# Principles

## Easiness to define a fusion

From the user(the person who creates a fusion)'s  perspective, fusion definitions should be as flexible as possible. Users shouldn't worry about performance when defining a fusion. The only thing a user should be worrying about is mathematical correctness. The matmul scheduler should accept all mathematically equivalent fusions and schedule all of them optimally. It is an unacceptable experience if the user need to think about things like below when defining the fusion:
> I want to do an Ampere matmul, Ampere has an ldmatrix.trans instruction that allows transpose in the smem to register load, and the mma op is always TN, so I will transpose the inputs to [M, K] and [N, K] first, and then do mma.

Instead, for example, for the `[M, K] @ [K, N] -> [M, N]` matmul, users should be able to define the fusion whatever way is most convenient to the user, options include:
![Screenshot_20230421_184052](https://user-images.githubusercontent.com/1032377/233755265-327d2a41-bb6c-4a84-8e63-32b6aaec7576.png)

## Easiness of lowering

For lowering to be easy, the fusion definition should be as close to the hardware as possible. However, different architecture has different matmul flavor, so there is no single "canonical form" that is close to all hardware.

On Volta, matrices are loaded to register in the same layout as inputs, and the mma op has TT, TN, NT, NN variants. So on Volta, the matmul definition closest to hardware is
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1032377/234374182-78cf028b-7fde-4b51-bdbb-54854d6b0d6c.png">

On Turing & Ampere, in shared memory, the layout of the matrices is the same as inputs. However, when shared memory matrices is loaded into register (using `ldmatrix`/`ldmatrix.trans`), the layouts of the matrices always become TN, and there is only one variant of mma which is TN. So on Turing & Ampere, the matmul definition closest to hardware is
![Screenshot_20230421_160350](https://user-images.githubusercontent.com/1032377/233746764-60c903eb-934d-41a3-a1c5-0d5ba4e18325.png)

On hopper, there are two variants of `wgmma`: the "rs" variant whose first operand is on register and the second operand is on shared memory, and the "ss" variant whose both operands are on shared memory. For the "rs" variant, the first operand must be `[M, K]`, the second variant can be either `[N,K]` or `[K,N]`. For the "ss" variant, its first operand can be `[M, K]` or `[K, M]`, and its second variant can be `[N,K]` or `[K,N]`. So the the matmul definition closest to hardware is:
![Screenshot_20230421_162027](https://user-images.githubusercontent.com/1032377/233748037-412b01f8-7686-4e63-9a10-65d5a87e1fb8.png)
![Screenshot_20230421_162255](https://user-images.githubusercontent.com/1032377/233748221-a788da90-03a7-4142-9bb9-2d0ac0ec2032.png)

# Design

As described in the last section, the principles of easiness to define a fusion and easiness of lowering would lead to different fusion definitions. For a given hardware, the "easiness of lowering" form is the canonical form that the scheduler needs to transform the fusion into. In order to be able to define the canonical form and transform to the canonical form, the following concepts will be added/changed for nvFuser:

## Implicit transpose/view/broadcast/squeeze

`Implicit transpose` is a transpose that happens in the rFactor domain of a tensor whose definition is not a `TransposeOp`. Starting from https://github.com/NVIDIA/Fuser/pull/148, all transposes are implicit (because we no longer have a `TransposeOp`), but we are only practicing implicit transpose tensors defined by `LoadStoreOp`. In order to define canonical forms of mma op, we would need to make the output tensor of `MmaOp` implicitly transposed as well.

I would like to go farther:
- I would like to do not just implicit transpose, but also implicit view, broadcast, and squeeze.
- I would like to enable implicit transpose/view/broadcast/squeeze not only on `MmaOp`'s output, but on all tensors.

For example, if I have `T1 = sin(T0)` where `T0` has shape `[I0, 1, I1, I2]`, and `T1` has
```
root domain: [I0, 1, I1, I2]
rFactor domain: [I2, I0*I1, 1] 
```
Then the output `T1`'s shape will be `[I2, I0*I1, 1]`. That is, T1 does an implicit squeeze-view-transpose-broadcast.

The reason for doing so is because:
- When indexing, we only care about how `IterDomain`s are transformed, we don't really care whether the tensor is defined by `LoadStoreOp` or `UnaryOpType::ReLU`. I believe this new approach can free up more flexibility without adding too much complexity to our existing system. Instead, I think our system will have in total less lines of code because we can just define many of these ops as `LoadStoreOp`, instead of each has its separate `Expr` subclass.
- `BroadcastOp`, `SqueezeOp`, `ViewOp`, `TransposeOp`, etc. is essentially just a data copying operation with fancy indexing. In the generated C++ code, I am not a fan of reading things like
  ```C++
  T1[i1] = T0[i0];
  T2[i2] = sin(T1[i1]);
  ```
  I prefer to read just `T2[i2] = sin(T0[i0])`. So I want to reduce redundant copies in generated C++. For the case of matmul, I would like to have a single `ldmatrix.trans` that does transpose+broadcast together, so that I don't have to deal with this extra broadcast.

## Forward and backward push of the rFactor domain

I would like to add two methods to `TensorView`: `pushRFactorForward` and `pushRFactorBackward`.

Assume we have the following fusion: `T0 --set--> T1 --set--> T2` where
```
T0: root = [I0, I1], no rfactor
T1: root = [I0, I1], rfactor = [I1, I0]
T2: root = [I1, I0], no rfactor
```
Then `pushRFactorForward` will transform the fusion as
```
T0: root = [I0, I1], no rfactor
T1: root = [I0, I1], no rfactor
T2: root = [I0, I1], rfactor = [I1, I0]
```
And `pushRFactorBackward` will transform the fusion as
```
T0: root = [I0, I1], rfactor = [I1, I0]
T1: root = [I1, I0], no rfactor
T2: root = [I1, I0], no rfactor
```

It is possible to specify intermediate state to only push part of the transformations. For example, if the fusion has `T0--view-->T1--sin-->T2` and
```
T0: root = [I0, I1, I2], no rfactor
T1: root = [I0, I1, I2], rfactor = [I1*I0/4, 4, I2]
T2: root = [I1*I0/4, 4, I2], no rfactor
```
Then `pushRFactorBackward([I1*I0, I2])` will get
```
T0: root = [I0, I1, I2], rfactor = [I1*I0, I2]
T1: root = [I1*I0, I2], rfactor = [I1*I0/4, 4, I2]
T2: root = [I1*I0/4, 4, I2], no rfactor
```
Note that for this case, `T0` might have implicit view, that is, a view that happens implicitly at some op that is not a `ViewOp`. And `pushRFactorForward([I1*I0, I2])` will get
```
T0: root = [I0, I1, I2], no rfactor
T1: root = [I0, I1, I2], rfactor = [I1*I0, I2]
T2: root = [I1*I0, I2], rfactor = [I1*I0/4, 4, I2]
```
Note that for this case, `T2` will be have implicit view.

If the current tensor has more than one producers, then a backward push will push its rfactor domain to all its producers. Similarly, if the current tensor has multiple consumers, then a forward push will push it to all its consumers. More complicated, if `c = op(a, b)`, then `a->pushRFactorForward()` will modify both `b` and `c`. Similar for the case of  `pushRFactorBackward` to a tensor with multiple uses.

Not all pushes are valid. A push must be compatible with the current schedule. For example, if you have `T0->T1` where
```
T0: root = [I0, I1, I2], no rfactor, leaf = [I0, I1*I2]
T1: root = [I0, I1, I2], rfactor = [I0*I1, I2], leaf = [I0*I1, I2]
```
Then `T1->pushRFactorBackward()` is illegal. However, if
```
T0: root = [I0, I1, I2], no rfactor, leaf = [(I0*I1)*I2]
T1: root = [I0, I1, I2], rfactor = [I0*I1, I2], leaf = [I0*I1, I2]
```
Then `T1->pushRFactorBackward()` will get
```
T0: root = [I0, I1, I2], rfactor = [I0*I1, I2], leaf = [(I0*I1)*I2]
T1: root = [I0*I1, I2], no rfactor, leaf = [I0*I1, I2]
```

There may be other types of invalid push, but discussing this is not in the scope of this issue.

The goal of these two methods is to make the manipulation of `rFactor` domains super easy. I believe in the long term, this added functionality would be helpful for `view` and `resize` scheduling. For the case of matmul, these two methods should make it easy to canonicalize user's input into hardware flavor. For example, the following transformation can be used to schedule an NN matmul for Ampere:

![Screenshot_20230421_190334](https://user-images.githubusercontent.com/1032377/233756191-afad6997-d25f-4568-aa8a-d0bbc8587507.png)

## MmaOp vs Mul-Sum

`MmaOp` and `Mul->Sum` are two mathematically equivalent way to define matmul. I prefer to define the fusion as `Mul->Sum` in user-facing API, and let the scheduler to convert it to `MmaOp` and fill in informations.
```[tasklist]
- [ ] https://github.com/NVIDIA/Fuser/pull/234
```

**Comment by zasdfgbnm** [comment]
Calling review @naoyam @drzejan2 @mmigdal-nv

**Comment by naoyam** [comment]
> View support in other schedulers: Similar to above, currently, we are only supporting specific patterns of view. Any infrastructure change that could potentially be useful to more complete view support is welcome.

What patterns are you thinking about?

**Comment by zasdfgbnm** [comment]
> What patterns are you thinking about?

I am not thinking about a specific pattern. I am not thinking about things like "this approach can be used to support this pattern of view that is not previously supported". I am just feeling that being able to conveniently move view around is a good capability to have. If we have incompatible views that is hard to schedule in one kernel, segmentation is needed. And this capability will allow us to adjust where to segment.

**Comment by zasdfgbnm** [comment]
And also for resize, we can move the shrinking resize from the the output of a fusion to inputs of a fusion, this way, we will load and compute less data.

**Comment by kevinstephano** [comment]
I like having a consistent API to define matmul like `Mul->Sum` and then have a the scheduler translate it to MMA ops in order to keep a separation between the definition and schedule.  Are there any drawbacks to the `Mul->Sum` API that makes you question changing it?

**Comment by kevinstephano** [comment]
> > Are there any drawbacks to the `Mul->Sum` API that makes you question changing it?
> 
> Not sure if I am understanding your question correctly. But I am not suggesting to change from `Mul->Sum` to something else. Instead, today, users are not creating `Mul->Sum`, they are creating `MmaOp`. And this proposal is suggesting changing to let user creates `Mul->Sum`.

Thanks for the clarification!  I did not realize that users were bypassing the `Mul->Sum` API and using the `MmaOp`.

**Comment by zasdfgbnm** [comment]
> By squeeze you meant there merge of iterdomains or some operations?

I meant https://pytorch.org/docs/stable/generated/torch.squeeze.html

**Comment by naoyam** [comment]
> In the last case of the Volta matmul, shouldn't there be a transpose of `b`?
> 
> https://user-images.githubusercontent.com/1032377/233745629-c01ae809-f117-4422-8ec8-e977bdb71cdc.png

Or, maybe there should be no explicit transpose, but it's done by the `mmaop`, so the input to the op should be `[N, K, 1]`?

**Comment by zasdfgbnm** [comment]
> Or, maybe there should be no explicit transpose, but it's done by the `mmaop`, so the input to the op should be `[N, K, 1]`?

Your understanding is write. I completely draw it wrong. Updated the figure.

**Comment by naoyam** [comment]
> > Or, maybe there should be no explicit transpose, but it's done by the `mmaop`, so the input to the op should be `[N, K, 1]`?
> 
> Your understanding is right. I completely draw it wrong. Updated the figure.

I haven't read through the rest of the doc, but what the root domain of the mmaop output should look like then? The two inputs have the different rfactor domains. Maybe this is another reason we should decompose mmaop?

**Comment by naoyam** [comment]
> For example, if I have T1 = sin(T0) where T0 has shape [I0, 1, I1, I2], and T1 has
> 
> root domain: [I0, 1, I1, I2]
> rFactor domain: [I2, I0*I1, 1] 

How do you define `T1` as such?

**Comment by zasdfgbnm** [comment]
> > > Or, maybe there should be no explicit transpose, but it's done by the `mmaop`, so the input to the op should be `[N, K, 1]`?
> > 
> > 
> > Your understanding is right. I completely draw it wrong. Updated the figure.
> 
> I haven't read through the rest of the doc, but what the root domain of the mmaop output should look like then? The two inputs have the different rfactor domains. Maybe this is another reason we should decompose mmaop?

They actually has matching rfactor domains. In my original drawing, I made it wrong on both of the mma inputs. They should be: `[1, K, M]` and `[N, K, 1]`.

**Comment by zasdfgbnm** [comment]
> How do you define `T1` as such?

I think I will just do:
```
root domain: [I0rf, b0, I1rf, I2]
rFactor domain: [I2, I3rf, b1]
```
where `b0` only exist in root domain, it does not exist in rFactor domain. `b1` only exist in rFactor domain, it does not exist in root domain. And `I3rf = merge(I0rf, I1rf)`.

**Comment by naoyam** [comment]
> > How do you define `T1` as such?
> 
> I think I will just do:
> 
> ```
> root domain: [I0rf, b0, I1rf, I2]
> rFactor domain: [I2, I3rf, b1]
> ```
> 
> where `b0` only exist in root domain, it does not exist in rFactor domain. `b1` only exist in rFactor domain, it does not exist in root domain. And `I3rf = merge(I0rf, I1rf)`.

How does the user define the transformation from the root to the rfactor domain?

**Comment by zasdfgbnm** [comment]
> How does the user define the transformation from the root to the rfactor domain?

Are you talking about interface? I don't have a concrete idea on how it will look like. Below is a possible design:

Suppose that we have `tv0->tv1->tv2`.

Assume:
- `tv1` is not scheduled yet

Beginning:
```
T1:
root domain: [I0, b0, I1, I2]
T2:
root domain: [I0, b0, I1, I2]
```

`tv1->squeezeRFactor(1)`:
```
T1:
root domain: [I0, b0, I1, I2]
rFactor domain: [I0, I1, I2]
T2:
root domain: [I0, I1, I2]
rFactor domain: [I0, b0, I1, I2]
```

`tv1->mergeRFactor(0)`:
```
T1:
root domain: [I0rf, b0, I1rf, I2]
rFactor domain: [I3rf, I2]
T2:
root domain: [I3rf, I2]
I0rf, I1rf = split(I3rf, I1->extent())
rFactor domain: [I0rf, b0, I1rf, I2]
```

`tv1->broadcastRFactor({false, false, true})`:
```
T1:
root domain: [I0rf, b0, I1rf, I2]
rFactor domain: [I3rf, I2, b1]
T2:
root domain: [I3rf, I2, b1]
I0rf, I1rf = split(I3rf, I0->extent())
rFactor domain: [I0rf, b0, I1rf, I2]
```

`tv1->reorderRFactor({{0, 1}, {1, 0}})`:
```
T1:
root domain: [I0rf, b0, I1rf, I2]
rfactor domain: [I2, I3rf, b1]
T2:
root domain: [I2, I3rf, b1]
I0rf, I1rf = split(I3rf, I0->extent())
rFactor domain: [I0rf, b0, I1rf, I2]
```

The assumption should be asserted. And this implies that the schedulers should always schedule rFactor domain before scheduling leaf domain. It is also recommended but not required that if a user want to define a fusion with implicit transpose/view/broadcast/squeeze, he/she should define the tensors with such implicit transformations before defining their consumers.

**Comment by zasdfgbnm** [comment]
> How does the user define the transformation from the root to the rfactor domain?

Most likely, a user won't want to define directly such operation by hand. A more likely to happen case `analyzeView` define such operation. If this is the case, the it is guaranteed that `tv1` has no consumer, and `analyzeView` can just create the output tensor without using any interface above.

**Comment by naoyam** [comment]
Looks like the existing expressions like `squeeze` are effectively replaced with the new expressions that update tensor IterDomains. And by doing so, we could avoid defining new tensors. 

I guess this could be described as moving the responsibility of some ops from the tensor level to the domain level.

As for the interface, it seems to me the current interface is simpler and easier to understand. 

Maybe we could keep the current interface, but once a fusion is defined by a user, we could "shrink" it by aggregating, e.g., squeeze and transpose to just a single op with the corresponding rfactor ops. But then why would we want to do this aside from the look of the final generated code?

**Comment by naoyam** [comment]
> MmaOp and Mul->Sum are two mathematically equivalent way to define matmul. I prefer to define the fusion as Mul->Sum in user-facing API, and let the scheduler to convert it to MmaOp and fill in informations.

Sounds good to me. IIRC, we added `MmaOp` just to trigger the matmul scheduler with scheduling options. That was convenient for the initial build out, but it should eventually be retired.

**Comment by zasdfgbnm** [comment]
> I guess this could be described as moving the responsibility of some ops from the tensor level to the domain level.

Yes, exactly.

> As for the interface, it seems to me the current interface is simpler and easier to understand.

I agree. I would still expect users to define view using the `view` in `alias.cpp`, rather than manually operate on rFactor domains. Right now, the `view` in `alias.cpp` will create a sequence of `squeeze-view-broadcast`, but I think we can make it create a single `LoadStoreOp` which is simpler.

> Maybe we could keep the current interface, but once a fusion is defined by a user, we could "shrink" it by aggregating, e.g., squeeze and transpose to just a single op with the corresponding rfactor ops.

I agree.

> But then why would we want to do this aside from the look of the final generated code?

I think the motivation is the following:

1. In order to be able to provide the flexibility for user to define matmul, and for matmul-transpose fusion, we should have `pushRFactorForward` and `pushRFactorBackward`.
2. In order for `pushRFactorForward` and `pushRFactorBackward` to work with broadcast/squeeze/view/resize for an arbitrary DAG, the most convenient way is to generally enable implicit transpose/view/broadcast/squeeze for all TVs.
3. After enabling implicit transpose/view/broadcast/squeeze for all TVs, we could aggregate broadcast/squeeze/view/resize into some tv to make the generated code look better with very little effort, so why not?

**Comment by zasdfgbnm** [comment]
> Sounds good to me. IIRC, we added `MmaOp` just to trigger the matmul scheduler with scheduling options. That was convenient for the initial build out, but it should eventually be retired.

Yes, agree. I would consider `MmaOp` as something like `kir::GridReduction`, `kir::GridWelford`, `kir::GroupedGridReduction`, etc.

**Comment by naoyam** [comment]
I finally understand what the final diagram is showing.

It seems these transformations can be done by the scheduler. Is that what you're thinking about? Do we really need the `pushRfactor` operations? Could it be done also by using the existing tensor ops?

**Comment by naoyam** [comment]
I think there are two relatively-separate topics here. 

1. The equivalent transformation of fusions by moving rfactor ops. I think this could be done with the current tensor-based ops.
2. Removal of the explicit tensor ops where rfactor ops can be used instead. 

For the user-facing interface, we agreed that we should keep the current design. So, we should not completely remove the existing ops. This would also mean that the transformation should be done by the scheduler. Is replacing tensor ops with domain ops make our life easier? I don't know, but for that I'd trust you.

**Comment by zasdfgbnm** [comment]
> For the user-facing interface, we agreed that we should keep the current design. So, we should not completely remove the existing ops.

Could you elaborate more on this? I think we have three options. For example, we want to define `view(sin(T0), {3, 1, 4}, {12, 1})`, and we have the following three options:

**Option 1**: Same as nvFuser today:
```
T1 = sin(T0);
T2 = squeeze(T1);
T3 = view(T2);
T4 = broadcast(T3);
```

**Option2**:
```
T1 = sin(T0);
T2 = set(T1);
// T2's rFactor domain does the job of squeeze+view+broadcast
```

**Option3**:
```
T1 = sin(T0);
// T1's rFactor domain does the job of squeeze+view+broadcast
```

In terms of user friendness, option 1 and option 2 are the same. I think we agreed on option 2, am I understanding correctly?

> This would also mean that the transformation should be done by the scheduler.

This I agree. User shouldn't see any difference in defining view/broadcast/squeeze, and the user should feel it becomes easier to define matmul.

> Is replacing tensor ops with domain ops make our life easier? I don't know, but for that I'd trust you.

My evaluation is based on transpose. After refactoring transpose as a domain op, the lines of code is reduced.

**Comment by naoyam** [comment]
> Could you elaborate more on this? I think we have three options. For example, we want to define `view(sin(T0), {3, 1, 4}, {12, 1})`, and we have the following three options:

I'm referring to the user interface, which is, as you wrote, just `view(sig(T0) {3, 1, 4}, {12, 1})`, or it's now possible to do `view(sig(T0), {IrBuilder::create<Int>(), IrBuilder::create<Int>()})`.

> My evaluation is based on transpose. After refactoring transpose as a domain op, the lines of code is reduced.

True, but shorter lines of code doesn't necessarily translate to code that's easier to maintain and understand. Sometimes explicit representations with more code may be preferred. I don't think there's no definite answer here as it's a matter of subjective balance.

**Comment by zasdfgbnm** [comment]
> I'm referring to the user interface, ...

Yeah, both option 1 and option 2 will have the same interface. I will pick option 2.

> True, but shorter lines of code doesn't necessarily translate to code that's easier to maintain and understand. Sometimes explicit representations with more code may be preferred. I don't think there's no definite answer here as it's a matter of subjective balance.

Yeah, I also agree. I will know which is preferred as I am building this out. For the transpose case, it is clear to me that domain op is better than tensor op. For view/squeeze/broadcast, I don't know yet.

**Comment by zasdfgbnm** [comment]
NN has been supported. The design for matmul-transpose fusion here is obsolete after the introduction of allocation domain.
