### ISSUE TITLE
Add Thunder `compile_options` for enabling `linear` and `matmul` separately at the Framework level

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#2053]
[There is an example ](https://github.com/Lightning-AI/lightning-thunder/blob/393828fa1dd45b3a9ff695f1bdbf005f5a669e5e/thunder/executors/nvfuserex_impl.py#L799)of an option `nv_enable_bookend` that can be used to create two new options, one each for `matmul` and `linear` enablement in the nvFuser executor.

**Comment by kevinstephano** [comment]
Priya has put up a draft PR on Thunder: https://github.com/Lightning-AI/lightning-thunder/pull/207

**Comment by Priya2698** [comment]
The following PRs added the compile options in Thunder
1. https://github.com/Lightning-AI/lightning-thunder/pull/207 
2. https://github.com/Lightning-AI/lightning-thunder/pull/318
