### ISSUE TITLE
Implement `ops.linear` Primitive

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#2057]
[Could we enumerate how this gets plumbed from Interface to IR]

We are working on plumbing down a call to linear from Python to our backends. For now, the default execution will rely on the aten linear implementation via our expression evaluator. This work is in the spirit as the implementation of the mamtul API in Python.

Linear[@Priya2698's PR in flight: https://github.com/NVIDIA/Fuser/pull/2050 ]

Issues to discuss:
1. Our logic for dispatching to at::matmul, admm, or linear could be (filled in by Priya below):

at::linear -> If the detected shape is [M,K] x [N, K].
at::addmm -> If the detected shape is [M,K] x [N, K] and bias != nullptr
at::matmul -> If the detected shape is [M,K] x [N, K] and bias == nullptr

I also agree with this. It should be able to cover the cases:
A. We call ops.matmul 
B. We call ops.linear (with 2 or 3 operands)
C. User creates a fusedMultiplySum followed by bias (admm).

2. The next question is how do we detect shape.  Priya mentioned:
While pattern matching, we look at the shapes of the unbroadcasted inputs to the MmaOp.

@jacobhinkle  also mentioned using getProblemIterDomains (https://github.com/NVIDIA/Fuser/blob/52692ed5347dc308b93a7f35acdf2c4123c10c1f/csrc/scheduler/mma_utils.cpp#L1056-L1089) to achieve this. I was also leaning towards this approach, and I was wondering if we can just call getMmaLayout (https://github.com/NVIDIA/Fuser/blob/52692ed5347dc308b93a7f35acdf2c4123c10c1f/csrc/scheduler/mma_utils.cpp#L1056-L1089) to get the shapes on the inputs. Thought the function name mentions layout, it's very much just the logical shapes of the tensors.

3. Segmentation doesn't work properly when the bias is of dimension {n} as is the case for linear.
This is probably solved. @jjsjann123  noticed this code:
(https://github.com/NVIDIA/Fuser/blob/618c4b79a053692bf83ebb32aa19dcc907ebb534/csrc/scheduler/mma_utils.cpp#L1239C1-L1247C8). It should be modified to just `!has_k`

**Comment by kevinstephano** [comment]
Issues we need to sort out:
1. How do we detect the input shapes of Matrices A and B?
2. Based on the shapes of A and B how do we differentiate between: `at::linear`, `at::addmm`, and `at::matmul`
3. We will run into an issue with segmentation where it will segment because it sees "matmul + bias".  We want this to be executed without segmentation.

**Comment by kevinstephano** [comment]
Based on these three questions.  @protonu is going to list the set of possible solutions and his preferences if he has one.

**Comment by Priya2698** [comment]
> 1. How do we detect the input shapes of Matrices A and B?

While pattern matching, we look at the shapes of the unbroadcasted inputs to the `MmaOp`. 
> 2. Based on the shapes of A and B how do we differentiate between: `at::linear`, `at::addmm`, and `at::matmul`

`at::linear` -> If the detected shape is [M,K] x [N, K].
`at::addmm` ->  If the detected shape is [M,K] x [N, K] and `bias != nullptr`
`at::matmul` -> If the detected shape is [M,K] x [N, K] and `bias == nullptr`

**Comment by Priya2698** [comment]
> ) to achieve this. I was also leaning towards this approach, and I was wondering if we can just call getMmaLayout (
> https://github.com/NVIDIA/Fuser/blob/52692ed5347dc308b93a7f35acdf2c4123c10c1f/csrc/scheduler/mma_utils.cpp#L1056-L1089
> 
> ) to get the shapes on the inputs. Thought the function name mentions layout, it's very much just the logical shapes of the tensors.

This does not work if the fusion input is transposed before calling matmul/linear. It gets the shape of the fusion inputs rather than the inputs post transpose. See test: https://github.com/NVIDIA/Fuser/blob/618c4b79a053692bf83ebb32aa19dcc907ebb534/tests/cpp/test_matmul_aten_evaluation.cpp#L71.

Here `getMmaLayout(fusion)` gives `MmaLayout::TN` based on the original inputs, whereas the code expects `MmaLayout::TT`. My WAR is to look at the bcast dimension of the first operand (last axes for matmul, middle axes for linear). Both these functions are using `mma->inA()/inB()/out()` to determine the ordering.

**Comment by Priya2698** [comment]
> 3. Segmentation doesn't work properly when the bias is of dimension {n} as is the case for linear.
>    This is probably solved. @jjsjann123  noticed this code:
>    (https://github.com/NVIDIA/Fuser/blob/618c4b79a053692bf83ebb32aa19dcc907ebb534/csrc/scheduler/mma_utils.cpp#L1239C1-L1247C8). It should be modified to just `!has_k`

Adding the fix to PR #2050 to run the Linear + Bias test.

**Comment by protonu** [comment]
>Here getMmaLayout(fusion) gives MmaLayout::TN based on the original inputs, whereas the code expects MmaLayout::TT. My WAR is to look at the bcast dimension of the first operand (last axes for matmul, middle axes for linear). Both these functions are using mma->inA()/inB()/out() to determine the ordering.

This sounds good to me. @jacobhinkle @jjsjann123 do you see something that might be overlooked with this?

**Comment by protonu** [comment]
If users decided to write something like:

b_t = fd.ops.transpose(b)
c = fd.op.matmul(a, b_t)

We should be invoking at::matmul in this case right (Assuming transposed b in {k, n})?

**Comment by Priya2698** [comment]
> If users decided to write something like:
> 
> b_t = fd.ops.transpose(b) c = fd.op.matmul(a, b_t)
> 
> We should be invoking at::matmul in this case right (Assuming transposed b in {k, n})?

That is what I am going with for the implementation, that is, trying to infer the shapes passed and hence the API used.

**Comment by kevinstephano** [comment]
Just waiting on a PR from Protonu.

**Comment by protonu** [comment]
PR: #2090

**Comment by kevinstephano** [comment]
What's left to land PR:
- Works on only 2-D of A and B and 1-D for bias.  Pytorch's A can have anything greater than 1D.  Pytorch's B can only 2D.  Pytorch's can be anything less than or equal to A.  Bias should match N-dimension and be 1-D.  [Here is the link to the Thunder Proxy for linear that has checks.](https://github.com/Lightning-AI/lightning-thunder/blob/649c3d71de9af13a3247694a4e23289221d0ff72/thunder/core/prims.py#L3251)
