### ISSUE TITLE
Investigate adding IR Nodes for `linear` and `matmul`

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#2149]
It was noticed that there is a lot of complexity in pattern matching operations and determining if the set of pattern matched nodes equal a `linear` operation or `matmul` operation prior to asking Expression Evaluator to process the operation.  Therefore, one idea to explore is to add IR nodes for the operations and decompose them later when they specifically come from `ops.linear` and `ops.matmul`.

**Comment by Priya2698** [comment]
PR #2240, #2209 and #2175 add the new IR nodes.
