### ISSUE TITLE
All checks were reported to have passed but some failed. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#2156]
This happened to https://github.com/NVIDIA/Fuser/pull/2126. 

![The conversation page](https://github.com/NVIDIA/Fuser/assets/2772612/dfa41247-fcad-4831-93c5-4eeaeb4ef81a) shows all checks have passed, but when I clicked into [`nvfuser-ci`](https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/pipelines/14551817), one test is found to be broken.

**Comment by wujingyue** [comment]
That test apparently ran out of time (https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/90702153), so this might be a test infra issue not the PR's. Still, I'd expect the error to be propagated to the PR page.

**Comment by xwang233** [comment]
Thanks for the report. This was just fixed in the internal CI infrastructure.
