### ISSUE TITLE
group norm segmented into pointwise + persistent + pointwise

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#2375]
Group norm is calculated as:
```
x0 = [N, C, H, W]
x1 = x0.cast(fp32).reshape(N, C, H, W)  --> (N, G, C/G, H, W) 
x2 = x1 / x1.sum(C/G, H, W)
x3 = x2.reshape(N, G, C/G, H, W) --> (N, C, H, W)
x4 = w*x3 + b
```
Due to the two reshapes, normalization scheduler rejects the unsegmented fusion and then it is segmented into three sub-fusions:
(1) pointwise doing `cast + reshape`
(2) normalization
(3) pointwise doing `reshape + scale & bias`

Reproduce (modified from [apex group norm implementation](https://github.com/NVIDIA/apex/blob/master/apex/contrib/group_norm/group_norm.py) and  [apex group norm test](https://github.com/NVIDIA/apex/blob/7b73b12361068a10b0f44844534613f252a5ea75/apex/contrib/test/group_norm/test_group_norm.py#L38) ):
```
import torch
import thunder

def torch_group_norm(x, g, w, b, eps, act=""):
    xdtype, wdtype = x.dtype, w.dtype
    if xdtype != wdtype:
        x = x.to(dtype=wdtype)
    y = torch.nn.functional.group_norm(x, g, w, b, eps)
    if act in ["silu", "swish"]:
        y = torch.nn.functional.silu(y)
    if xdtype != wdtype and y.dtype != xdtype:
        y = y.to(dtype=xdtype)
    return y

def verify_group_norm(N=32,
                      C=128,
                      H=256,
                      W=256,
                      G=32,
                      xdtype=torch.float16,
                      wdtype=torch.float32,
                      eps=1e-5,
                      memory_format=torch.channels_last,
                      device='cuda',
                      act=""):
    # create data
    x_shape = (N, C, H, W)
    w_shape = (C,)
    weight = torch.rand(w_shape,
                        dtype=wdtype,
                        device='cuda',
                        requires_grad=True)
    bias = torch.rand(w_shape,
                      dtype=wdtype,
                      device='cuda',
                      requires_grad=True)
    x = torch.randn(x_shape, dtype=xdtype, device='cuda')
    x = x.to(memory_format=memory_format)
    x.requires_grad_(True)
    thunder_group_norm = thunder.jit(torch_group_norm)
    y_torch = torch_group_norm(x, G, weight, bias, eps, act)
    y_thunder = thunder_group_norm(x, G, weight, bias, eps, act)
    # compare
    torch.testing.assert_close(y_thunder, y_torch, atol=4e-2, rtol=0)

# NVFUSER_DUMP=scheduler_params,cuda_to_file,fusion_ir_preseg,python_definition python group_norm.py 2>&1 |tee 1.log
if __name__ == "__main__":
  verify_group_norm(N=2, C=128, H=16, W=16)

```

**Comment by naoyam** [comment]
I wonder why `(1)` and `(2)` are not fused. I think an easy solution for the second reshape would move it to the end of the fusion and turn it to a meta-data operation.

**Comment by liqiangxl** [comment]
Due to `reductionInterferingView` check. If I disable this check & remove the last reshape in group norm (no weight & bias), the nvFuser uses `Inner Persistent` but got err msg `Merging IterDomains requires that their iteration types match. Outer: iS133{32}, Inner: rS17{i2}`. 
We can also move the 1st reshape to the beginning of the fusion, so it is just a no-op. what do you think?

**Comment by naoyam** [comment]
> Due to `reductionInterferingView` check. If I disable this check & remove the last reshape in group norm (no weight & bias), nvFuser uses `Inner Persistent` but got err msg `Merging IterDomains requires that their iteration types match. Outer: iS133{32}, Inner: rS17{i2}`. We can also move the 1st reshape to the beginning of the fusion, so it is just a no-op. what do you think?

There's only one normalization in `(1)` and `(2)`, so I assume `x1.sum` is used as the reference for the segment. Which tensor does this conflict come from?

**Comment by liqiangxl** [comment]
> There's only one normalization in `(1)` and `(2)`, so I assume `x1.sum` is used as the reference for the segment. Which tensor does this conflict come from?

Comes from `scheduler_utils::propagateReshapeTransforms(fusion, ca_map);`. 
There is a viewOp. The fusion before this transform:
 `T20_l[ iS100{2}, iS107{( 32 * i2 )}rf, iS142{16}, iS143{16} ] = view( T17_l[ iS82{2}, iS83{32}, iS84{i2}, iS140{16}, iS141{16} ] )`

```
Inputs:
  T0_g[ iS112{2}, iS113{32}, iS2{i2}, iS114{16}, iS115{16} ], __half
Outputs:
  T19_g[ iS169{2}, iS170{128}, iS171{16}, iS172{16} ], __half
  T26_g[ iS175{2}, iS176{32} ], float
  T28_g[ iS182{2}, iS183{32}, bS184{1}, bS185{1}, bS186{1} ], float

%kernel_math {
T24_l[ iS164{2}, iS165{32}, iS166{i2}, iS167{16}, iS168{16} ]
   = Set( T0_g[ iS112{2}, iS113{32}, iS2{i2}, iS114{16}, iS115{16} ], cache_op=Streaming )
T1_l[ iS116{2}, iS117{32}, iS7{i2}, iS118{16}, iS119{16} ]
   = __half2float(T24_l[ iS164{2}, iS165{32}, iS166{i2}, iS167{16}, iS168{16} ]);
T21_l[ iS144{2}, iS145{32}, rS146{i2}, rS147{16}, rS148{16} ]
   = reduction( T1_l[ iS116{2}, iS117{32}, iS7{i2}, iS118{16}, iS119{16} ], op = add, initial value = float(0), allreduce = false )
d214 = (double)(i2);
d216 = double(1) * d214;
d218 = (double)(16);
d220 = d216 * d218;
d222 = (double)(16);
d224 = d220 * d222;
T2_l[ iS124{2}, iS125{32} ]
   = T21_l[ iS144{2}, iS145{32}, rS146{i2}, rS147{16}, rS148{16} ]
   / d224;
T8_l[ iS128{2}, iS129{32}, bS39{1}, bS40{1}, bS41{1} ]
   = broadcast( T2_l[ iS124{2}, iS125{32} ] )
T9_l[ iS42{2}, iS43{32}, bS44{1}, bS45{1}, bS46{1} ]
   = Set( T8_l[ iS128{2}, iS129{32}, bS39{1}, bS40{1}, bS41{1} ], cache_op=Streaming )
T12_l[ iS57{2}, iS58{32}, bS59{1}, bS60{1}, bS61{1} ]
   = Set( T9_l[ iS42{2}, iS43{32}, bS44{1}, bS45{1}, bS46{1} ], cache_op=Streaming )
T13_l[ iS62{2}, iS63{32}, bS64{1 ex 4}, bS65{1 ex 16}, bS66{1 ex 16} ] = expand( T12_l[ iS57{2}, iS58{32}, bS59{1}, bS60{1}, bS61{1} ], {2, 32, 4, 16, 16} )
T14_l[ iS67{2}, iS68{32}, iS69{i2}, iS130{16}, iS131{16} ]
   = T1_l[ iS116{2}, iS117{32}, iS7{i2}, iS118{16}, iS119{16} ]
   - T13_l[ iS62{2}, iS63{32}, bS64{1 ex 4}, bS65{1 ex 16}, bS66{1 ex 16} ];
T22_l[ iS149{2}, iS150{32}, iS151{i2}, iS152{16}, iS153{16} ]
   = T1_l[ iS116{2}, iS117{32}, iS7{i2}, iS118{16}, iS119{16} ]
   - T8_l[ iS128{2}, iS129{32}, bS39{1}, bS40{1}, bS41{1} ];
T23_l[ iS154{2}, iS155{32}, iS156{i2}, iS157{16}, iS158{16} ]
   = T22_l[ iS149{2}, iS150{32}, iS151{i2}, iS152{16}, iS153{16} ]
   * T22_l[ iS149{2}, iS150{32}, iS151{i2}, iS152{16}, iS153{16} ];
T3_l[ iS132{2}, iS133{32}, rS17{i2}, rS134{16}, rS135{16} ]
   = reduction( T23_l[ iS154{2}, iS155{32}, iS156{i2}, iS157{16}, iS158{16} ], op = add, initial value = double(0), allreduce = false )
d18 = (double)(i2);
d20 = double(1) * d18;
d22 = (double)(16);
d24 = d20 * d22;
d26 = (double)(16);
d28 = d24 * d26;
d32 = (double)(0);
d34 = d28 - d32;
d36 = (double)(0);
b38 = d34 >= d36;
d40 = (double)(0);
d42 = where(b38, d34, d40);
d48 = reciprocal(d42);
T5_l[ iS136{2}, iS137{32} ]
   = T3_l[ iS132{2}, iS133{32}, rS17{i2}, rS134{16}, rS135{16} ]
   * d48;
T6_l[ iS138{2}, iS139{32}, bS29{1}, bS30{1}, bS31{1} ]
   = broadcast( T5_l[ iS136{2}, iS137{32} ] )
T7_l[ iS32{2}, iS33{32}, bS34{1}, bS35{1}, bS36{1} ]
   = Set( T6_l[ iS138{2}, iS139{32}, bS29{1}, bS30{1}, bS31{1} ], cache_op=Streaming )
T10_l[ iS47{2}, iS48{32}, bS49{1}, bS50{1}, bS51{1} ]
   = T7_l[ iS32{2}, iS33{32}, bS34{1}, bS35{1}, bS36{1} ]
   + double(1.0000000000000001e-05);
T11_l[ iS52{2}, iS53{32}, bS54{1}, bS55{1}, bS56{1} ]
   = rsqrtf(T10_l[ iS47{2}, iS48{32}, bS49{1}, bS50{1}, bS51{1} ]);
T15_l[ iS72{2}, iS73{32}, bS74{1}, bS75{1}, bS76{1} ]
   = Set( T11_l[ iS52{2}, iS53{32}, bS54{1}, bS55{1}, bS56{1} ], cache_op=Streaming )
T16_l[ iS77{2}, iS78{32}, bS79{1 ex 4}, bS80{1 ex 16}, bS81{1 ex 16} ] = expand( T15_l[ iS72{2}, iS73{32}, bS74{1}, bS75{1}, bS76{1} ], {2, 32, 4, 16, 16} )
T17_l[ iS82{2}, iS83{32}, iS84{i2}, iS140{16}, iS141{16} ]
   = T14_l[ iS67{2}, iS68{32}, iS69{i2}, iS130{16}, iS131{16} ]
   * T16_l[ iS77{2}, iS78{32}, bS79{1 ex 4}, bS80{1 ex 16}, bS81{1 ex 16} ];
T20_l[ iS100{2}, iS107{( 32 * i2 )}rf, iS142{16}, iS143{16} ] = view( T17_l[ iS82{2}, iS83{32}, iS84{i2}, iS140{16}, iS141{16} ] )
T25_l[ iS108{2}, iS109{128}, iS110{16}, iS111{16} ]
   = __float2half(T20_l[ iS100{2}, iS107{( 32 * i2 )}rf, iS142{16}, iS143{16} ]);
T19_g[ iS169{2}, iS170{128}, iS171{16}, iS172{16} ]
   = Set( T25_l[ iS108{2}, iS109{128}, iS110{16}, iS111{16} ], cache_op=Streaming )
T27_l[ iS173{2}, iS174{32} ]
   = Set( T2_l[ iS124{2}, iS125{32} ], cache_op=Streaming )
T26_g[ iS175{2}, iS176{32} ]
   = Set( T27_l[ iS173{2}, iS174{32} ], cache_op=Streaming )
T29_l[ iS177{2}, iS178{32}, bS179{1}, bS180{1}, bS181{1} ]
   = Set( T11_l[ iS52{2}, iS53{32}, bS54{1}, bS55{1}, bS56{1} ], cache_op=Streaming )
T28_g[ iS182{2}, iS183{32}, bS184{1}, bS185{1}, bS186{1} ]
   = Set( T29_l[ iS177{2}, iS178{32}, bS179{1}, bS180{1}, bS181{1} ], cache_op=Streaming )
}
```

**transform_propagator debug msg:**
```
Propagating transformations for T20_l[ iS107{( 32 * i2 )}rf, iS100{2}, iS142{16}, iS143{16} ], pos= 1
TransformPropagator::propagateC2P
  from: T20_l[ iS107{( 32 * i2 )}rf, iS100{2}, iS142{16}, iS143{16} ] @ 1
  to: T17_l[ iS82{2}, iS83{32}, iS84{i2}, iS140{16}, iS141{16} ]
  replayed: T17_l[ iS187{( 32 * i2 )}, iS82{2}, iS140{16}, iS141{16} ] @ 1
TransformPropagator::propagateC2P
  from: T17_l[ iS187{( 32 * i2 )}, iS82{2}, iS140{16}, iS141{16} ] @ 1
  to: T16_l[ iS77{2}, iS78{32}, bS79{1 ex 4}, bS80{1 ex 16}, bS81{1 ex 16} ]
  replayed: T16_l[ iS188{( 32 * 1 )}, iS77{2}, bS80{1 ex 16}, bS81{1 ex 16} ] @ 1
TransformPropagator::propagateC2P
  from: T16_l[ iS188{( 32 * 1 )}, iS77{2}, bS80{1 ex 16}, bS81{1 ex 16} ] @ 1
  to: T15_l[ iS72{2}, iS73{32}, bS74{1}, bS75{1}, bS76{1} ]
  replayed: T15_l[ iS189{( 32 * 1 )}, iS72{2}, bS75{1}, bS76{1} ] @ 1
TransformPropagator::propagateC2P
  from: T15_l[ iS189{( 32 * 1 )}, iS72{2}, bS75{1}, bS76{1} ] @ 1
  to: T11_l[ iS52{2}, iS53{32}, bS54{1}, bS55{1}, bS56{1} ]
  replayed: T11_l[ iS190{( 32 * 1 )}, iS52{2}, bS55{1}, bS56{1} ] @ 1
TransformPropagator::propagateC2P
  from: T11_l[ iS190{( 32 * 1 )}, iS52{2}, bS55{1}, bS56{1} ] @ 1
  to: T10_l[ iS47{2}, iS48{32}, bS49{1}, bS50{1}, bS51{1} ]
  replayed: T10_l[ iS191{( 32 * 1 )}, iS47{2}, bS50{1}, bS51{1} ] @ 1
TransformPropagator::propagateC2P
  from: T10_l[ iS191{( 32 * 1 )}, iS47{2}, bS50{1}, bS51{1} ] @ 1
  to: T7_l[ iS32{2}, iS33{32}, bS34{1}, bS35{1}, bS36{1} ]
  replayed: T7_l[ iS192{( 32 * 1 )}, iS32{2}, bS35{1}, bS36{1} ] @ 1
TransformPropagator::propagateC2P
  from: T7_l[ iS192{( 32 * 1 )}, iS32{2}, bS35{1}, bS36{1} ] @ 1
  to: T6_l[ iS138{2}, iS139{32}, bS29{1}, bS30{1}, bS31{1} ]
  replayed: T6_l[ iS193{( 32 * 1 )}, iS138{2}, bS30{1}, bS31{1} ] @ 1
TransformPropagator::propagateP2C
  from: T11_l[ iS190{( 32 * 1 )}, iS52{2}, bS55{1}, bS56{1} ] @ 1
  to: T29_l[ iS177{2}, iS178{32}, bS179{1}, bS180{1}, bS181{1} ]
TransformReplay::replayCasP consumer: T29_l[ iS177{2}, iS178{32}, bS179{1}, bS180{1}, bS181{1} ], producer: T11_l[ iS190{( 32 * 1 )}, iS52{2}, bS55{1}, bS56{1} ]
  replayed: T29_l[ iS194{( 32 * 1 )}, iS177{2}, bS180{1}, bS181{1} ] @ 1
TransformPropagator::propagateP2C
  from: T29_l[ iS194{( 32 * 1 )}, iS177{2}, bS180{1}, bS181{1} ] @ 1
  to: T28_g[ iS182{2}, iS183{32}, bS184{1}, bS185{1}, bS186{1} ]
TransformReplay::replayCasP consumer: T28_g[ iS182{2}, iS183{32}, bS184{1}, bS185{1}, bS186{1} ], producer: T29_l[ iS194{( 32 * 1 )}, iS177{2}, bS180{1}, bS181{1} ]
  replayed: T28_g[ iS195{( 32 * 1 )}, iS182{2}, bS185{1}, bS186{1} ] @ 1
TransformPropagator::propagateC2P
  from: T17_l[ iS187{( 32 * i2 )}, iS82{2}, iS140{16}, iS141{16} ] @ 1
  to: T14_l[ iS67{2}, iS68{32}, iS69{i2}, iS130{16}, iS131{16} ]
  replayed: T14_l[ iS196{( 32 * i2 )}, iS67{2}, iS130{16}, iS131{16} ] @ 1
TransformPropagator::propagateC2P
  from: T14_l[ iS196{( 32 * i2 )}, iS67{2}, iS130{16}, iS131{16} ] @ 1
  to: T13_l[ iS62{2}, iS63{32}, bS64{1 ex 4}, bS65{1 ex 16}, bS66{1 ex 16} ]
  replayed: T13_l[ iS197{( 32 * 1 )}, iS62{2}, bS65{1 ex 16}, bS66{1 ex 16} ] @ 1
TransformPropagator::propagateC2P
  from: T13_l[ iS197{( 32 * 1 )}, iS62{2}, bS65{1 ex 16}, bS66{1 ex 16} ] @ 1
  to: T12_l[ iS57{2}, iS58{32}, bS59{1}, bS60{1}, bS61{1} ]
  replayed: T12_l[ iS198{( 32 * 1 )}, iS57{2}, bS60{1}, bS61{1} ] @ 1
TransformPropagator::propagateC2P
  from: T12_l[ iS198{( 32 * 1 )}, iS57{2}, bS60{1}, bS61{1} ] @ 1
  to: T9_l[ iS42{2}, iS43{32}, bS44{1}, bS45{1}, bS46{1} ]
  replayed: T9_l[ iS199{( 32 * 1 )}, iS42{2}, bS45{1}, bS46{1} ] @ 1
TransformPropagator::propagateC2P
  from: T9_l[ iS199{( 32 * 1 )}, iS42{2}, bS45{1}, bS46{1} ] @ 1
  to: T8_l[ iS128{2}, iS129{32}, bS39{1}, bS40{1}, bS41{1} ]
  replayed: T8_l[ iS200{( 32 * 1 )}, iS128{2}, bS40{1}, bS41{1} ] @ 1
TransformPropagator::propagateP2C
  from: T8_l[ iS200{( 32 * 1 )}, iS128{2}, bS40{1}, bS41{1} ] @ 1
  to: T22_l[ iS149{2}, iS150{32}, iS151{i2}, iS152{16}, iS153{16} ]
TransformReplay::replayCasP consumer: T22_l[ iS149{2}, iS150{32}, iS151{i2}, iS152{16}, iS153{16} ], producer: T8_l[ iS200{( 32 * 1 )}, iS128{2}, bS40{1}, bS41{1} ]
  replayed: T22_l[ iS201{( 32 * i2 )}, iS149{2}, iS152{16}, iS153{16} ] @ 1
TransformPropagator::propagateP2C
  from: T22_l[ iS201{( 32 * i2 )}, iS149{2}, iS152{16}, iS153{16} ] @ 1
  to: T23_l[ iS154{2}, iS155{32}, iS156{i2}, iS157{16}, iS158{16} ]
TransformReplay::replayCasP consumer: T23_l[ iS154{2}, iS155{32}, iS156{i2}, iS157{16}, iS158{16} ], producer: T22_l[ iS201{( 32 * i2 )}, iS149{2}, iS152{16}, iS153{16} ]
  replayed: T23_l[ iS202{( 32 * i2 )}, iS154{2}, iS157{16}, iS158{16} ] @ 1
TransformPropagator::propagateP2C
  from: T23_l[ iS202{( 32 * i2 )}, iS154{2}, iS157{16}, iS158{16} ] @ 1
  to: T3_l[ iS132{2}, iS133{32}, rS17{i2}, rS134{16}, rS135{16} ]
TransformReplay::replayCasP consumer: T3_l[ iS132{2}, iS133{32}, rS17{i2}, rS134{16}, rS135{16} ], producer: T23_l[ iS202{( 32 * i2 )}, iS154{2}, iS157{16}, iS158{16} ]
An error occurred while executing nvFuser FusionDefinition 0.
```

 Merging IterDomains requires that their iteration types match. Outer: iS133{32}, Inner: rS17{i2}

**Comment by liqiangxl** [comment]
Looks like thunder did some optimizations of the captured graph. Specifically, it does `reshape` of input before `cast to fp32`.  Afther computation, it added another reshape before cast back to fp16. The 2nd reshape caused the error.
```
def augmented_forward_fn(x):
  # x: "cuda:0 f16[2, 128, 16, 16]"
  t0 = torch.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
    # t0 = ltorch.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
      # t0 = prims.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
  [t16, t5, t9] = nvFusion0(t0)
    # t1 = prims.convert_element_type(t0, dtypes.float32)  # t1: "cuda:0 f32[2, 32, 4, 16, 16]"
    # (t4, t5) = prims.var_mean(t1, (2, 3, 4), correction=0)
    # t6 = prims.broadcast_in_dim(t4, [2, 32, 1, 1, 1], [0, 1])  # t6: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t7 = prims.broadcast_in_dim(t5, [2, 32, 1, 1, 1], [0, 1])  # t7: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t8 = prims.add(t6, 1e-05)  # t8: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t9 = prims.rsqrt(t8)  # t9: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t10 = prims.broadcast_in_dim(t7, (2, 32, 4, 16, 16), (0, 1, 2, 3, 4))  # t10: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t12 = prims.sub(t1, t10)  # t12: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t13 = prims.broadcast_in_dim(t9, (2, 32, 4, 16, 16), (0, 1, 2, 3, 4))  # t13: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t14 = prims.mul(t12, t13)  # t14: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t15 = prims.reshape(t14, (2, 128, 16, 16))  # t15: "cuda:0 f32[2, 128, 16, 16]"
    # t16 = prims.convert_element_type(t15, dtypes.float16)  # t16: "cuda:0 f16[2, 128, 16, 16]"
  return {'output': t16, 'flat_args': [x], 'flat_output': (t16,)}, ((t0, t5, t9), ())
```

**Comment by liqiangxl** [comment]
Thanks for the suggestion @jjsjann123 and  @kevinstephano, nvFuser gets two reshapes if `thunder.jit(torch_group_norm, nv_enable_bookend=False)`
```
def augmented_forward_fn(x):
  # x: "cuda:0 f16[2, 128, 16, 16]"
  [t16, t5, t9] = nvFusion0(x)
    # t0 = prims.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
    # t1 = prims.convert_element_type(t0, dtypes.float32)  # t1: "cuda:0 f32[2, 32, 4, 16, 16]"
    # (t4, t5) = prims.var_mean(t1, (2, 3, 4), correction=0)
    # t6 = prims.broadcast_in_dim(t4, [2, 32, 1, 1, 1], [0, 1])  # t6: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t7 = prims.broadcast_in_dim(t5, [2, 32, 1, 1, 1], [0, 1])  # t7: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t8 = prims.add(t6, 1e-05)  # t8: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t9 = prims.rsqrt(t8)  # t9: "cuda:0 f32[2, 32, 1, 1, 1]"
    # t10 = prims.broadcast_in_dim(t7, (2, 32, 4, 16, 16), (0, 1, 2, 3, 4))  # t10: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t12 = prims.sub(t1, t10)  # t12: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t13 = prims.broadcast_in_dim(t9, (2, 32, 4, 16, 16), (0, 1, 2, 3, 4))  # t13: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t14 = prims.mul(t12, t13)  # t14: "cuda:0 f32[2, 32, 4, 16, 16]"
    # t15 = prims.reshape(t14, (2, 128, 16, 16))  # t15: "cuda:0 f32[2, 128, 16, 16]"
    # t16 = prims.convert_element_type(t15, dtypes.float16)  # t16: "cuda:0 f16[2, 128, 16, 16]"
  return {'output': t16, 'flat_args': [x], 'flat_output': (t16,)}, ((t5, t9, x), (0,))
```

If we change these two reshapes to `reshape of input` and `reshape before output`, and revise `MarkAliasesPreparePass`, nvFuser can change from 3 kernels to two no ops and a normalization kernel. I added a draft PR (#2405 ) with three test cases:

1. `GroupNormOriginal`: segment into 3 kernels
2. `GroupNormReshapeMovedToInputOutputNoWeightBias`: one kernel
3. `GroupNormReshapeMovedToInputOutput`: one kernel

**So the proposed plan is a 2-steps approach:**

- step-1, revise `MarkAliasesPreparePass` to get one kernel if the fusion only have `reshape of input` and `reshape before output`. PR #2405 
- step-2, move reshape exprs to `reshape of input` or `reshape before output`

**Comment by liqiangxl** [comment]
Add original related issue. https://github.com/Lightning-AI/lightning-thunder/issues/468

**Comment by wujingyue** [comment]
Unfortunately, the current alias analysis wasn't built for tracking aliases involving intermediates. When I wrote it, I didn't see a strong case for dealing with intermediates and expected intermediates to be fused into a kernel and become cheap index calculation. However, in this case, it appears that the two reshapes have caused the normalization scheduler to bail out... 

#2405 sounds like a reasonable extension -- add segment_set after input reshapes and before output reshapes. Caveat: there are some tricky patterns that we'll need to consider, e.g., if the original input is used by an operation other than the reshape, we probably shouldn't segment out the reshape. But we can leave these important implementation details to PR discussion. 

That being said, is the normalization scheduler supposed to handle the two reshapes? That feels the right solution to me. However, if it would take a long time, I would totally understand the need for a quicker workaround.

**Comment by wujingyue** [comment]
Thanks for the write-up, @liqiangxl! The problem looks quite clear to me even though I was unsure about the solution.

**Comment by liqiangxl** [comment]
> That being said, is the normalization scheduler supposed to handle the two reshapes? That feels the right solution to me. However, if it would take a long time, I would totally understand the need for a quicker workaround.

It should be able to handle the first reshape (which only includes split of ID), but for the second reshape (which is merge of an iter ID and a reduction ID) needs a lot of work. So another option is we can extend current reduction/normalization scheduler to handle some kinds of reshapes so the pre-segment optimizaiton pass only needs to process some specfic types of reshape e.g. reshape includes a merge of iter ID and redu ID.

**Comment by liqiangxl** [comment]
@jjsjann123 , @wujingyue , and @naoyam
Thanks for the helpful discussions.
Here is a summary of the approach :
- (1) The reshape of inputs only involves `split` of domains, it won't interfere with reduction where iter and redu domains are merged separately.  #2437 allows reduction/normalization schedulers take the 1st reshape.
- (2) The reshape of outputs involves `merge` of `iter` and `redu` domains, #2405 peels off the 2nd reshape into a no-op.
- (3) thunder will ensure reshape is moved to the front and end of the fusion.

**Comment by naoyam** [comment]
> Looks like thunder did some optimizations of the captured graph. Specifically, it does `reshape` of input before `cast to fp32`. Afther computation, it added another reshape before cast back to fp16. The 2nd reshape caused the error.
> 
> ```
> def augmented_forward_fn(x):
>   # x: "cuda:0 f16[2, 128, 16, 16]"
>   t0 = torch.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
>     # t0 = ltorch.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
>       # t0 = prims.reshape(x, (2, 32, 4, 16, 16))  # t0: "cuda:0 f16[2, 32, 4, 16, 16]"
>   [t16, t5, t9] = nvFusion0(t0)
>     # t1 = prims.convert_element_type(t0, dtypes.float32)  # t1: "cuda:0 f32[2, 32, 4, 16, 16]"
>     # (t4, t5) = prims.var_mean(t1, (2, 3, 4), correction=0)
>     # t6 = prims.broadcast_in_dim(t4, [2, 32, 1, 1, 1], [0, 1])  # t6: "cuda:0 f32[2, 32, 1, 1, 1]"
>     # t7 = prims.broadcast_in_dim(t5, [2, 32, 1, 1, 1], [0, 1])  # t7: "cuda:0 f32[2, 32, 1, 1, 1]"
>     # t8 = prims.add(t6, 1e-05)  # t8: "cuda:0 f32[2, 32, 1, 1, 1]"
>     # t9 = prims.rsqrt(t8)  # t9: "cuda:0 f32[2, 32, 1, 1, 1]"
>     # t10 = prims.broadcast_in_dim(t7, (2, 32, 4, 16, 16), (0, 1, 2, 3, 4))  # t10: "cuda:0 f32[2, 32, 4, 16, 16]"
>     # t12 = prims.sub(t1, t10)  # t12: "cuda:0 f32[2, 32, 4, 16, 16]"
>     # t13 = prims.broadcast_in_dim(t9, (2, 32, 4, 16, 16), (0, 1, 2, 3, 4))  # t13: "cuda:0 f32[2, 32, 4, 16, 16]"
>     # t14 = prims.mul(t12, t13)  # t14: "cuda:0 f32[2, 32, 4, 16, 16]"
>     # t15 = prims.reshape(t14, (2, 128, 16, 16))  # t15: "cuda:0 f32[2, 128, 16, 16]"
>     # t16 = prims.convert_element_type(t15, dtypes.float16)  # t16: "cuda:0 f16[2, 128, 16, 16]"
>   return {'output': t16, 'flat_args': [x], 'flat_output': (t16,)}, ((t0, t5, t9), ())
> ```

Trying to catch up what's going on here, but still confused why these two are not fused:

> (1) pointwise doing cast + reshape
> (2) normalization

Doesn't the second reshape belong to the third segment?

> (3) pointwise doing reshape + scale & bias

**Comment by wujingyue** [comment]
> Here is a summary of the approach

LGTM. I'll defer to others whether we should fix the scheduler(s) to accept both types of reshapes. That sounds like the right fix to me even though it may take longer.

**Comment by liqiangxl** [comment]
> Trying to catch up what's going on here, but still confused why these two are not fused:
> 
> (1) pointwise doing cast + reshape
> (2) normalization

Rejected by `reductionInterferingView()`, it divides the IDs of the reduction tv into multiple groups based on iter or reduction. Then generate a disjoint set for all the IDs and check if there are IDs in the same entry of the disjoint set belongs to two different groups.

For example, a tv with [{i0}, {32}, **{i2/32}, {i3}, {i4}**], bold represents reduction dims. 

- (1) They are grouped into 2 groups `**{i2/32}, {i3}, {i4}**` and `{i0}, {32}`. 
- (2) `**{i2/32}**, {32}, {i2}` are in the same entry of the disjoint sets (why?)
- (3) `**{i2/32}**` is in a different group from `**{32}**`
- (4)`reductionInterferingView()` returns false and fusion rejected.

I think we can safely skip these checks if the reshape only involves `split` since it won't cause the merge of `iter` ID and `redu` ID which is the root limitation of the current reduction scheudler. The fix is simple and avoids the complex checks.
Another approach is revise the logic in the disjoint set based checks. It seems more complex than the current appraoch in #2437. so this opion is not explored.


> 
> Doesn't the second reshape belong to the third segment?
> 
> (3) pointwise doing reshape + scale & bias

Yes.

**Comment by wujingyue** [comment]
> thunder will ensure reshape is moved to the front and end of the fusion

I missed this part. I was expecting nvFuser not Thunder to do this. It sounds like a specific code motion to work around an nvFuser limitation. Doing this in nvFuser makes nvFuser standalone, not relying on a specific code pattern upstream.

**Comment by liqiangxl** [comment]
> > thunder will ensure reshape is moved to the front and end of the fusion
> 
> I missed this part. I was expecting nvFuser not Thunder to do this. It sounds like a specific code motion to work around an nvFuser limitation. Doing this in nvFuser makes nvFuser standalone, not relying on a specific code pattern upstream.

Thanks for the quick feedback. I'll check with other stakeholders and may schedule a short sync meeting.

**Comment by naoyam** [comment]
> > Trying to catch up what's going on here, but still confused why these two are not fused:
> > (1) pointwise doing cast + reshape
> > (2) normalization
> 
> Rejected by `reductionInterferingView()`, it divides the IDs of the reduction tv into multiple groups based on iter or reduction. Then generate a disjoint set for all the IDs and check if there are IDs in the same entry of the disjoint set belongs to two different groups.
> 
> For example, a tv with [{i0}, {32}, **{i2/32}, {i3}, {i4}**], bold represents reduction dims.
> 
> * (1) They are grouped into 2 groups `**{i2/32}, {i3}, {i4}**` and `{i0}, {32}`.
> * (2) `**{i2/32}**, {32}, {i2}` are in the same entry of the disjoint sets (why?)
> * (3) `**{i2/32}**` is in a different group from `**{32}**`
> * (4)`reductionInterferingView()` returns false and fusion rejected.
> 
> I think we can safely skip these checks if the reshape only involves `split` since it won't cause the merge of `iter` ID and `redu` ID which is the root limitation of the current reduction scheudler. The fix is simple and avoids the complex checks. Another approach is revise the logic in the disjoint set based checks. It seems more complex than the current appraoch in #2437. so this opion is not explored.
> 
> > Doesn't the second reshape belong to the third segment?
> > (3) pointwise doing reshape + scale & bias
> 
> Yes.

I see. I was only thinking about `requiresForwardViewReplay`, but it now makes sense. 

Have you thought about using IdModel to rewrite `reductionInterferingView`? I think it'd be relatively straightforward with an ID graph. All we need to see is if any use of the ID groups of the reference tensor could merge multiple groups, which would be a simple graph traversal. It should naturally handle Merge as well.

**Comment by jjsjann123** [comment]
> > > thunder will ensure reshape is moved to the front and end of the fusion
> > 
> > 
> > I missed this part. I was expecting nvFuser not Thunder to do this. It sounds like a specific code motion to work around an nvFuser limitation. Doing this in nvFuser makes nvFuser standalone, not relying on a specific code pattern upstream.
> 
> Thanks for the quick feedback. I'll check with other stakeholders and may schedule a short sync meeting.

Agree that the proper approach is that nvfuser should be able to handle graph level optimization and re-order some trivial reshape to allow better fusion. We can discuss the priority on that.

Meanwhile, the last reshape in thunder might be an easier thing to change with some slightly ugly code: https://github.com/Lightning-AI/lightning-thunder/blob/14e6c9b67eb038ab28a192cd381bc183b77e8f81/thunder/torch/__init__.py#L4406-L4420

**Comment by liqiangxl** [comment]
The remaining issue if for channel last format, current reduction/normalization scheduler didn't consider allocation domains.
