### ISSUE TITLE
Blackwell B100 test cases

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#2381]

**Comment by zasdfgbnm** [comment]
We should skip hopper matmul tests on blackwell:
> Target architectures with suffix “a”, such as sm_90a, include architecture-accelerated features that are supported on the specified architecture only, hence such targets do not follow the onion layer model. Therefore, PTX code generated for such targets cannot be run on later generation devices. Architecture-accelerated features can only be used with targets that support these features.

https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#ptx-module-directives-target

but not ampere ones
