### ISSUE TITLE
Almost Exact graph does not map non-size-one broadcast domains

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#2393]
One could say this would be due to creating broadcast domains with non size one, but if a broadcast domain is, for example, split by 4, it would generate two broadcast domains, `b{ceilDiv(1, 4)}` and `b{4}`, both of which do not "appear" to have size one (the former could be simplified to 1, though).

These broadcast domains do not join the almost-exact mappings:

https://github.com/NVIDIA/Fuser/blob/main/csrc/compute_at_map.cpp#L718
https://github.com/NVIDIA/Fuser/blob/main/csrc/id_model/id_model.cpp#L335

That is, if a non-broadcast domain is merged with, e.g., `b{4}`, the merge output would not be mapped with the input non-broadcast domain. 

One of the main current use cases of the almost-exact graph is indexing, where mapping broadcast domains, regardless of extents, do not matter, so it makes sense to handle such non-size-one broadcast domains in the same way as size-one broadcast domains.

**Comment by naoyam** [comment]
Sample repro where indexing traversal fails:

```
  Fusion fusion;
  FusionGuard fg(&fusion);

  // [w]
  auto tv0 = makeSymbolicTensor(1);
  fusion.addInput(tv0);

  // [w, x]
  auto tv1 = makeSymbolicTensor(2);
  fusion.addInput(tv1);

  auto tv2 = broadcast(tv0, {false, true});
  auto tv3 = add(tv1, tv2);
  fusion.addOutput(tv3);

  tv3->split(0, 3);
  tv3->split(2, 4);
  tv3->merge(1);
  tv3->split(1, 5);

  MaxRootDomainInfoSpanningTree tree(tv3);
  TransformPropagator tp(tv3);
  tree.traverse(&tp);

  inlineAllAt(tv3, 1, true);
```
![transform](https://github.com/NVIDIA/Fuser/assets/363169/76b77771-2fe7-4c1d-9e25-9f420379bfad)

In this case, indexing `tv2` as the producer of `tv3` fails as its traversal can't reach id `18` and also `19` and `20`, which are part of the allocation domains of `tv2`.

**Comment by jacobhinkle** [comment]
Would it make sense to special-case `split` so that any split of a size-1 broadcast gives extents of 1 to both the outputs?

**Comment by naoyam** [comment]
> Would it make sense to special-case `split` so that any split of a size-1 broadcast gives extents of 1 to both the outputs?

I think that makes sense. More broadly, outputs from broadcast inputs should be broadcast, except for resize. Not sure if there's any side effect.
