### ISSUE TITLE
Tracking outer reduction CPP benchmark regressions

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#2396]
#2281 leads to several regressions for cases with small reduction dim, that PR prioritized vectorization, it leads to lower unroll, so needs more threads/blocks in the reduction dim, which leads to grid reduction which is slower than the original block reduction. 
Will be fixed after step-2 #2302 where block reduction is prioritized. 
Should use a baseline before #2281 is merged.

**Comment by Priya2698** [comment]
Which cases are seeing regressions? 
I will include those ranges in python benchmarks.

**Comment by liqiangxl** [comment]
These cases
![image](https://github.com/NVIDIA/Fuser/assets/116412316/afd23927-8b23-4b9a-84bb-88db6717e63b)
I remember we want to add all the extreme cases in outer/inner reductions not covered by the current python benchmakrs, e.g. `Ranges({{32768, 64 * 1024 * 1024}, {2, 16}})`, you may check ranges in [reduction.cpp](https://github.com/NVIDIA/Fuser/blob/main/benchmarks/cpp/reduction.cpp).

**Comment by liqiangxl** [comment]
fixed.
