### ISSUE TITLE
Flipping declaration order of matmul inputs results in scheduling error

### ISSUE THREAD

**Issue by cowanmeg** [NVIDIA/Fuser#2434]
I noticed a bug where if the TensorView ordering causes a compilation error in the matmul scheduler. 

This fusion works fine:
``` 
  TensorView* a = makeContigConcreteTensor({64, 128}, DataType::BFloat16);
  TensorView* b = makeContigConcreteTensor({32, 128}, DataType::BFloat16);

  TensorView* bbcast = broadcast(b, {true, false, false});
  TensorView* abcast = broadcast(a, {false, true, false});
  TensorView* ab = mul(abcast, bbcast);
  TensorView* matmul = sum(ab, {-1});

  fusion->addInput(a);
  fusion->addInput(b);
  fusion->addOutput(matmul);
```

However, if I flip the order a and b are declared, the fusion does not compile:
```
  TensorView* b = makeContigConcreteTensor({32, 128}, DataType::BFloat16);
  TensorView* a = makeContigConcreteTensor({64, 128}, DataType::BFloat16);

  TensorView* bbcast = broadcast(b, {true, false, false});
  TensorView* abcast = broadcast(a, {false, true, false});
  TensorView* ab = mul(abcast, bbcast);
  TensorView* matmul = sum(ab, {-1});

  fusion->addInput(a);
  fusion->addInput(b);
  fusion->addOutput(matmul);
```
And results in the error: 
C++ exception with description "producer->getComputePosition(tv) <= double_buffer_pos INTERNAL ASSERT FAILED at "Fuser/csrc/device_lower/pass/double_buffer.cpp":96, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Invalid tensor to double-buffer. The computeAt position of the producer tensor must be moved left: T9_s[ iS76{( ceilDiv(32, 128) )}, iS78{( ceilDiv(128, 32) )}, iS181{( ceilDiv(( ( ( ( ceilDiv(( ceilDiv(128, 2) ), 4) ) * 4 ) * 2 ) * ( ( ( ceilDiv(( ceilDiv(32, 8) ), 4) ) * 4 ) * 8 ) ), 1024) )}, ithreadIdx.z187{( ceilDiv(( ceilDiv(( ceilDiv(1024, 8) ), 32) ), 2) )}, ithreadIdx.y188{2}, ithreadIdx.x186{32}, iV184{8} ] ca_pos( 1 )
Exception raised from validateDoubleBufferedTensor at /Fuser/csrc/device_lower/pass/double_buffer.cpp:96 (most recent call first):

I think the source of the error is here: https://github.com/NVIDIA/Fuser/blob/9381e6f48f0663faf6d189412247f8336429471f/csrc/scheduler/mma_utils.cpp#L1280
where the order of TensorView is based on the name if the number of uses is the same which can result in MatmulRole::Operands storing B, A instead of A, B
cc'ing @jacobhinkle

**Comment by jacobhinkle** [comment]
Thanks for reporting this! I think I'll need to revert #2419 since A and B actually are scheduled slightly differently from one another.
