### ISSUE TITLE
validation err in `tests/python/pytest_ops.py::test_correctness_truediv_complex64`

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#2444]
This test failed several times in CI, seems due to tolerance.

```
00:31:45 FAILED tests/python/pytest_ops.py::test_correctness_truediv_complex64 - AssertionError: Tensor-likes are not close!
00:31:45 
00:31:45 Mismatched elements: 1 / 1048576 (0.0%)
00:31:45 Greatest absolute difference: 0.001091830083169043 at index (337, 343) (up to 0.001 allowed)
00:31:45 Greatest relative difference: 7.912316846159229e-08 at index (337, 343) (up to 0 allowed)
```

There is a TODO:
```
00:31:45         # TODO Add specific dtype tolerances
00:31:45 >       torch.testing.assert_close(
00:31:45             nvfuser_result, torch_result, equal_nan=True, atol=1e-3, rtol=0
00:31:45         )
```

**Comment by jacobhinkle** [comment]
I tried to fix this in #2392 but I guess it's still happening. Maybe we should force `|denom| >= 1`.

**Comment by liqiangxl** [comment]
> I tried to fix this in #2392 but I guess it's still happening. Maybe we should force `|denom| >= 1`.

Thanks for the heads up. I am wondering why it only happens for dtype `complex64` (IIRC). Can we incrase atol for this dtype? I saw a todo about using different atol for different dtypes. @rdspring1

**Comment by jacobhinkle** [comment]
Is it because our implementation is not stable for large and small denominators? There is some protection against iverflow and underflow here: https://github.com/NVIDIA/Fuser/blob/main/runtime/complex_number.cu. But the algorithm is still the naive one which can be improved c.f. https://arxiv.org/abs/1210.4539.

**Comment by jacobhinkle** [comment]
> Is it because our implementation is not stable for large and small denominators? There is some protection against overflow and underflow here: https://github.com/NVIDIA/Fuser/blob/main/runtime/complex_number.cu. But the algorithm is still the naive one which can be improved c.f. https://arxiv.org/abs/1210.4539.

What I said above is true, but it does seem that our implementation matches ATen: https://github.com/pytorch/pytorch/blob/bbdeff76fc1205d13358ee6c147a4d8930b562ee/aten/src/ATen/cuda/llvm_complex.cpp#L367. So that doesn't explain the differences.
