### ISSUE TITLE
Post-reduction fusion

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#260]
While experimenting fusing `take_along_axis`, I found seemingly inconsistent scheduling with reductions.

https://github.com/NVIDIA/Fuser/blob/2a1a65b5f3823892e9075924415c04f3e6a20c3d/csrc/scheduler/registry.cpp#L359-L395

This rule segments this fusion because of `tv1`:

```
TEST_F(NVFuserTest, PostReductionFusion1_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  auto tv0 = makeSymbolicTensor(2);
  fusion->addInput(tv0);
  auto tv1 = makeSymbolicTensor(1);
  fusion->addInput(tv1);

  auto tv2 = sum(tv0, {1});
  auto tv3 = add(tv2, tv1);
  fusion->addOutput(tv3);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::manual_seed(0);
  at::Tensor t0 = at::randn({4, 32}, options);
  at::Tensor t1 = at::randn({4}, options);
  std::vector<c10::IValue> aten_inputs({t0, t1});

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);

  std::cout << "Num segments: "
            << executor_cache.getMostRecentKernelRuntime()->fusionSegments()->groups().size() << std::endl;
}
```

However, this is not segmented although it's quite similar to the above fusion:

```
TEST_F(NVFuserTest, PostReductionFusion2_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  auto tv0 = makeSymbolicTensor(2);
  fusion->addInput(tv0);
  auto tv1 = makeSymbolicTensor(1);
  fusion->addInput(tv1);

  auto tv2 = broadcast(tv1, {false, true});
  auto tv3 = add(tv0, tv2);
  auto tv4 = sum(tv3, {1});
  auto tv5 = add(tv4, tv1);
  fusion->addOutput(tv5);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::manual_seed(0);
  at::Tensor t0 = at::randn({4, 32}, options);
  at::Tensor t1 = at::randn({4}, options);
  std::vector<c10::IValue> aten_inputs({t0, t1});

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);

  std::cout << "Num segments: "
            << executor_cache.getMostRecentKernelRuntime()->fusionSegments()->groups().size() << std::endl;
}
```

In this case `tv1` is used as a dependency to the reduction op, so another use of it after the reduction does not break the fusion restriction.

This seems inconsistent to me. Why do we need to segment the first fusion? Post-reduction may not have limited parallelism, so it may make more sense to end the kernel and restart with different parallelization, but then shouldn't the first fusion also be segmented?

It seems that both cases should be fine without segmentation. Unless the reduction output is broadcast, shouldn't we always allow post-reduction fusions (for inner reductions)?

**Comment by naoyam** [comment]
CC: @csarofeen

**Comment by csarofeen** [comment]
I think what you're hitting is me trying to avoid strided parallelization on output fusion of reductions. I was concerned we could get into a situation where we have an inner reduction on something like tidx, then we do a bunch of pointwise ops where tidx is not active.

**Comment by csarofeen** [comment]
If we have an outer reduction, then I think it should not worry about what comes after the reduction, but after an inner reduction I was hesitant to allow a lot of fused pointwise ops. Think about the case where we have `[1024, 2]->sum{1}` then we have a bunch of inputs that operate with the result. This would have non coalesced access on all the other inputs.

**Comment by naoyam** [comment]
Yeah, in that case, it would make sense to stop fusing, but if there's only a few such post-reduction ops, it might make sense to fuse them together, depending on the penalty of the non coalesced accesses and the cost of the segmentation. Also, if such inputs are small enough to fit in L2, the penalty of the non coalesced accesses may be small.

Such non-coalesced accesses also happen with pre-reduction fusions, where tensor inputs of shape, e.g., `[1024]`, are used before the reduction of `[1024, 2]->sum{1}`. 

I'm closing this issue for now, but I think what we'd need is to make the segmentation decision more adaptive to problem sizes.

**Comment by csarofeen** [comment]
Agreed, I think we may have had this conversation in the past too about this exact thing... maybe it was with someone else. But yes we could definitely make this a less conservative decision.
