### ISSUE TITLE
`cudaMalloc` when using `at::matmul_out`

### ISSUE THREAD

**Issue by samnordmann** [NVIDIA/Fuser#2673]
# Description
Nsight profiles reveal that using `matmul_out` introduces allocations of new buffers. Our conclusion is:
- `matmul_out` triggers allocation whereas it shouldn't, at least when using multiple streams
- This allocation might be hidden by torch's allocator cache, which doesn't work well with streams (see, e.g., [here](https://dev-discuss.pytorch.org/t/fsdp-cudacachingallocator-an-outsider-newb-perspective/1486))

Even if the allocator cache can save us in some places, I see no reason why `matmul_out` should allocate.

Also, relying on the allocator is risky in my opinion, especially because we are beyond what is supported by the cache, especially when we use different slices on the same buffer in different streams, as done in the overlap technic of #2401. 

# Experiment

We provide a reproducer in 
- #2682 

that performs `I=8` matrix multiply in a for-loop. The parameters of our experiments are:
- the matrix dimensions `M=2^8`, `N=2^8`, `K=2^8`
- setup: H100 80GB. We also ran the same experiment on V100 16GB and got similar result, so we omit this case.
- `compute_mode`:
    - `matmul`: use `at::matmul`
    - `matmul_out`: use `at::matmul_out` on preallocated output
    - `unfused`: decompose the matmul into pointiwise multiply `at::mul_out` and sum reduction `at::sum_out` on preallocated buffers
- `stream_mode`
    - `no_streams`: use only the default streams
    - `post_on_different_streams`: posts the `at::` compute operation on different streams, but allocate the buffers on the default stream. **This is probably what is closest to our use case** from #2401 where we allocate one big buffer and handle each slice on a different stream
    - `allocate_and_post_on_different_streams`: allocates and posts the `at::` compute operations on different streams
- `enable_allocator_cache`: through setting or unsetting the environment variable `PYTORCH_NO_CUDA_MEMORY_CACHING` 

# 1. `stream_mode=no_streams`
## 1.a. `compute_mode==matmul_out`
Whether we enable allocation cache or not, we do not see any cudaMalloc:
![LOG2_M=8__LOG2_N=8__LOG2_K=8__STREAM_MODE=no_streams__COMPUTE_MODE=matmul_out__ENABLE_MEMORY_CACHE=0](https://github.com/user-attachments/assets/15698310-86b3-443a-a82b-eb9b8fbcd0d2)

## 1.b. `compute_mode==matmul`

As expected, a cudaMalloc appears, corresponding to allocating the output buffer:
![LOG2_M=8__LOG2_N=8__LOG2_K=8__STREAM_MODE=no_streams__COMPUTE_MODE=matmul__ENABLE_MEMORY_CACHE=0](https://github.com/user-attachments/assets/c2d9e048-b2de-4032-baa6-d0d04e03c3ad)

# 2. `stream_mode=allocate_and_post_on_different_streams`

## 2.a. `compute_mode==matmul_out`

`cudaMalloc` are present, even when enabling cache allocator. **This is an unexpected behavior,** as `matmul_out` shouldn't allocate anything in principle.
![LOG2_M=8__LOG2_N=8__LOG2_K=8__STREAM_MODE=allocate_and_post_on_different_streams__COMPUTE_MODE=matmul_out__ENABLE_MEMORY_CACHE=1](https://github.com/user-attachments/assets/5fe95146-012f-4ca4-9280-928c736df029)

## 2.b. `compute_mode==matmul`

As expected, a **second** `cudaMalloc` appears, corresponding to allocating the output buffer:

![LOG2_M=8__LOG2_N=8__LOG2_K=8__STREAM_MODE=allocate_and_post_on_different_streams__COMPUTE_MODE=matmul__ENABLE_MEMORY_CACHE=1](https://github.com/user-attachments/assets/a8566830-7edd-468f-9650-bfc743d6358f)

## 2.c. `compute_mode==unfused`
switching to "unfused", even if disabling allocator cache, **all the cuda malloc disappear** 

![LOG2_M=8__LOG2_N=8__LOG2_K=8__STREAM_MODE=allocate_and_post_on_different_streams__COMPUTE_MODE=unfused__ENABLE_MEMORY_CACHE=0](https://github.com/user-attachments/assets/31539bdb-2b0e-4ea4-8c52-dfca575e401c)

# 3. `stream_mode=post_on_different_streams`

Same results as in "2. `stream_mode=allocate_and_post_on_different_streams`"

# Related PRs
- #2656
- #2584
- #2401

Linked to item 1 of https://github.com/NVIDIA/Fuser/pull/2584#issuecomment-2238833771

**Comment by samnordmann** [comment]
cc @naoyam @wujingyue @kevinstephano

**Comment by samnordmann** [comment]
Let me know if I should provide a minimal reproducer and open an issue on torch repo

**Comment by naoyam** [comment]
Thanks @samnordmann. Yes, please create a repro. Just a minimum C++ unit test would be fine. Since this is not an nvFuser issue, it doesn't need to create anything like `Fusion`.

**Comment by kevinstephano** [comment]
Did you try running the matmul parts on 1-GPU separate from running multi-gpu to see if we see it there?  It's easier to isolate down the issue if it is also seen on 1-GPU.

**Comment by samnordmann** [comment]
I updated the comment with the new collected profiles. I'm getting cudaMalloc even on a single stream, both with `at::matmul` or `at::matmul_out` (contrarily to what I said yesterday during the meeting where I unfortunately overlooked le nsight profile)

**Comment by samnordmann** [comment]
I updated the issue description with the new collected profiles. I'm getting `cudaMalloc` even on a single stream, both with `at::matmul` or `at::matmul_out` (contrarily to what I said yesterday during the meeting where I unfortunately overlooked le nsight profile)

> Did you try running the matmul parts on 1-GPU separate from running multi-gpu to see if we see it there? It's easier to isolate down the issue if it is also seen on 1-GPU.

> Thanks @samnordmann. Yes, please create a repro. Just a minimum C++ unit test would be fine. Since this is not an nvFuser issue, it doesn't need to create anything like Fusion.

@kevinstephano the new reproducer is single-device
@naoyam the reproducer is purely pytorch

**Comment by samnordmann** [comment]
@naoyam I have provided new results and analysis. I see the same qualitative results. Changes (See #2682):
- This time I run on H100 as you suggested
-  I tried allocating on the same Stream as the one which the compute is posted to.
- I also provide results where we unfuse matmul into pointwise+reduction. This case shows that there is no allocation at all, as it should be. We can see comparatively that matmul_out performs an unnecessary allocation
- I fixed disabling the allocator cache (but I am not sure to see any difference on the profiles...)

**Comment by naoyam** [comment]
Is only 2.a the unexpected result?

**Comment by samnordmann** [comment]
> Is only 2.a the unexpected result?

yes

**Comment by samnordmann** [comment]
@naoyam as you requested in https://github.com/NVIDIA/Fuser/pull/2682#discussion_r1695581267, [I added a `cudaDeviceSynchronize` between allocation and compute](https://github.com/NVIDIA/Fuser/pull/2682/commits/5d5a22edc7dfb8920a29fda73276696377191ecd), but this doesn't change the observed behavior. For instance, look at the following plot for the case "2.a. `stream_mode=allocate_and_post_on_different_streams` and `compute_mode==matmul_out`" (on a v100)
![LOG2_M=8__LOG2_N=8__LOG2_K=8__STREAM_MODE=allocate_and_post_on_different_streams__COMPUTE_MODE=matmul_out__ENABLE_MEMORY_CACHE=1](https://github.com/user-attachments/assets/c2382743-d863-4a0f-963f-3515aaf35327)

**Comment by naoyam** [comment]
Looks like the actual matmul kernel is a splitk matmul, so the allocation is likely for its temporary work buffer, which is indeed necessary for executing the kernel. I'm not familiar how PyTorch manages these temporary buffers, but let's see what happens if we repeat the matmul iterations. I suppose these buffer spaces are specific to each stream, so I suspect these allocations shouldn't occur after the first iteration.

**Comment by samnordmann** [comment]
> Looks like the actual matmul kernel is a splitk matmul, so the allocation is likely for its temporary work buffer, which is indeed necessary for executing the kernel. 

makes sense

> what happens if we repeat the matmul iterations. I suppose these buffer spaces are specific to each stream, so I suspect these allocations shouldn't occur after the first iteration.

That's what I tried, and indeed, you're right, after the first iteration, the `cudaMalloc` disappeared.

To be more precise, I tried with three nested for-loop in total ( we added two new for-loop in [this commit](https://github.com/NVIDIA/Fuser/pull/2682/commits/b6aca8d3c36169c03472b1f4f0ba6373a67299b2)):
1) *Loop `I`, 4 iterations*: the inner-most for-loop, which was the only one present so far. At each iteration we post the compute on a different stream. 
2) *Loop `J`, 4 iterations*: we post the matmul compute, reusing the same streams in a round-robin fashion and the same I/O allocated buffers 
3) *Loop `L`, 2 iterations*: outermost for-loop, we reallocate new I/O, but keep reusing the same streams in a round-robin fashion.

In both cases, the cudaMalloc disappears, which most probably means that the allocator cache is coming into play and allows `matmul_out` to reuse the work buffers.

Here is a screenshot of the night profile, and the same screenshot annotated. Settings: V100, case "2.a. `stream_mode=allocate_and_post_on_different_streams` and `compute_mode==matmul_out`" (on a v100). 
![Screenshot 2024-07-31 at 12 42 18](https://github.com/user-attachments/assets/845158a9-b4b9-4691-a820-b9f1b19de2a5)
![Screenshot 2024-07-31 at 11 34 00](https://github.com/user-attachments/assets/067c2fa0-cd07-41dd-b14b-e25129ff4e29)


The conclusion is that **the at::matmul_out allocation is a one-time cost per stream** (thanks to the allocation cache). As far as the overlap technique is concerned:
1) We can keep using `matmul_out`
2) We need to look at the profile after one warm-up iteration
3) We need to limit the number of Streams we use.

I will work on this. I'm closing the issue for now.

_By the way, I think that the variable `PYTORCH_NO_CUDA_MEMORY_CACHING` doesn't work, I can't see any difference whether I set it or not... So I would be careful using that_

**Comment by jacobhinkle** [comment]
> By the way, I think that the variable `PYTORCH_NO_CUDA_MEMORY_CACHING` doesn't work, I can't see any difference whether I set it or not... So I would be careful using that

Could this be because the workspace is allocated by cublas and is not directly controlled by the pytorch caching allocator?

**Comment by naoyam** [comment]
https://pytorch.org/docs/stable/notes/cuda.html#cublas-workspaces
