### ISSUE TITLE
`FusionReductionWithTrivialReduction_CUDA` fails with compute-sanitizer

### ISSUE THREAD

**Issue by xwang233** [NVIDIA/Fuser#2930]
repro (pjnl-20240910):
```
NVFUSER_ENABLE=kernel_debug PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer bin/nvfuser_tests --gtest_filter='*FusionReductionWithTrivialReduction_CUDA*'
```

sample stacktrace:
```
========= Invalid __local__ write of size 16 bytes
=========     at void <unnamed>::loadGeneric<float, (int)4>(T1 *, T1 *)+0x830 in /opt/pytorch/nvfuser/__tmp_kernel_reduction_f0_c1_r0_g5.cu:2623
=========     by thread (3,4,0) in block (71,0,0)
=========     Address 0xfffa94 is misaligned
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x2dcdbf]
=========                in /usr/local/cuda/compat/lib.real/libcuda.so.1
=========     Host Frame:nvfuser::FusionExecutor::runFusion(nvfuser::KernelArgumentHolder&, nvfuser::LaunchParams const&, nvfuser::CompileParams, std::vector<at::Tensor, std::allocator<at::Tensor> >) [0x55f85e]
=========                in /opt/pytorch/nvfuser/bin/nvfuser_tests
=========     Host Frame:nvfuser::FusionKernelRuntime::runKernelWithInput(nvfuser::KernelArgumentHolder&, nvfuser::SegmentedGroup*) [0x721c9d]
=========                in /opt/pytorch/nvfuser/bin/nvfuser_tests
=========     Host Frame:nvfuser::FusionKernelRuntime::runSegmentsWithInputs(nvfuser::KernelArgumentHolder&) [0x72676c]
=========                in /opt/pytorch/nvfuser/bin/nvfuser_tests
=========     Host Frame:nvfuser::FusionKernelRuntime::runWithInputs(nvfuser::KernelArgumentHolder&) [0x726c49]
=========                in /opt/pytorch/nvfuser/bin/nvfuser_tests
```

line of code at `/opt/pytorch/nvfuser/__tmp_kernel_reduction_f0_c1_r0_g5.cu:2623`:
```cuda
template <typename scalar_t, int vec_size>
__device__ void loadGeneric(scalar_t* to, scalar_t* from) {
  // It would be really nice to use memcpy here, but one example was failing
  // with:
  //
  //  memcpy(to, from, vec_size * sizeof(scalar_t));
  //
  // Yet passing with:
  //
  // for(int i = 0; i < vec_size; i++){
  //   to[i] = from[i];
  // }

  switch (sizeof(scalar_t) * vec_size) {
    case 1:
      *reinterpret_cast<uchar1*>(to) = *reinterpret_cast<uchar1*>(from);
      break;
    case 2:
      *reinterpret_cast<uchar2*>(to) = *reinterpret_cast<uchar2*>(from);
      break;
    case 4:
      *reinterpret_cast<uint1*>(to) = *reinterpret_cast<uint1*>(from);
      break;
    case 8:
      *reinterpret_cast<uint2*>(to) = *reinterpret_cast<uint2*>(from);
      break;
    case 12:
      *reinterpret_cast<uint3*>(to) = *reinterpret_cast<uint3*>(from);
      break;
    case 16:
      *reinterpret_cast<uint4*>(to) = *reinterpret_cast<uint4*>(from);
      break;
  }
}
```
line 2623 is the `reinterpret_cast` line of `case 16` and `uint4`

**Comment by naoyam** [comment]
Thanks for reporting.

I'm not aware of any recent change that might affect this test. Not often, but I have run the tests with sanitizer sometimes and have never seen this error before. Maybe because of `-G`? I usually just used `--lineinfo`. I'll look into it.

**Comment by jacobhinkle** [comment]
Interesting that this doesn't fail with `NVFUSER_ENABLE=kernel_lineinfo`, only with `NVFUSER_ENABLE=kernel_debug`.

**Comment by naoyam** [comment]
This misaligned write actually happens even without sanitizer. I suppose there's a real problem, it was just masked by optimization.

@liqiangxl This seems to be happening inside `blockIterGroupedYdimReduce`. Could you please take a look? Here's my repro commandline:

```
NVFUSER_DISABLE=parallel_compile NVFUSER_DUMP=fusion_ir,cuda_to_file NVFUSER_ENABLE=kernel_debug PYTORCH_NO_CUDA_MEMORY_CACHING=1 compute-sanitizer bin/nvfuser_tests --gtest_filter='*FusionReductionWithTrivialReduction_CUDA*'
```

**Comment by xwang233** [comment]
> I suppose the offending `__local__` write is optimized away without `-G`.

Do you suggest we run compute-sanitizer CI jobs with `-G` or without?

**Comment by naoyam** [comment]
Validation of kernels with optimization is more important, so let's just use `--lineinfo`.

**Comment by liqiangxl** [comment]
sure

**Comment by liqiangxl** [comment]
The error happens when vectorized writing array of float stored in registers to shared memory, e.g.
```
loadGeneric(T* shared_memory, T* register_array) 
```
The `register_array` should be 
```
auto align_size = sizeof(T) * vec_size;
__align__(align_size) T inp[vec_size];
```
instead of 
```
T inp[vec_size];
```

**Comment by naoyam** [comment]
Interesting. Are you sure it's due to `register_array` even though the error is about writes not reads?

**Comment by liqiangxl** [comment]
> Interesting. Are you sure it's due to `register_array` even though the error is about writes not reads?

There is also write from shared meory to register array, e.g. `loadGeneric(T* register_array, T* shared_memory) `

For shared memory it is declared with `alignas(16) extern __shared__ char array[];`, so I think it is fine.
I am not sure if `register_array` is the only reason, but it at least it is a reason. After changing to `__align__(align_size) T inp[vec_size];`, the error is gone. I am planning to set a PR to make this change and see if there are other issues.
