### ISSUE TITLE
Error when installing this package.

### ISSUE THREAD

**Issue by namirinz** [NVIDIA/Fuser#2986]
I got an error when trying to install this package by running command.

pip install --pre nvfuser-cu121

Defaulting to user installation because normal site-packages is not writeable
Collecting nvfuser-cu121
  Using cached nvfuser_cu121-0.2.10.dev20240916.tar.gz (544 bytes)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Traceback (most recent call last):
        File "/home/b6410500238/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/b6410500238/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/b6410500238/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/scratch/slurm/b6410500238/2773/pip-build-env-dyndsppx/overlay/lib/python3.11/site-packages/nvidia_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/scratch/slurm/b6410500238/2773/pip-build-env-dyndsppx/overlay/lib/python3.11/site-packages/nvidia_stub/wheel.py", line 175, in download_wheel
          report_install_failure(distribution, version, None)
        File "/scratch/slurm/b6410500238/2773/pip-build-env-dyndsppx/overlay/lib/python3.11/site-packages/nvidia_stub/error.py", line 63, in report_install_failure
          raise InstallFailedError(
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************
      
      The installation of nvfuser-cu121 for version 0.2.10.dev20240916 failed.
      
      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.
      
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com nvfuser-cu121
      ```
      
      Here is some debug information about your platform to include in any bug
      report:
      
      Python Version: CPython 3.11.7
      Operating System: Linux 5.15.0-1042-nvidia
      CPU Architecture: x86_64
      Driver Version: 535.154
      CUDA Version: 12.2
      
      *******************************************************************************
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zasdfgbnm** [comment]
This error is reproducible:
```
      The installation of nvfuser-cu121 for version 0.2.10.dev20240916 failed.
      
      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.
      
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com nvfuser-cu121
      ```
      
      Here is some debug information about your platform to include in any bug
      report:
      
      Python Version: CPython 3.12.5
      Operating System: Linux 6.10.9-arch1-2
      CPU Architecture: x86_64
      Driver Version: 560.35
      CUDA Version: 12.6
```
cc @xwang233

**Comment by xwang233** [comment]
https://github.com/NVIDIA/Fuser?tab=readme-ov-file#installation Please check the installation section in readme. Nightly package `nvfuser-cu121` needs to be installed from nvidia pypi index `pypi.nvidia.com` and is not uploaded to public pypi.org. 

Besides, we only publish python3.10 packages for nvfuser. It may or may not work properly for your python 3.11 installations.
