### ISSUE TITLE
CollectiveBasedOverlapTest.ReduceScatterBasedPipeliningATenImplementation fails in nightly CI.

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#3051]
https://gitlab-master.nvidia.com/dl/pytorch/update-scripts/-/jobs/113547544#L2304

I've yet to find out when this started to show up. FYI, this test runs on 8xH100.

**Comment by samnordmann** [comment]
I am not able to reproduce the bug. I am running on a DGX 8*H100, with the same nccl version (in the pjnl container), and the same command as in the test
`mpirun --timeout 2400 --get-stack-traces --tag-output --report-state-on-timeout --allow-run-as-root -np 1 bin/test_multidevice --gtest_output=xml:TEST-report-test-multidevice.xml : -np 7 bin/test_multidevice`
runs successfully

**Comment by samnordmann** [comment]
Since it fails at the first gtest instance, it is probably nccl setup that throws this error, and not the unit test, which has been running successfully for several weeks now

**Comment by wujingyue** [comment]
Thanks for looking into this, Sam! This could indeed be an infra problem, so cc @xwang233. 

Looking at some more recent runs (https://gitlab-master.nvidia.com/dl/pytorch/update-scripts/-/jobs/113690044), the 8xH100 tests are apparently failing for other reasons...

**Comment by wujingyue** [comment]
Won't fix -- not reproducible.
