### ISSUE TITLE
`python_frontend::cleanup` call is resulting in a segfault during multi-gpu cluster usage

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#3093]
During cluster based Thunder runs, we are seeing segfaults coming from `python_frontend::cleanup` found [here](https://github.com/NVIDIA/Fuser/blob/8a36d29cd7941119d429416c30acde3eee92c137/csrc/python_frontend/python_bindings_extension.cpp#L16-L17).

Can we enable this selectively for our internal development until we can determine why the segfault is happening?  I could not produce a reproduction on a single node DGXH100.

**Comment by samnordmann** [comment]
https://github.com/NVIDIA/Fuser/pull/3109 is not exactly a fix but a useful debug tool to quickly disable the multidevice module at runtime

**Comment by kevinstephano** [comment]
Notes:

1. This was found on a specific cluster during cleanup of a test given that the user increases batch size until they see a failure condition like OOM or other failures caused by running out of memory that includes NCCL errors.
2. This suspicion is that some how the cleanup is corrupting or somehow double calling the cleanup function.
