### ISSUE TITLE
Dependencies on Pytorch library

### ISSUE THREAD

**Issue by Jiexin-Zheng** [NVIDIA/Fuser#31]
Hi, team nvfuser, i am an ai framework engineer. I know that nvfuser was firstly designed for Pytorch, now you pick the corresponding source code from pytorch as a standalone repository, do you plan to maintain it as an project with general support for ai frameworks besides pytorch? 
If so, how do you plan to decouple nvfuser from pytorch?

**Comment by kevinstephano** [comment]
We are not planning to decouple from Pytorch, in the near future, so closing for now.
