### ISSUE TITLE
Errors during _finalize_definition don't indicate the problematic op.

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#3190]
This made efforts like #3184 much harder. I had to examine all reshapes one by one and manually inferred the shapes. 

https://github.com/NVIDIA/Fuser/commit/88fb1626d13b19bd5041c23b240381d2f7ad7850 added a simplified example. It's easy to spot the error in that example because there's only one reshape and the shapes are constant. However, it's much harder to deal with large fusions like the one in #3184.

**Comment by wujingyue** [comment]
cc @kevinstephano because I don't know whom to start with :)

**Comment by wujingyue** [comment]
cc @rdspring1

**Comment by rdspring1** [comment]
Debug thoughts:
1. Use `gdb` with `catch throw` to get backtrace for failure case.
2. Add print statements at https://github.com/NVIDIA/Fuser/blob/main/csrc/python_frontend/fusion_state.cpp#L98

Enhancement thoughts:
1. Use try-catch in `FusionState::BuildFusionIr`.
2. Print `RecordFunctor` and error message in catch block.
