### ISSUE TITLE
Reshape/transpose operators in BFloat16 causing errors

### ISSUE THREAD

**Issue by cowanmeg** [NVIDIA/Fuser#3194]
I am seeing a strange bug where the datatype of a reshape and transpose ops is affecting the error of a much further downstream op. 

Cast output of linear0 from bfloat16->float before reshape/transpose, then cast back to bfloat16 before sdpa, note the casts should be redundant, and map to a pointwise scheduler
linear0 max error: 0.015625
          max relative error: 0.0062561
          failing elements: 0, 0% of tensor
linear0 max error: 0.0078125
          max relative error: 0.00294495
          failing elements: 0, 0% of tensor
sdpa max error: 0.000488281
          max relative error: 0.000289917
          failing elements: 0, 0% of tensor
sdpa max error: 0.000976562
          max relative error: 0.00050354
          failing elements: 0, 0% of tensor
linear1 max error: 0.00634766
          max relative error: 0.00524194
          failing elements: 0, 0% of tensor
linear1 max error: 0.00634766
          max relative error: 0.00524194
          failing elements: 0, 0% of tensor
dropout max error: 0.00705302
          max relative error: 0.00524198
          failing elements: 0, 0% of tensor
dropout max error: 0.00705302
          max relative error: 0.00524198
          failing elements: 0, 0% of tensor

No casting, reshape/transpose stay in bfloat16. From the preseg_fusion dump, the reshape/transpose are mapped to no-op scheduler. 
linear0 max error: 0.015625
          max relative error: 0.0062561
          failing elements: 0, 0% of tensor
linear0 max error: 0.0078125
          max relative error: 0.00294495
          failing elements: 0, 0% of tensor
sdpa max error: 0.000488281
          max relative error: 0.000289917
          failing elements: 0, 0% of tensor
sdpa max error: 0.000976562
          max relative error: 0.00050354
          failing elements: 0, 0% of tensor
**linear1 max error: 1.10844
          max relative error: 0.91536
          failing elements: 174249, 88.6276% of tensor
linear1 max error: 1.10844
          max relative error: 0.91536
          failing elements: 174249, 88.6276% of tensor
dropout max error: 1.2316
          max relative error: 0.91536
          failing elements: 158645, 80.691% of tensor
dropout max error: 1.2316
          max relative error: 0.91536
          failing elements: 158645, 80.691% of tensor**

Repro:
Checkout my fork, transformer_linear
$ git clone https://github.com/cowanmeg/Fuser.git --recursive
$ git checkout transformer_linear

$ mpirun -np 2 bin/test_multidevice --gtest_filter='DistributedTransformerTest.MultiheadAttention/__bfloat'

Note: Comments are in function `mha_qkv` of where to add/remove casts to observe behavior.

**Comment by wujingyue** [comment]
Thanks for looking into this! It's tempting to dismiss validation errors by bumping up the threshold. I'm so glad you didn't do that and you likely found a real bug! 

Can you try to reduce the repro? I'm fine with it being based on an MHA, but https://github.com/NVIDIA/Fuser/compare/main...cowanmeg:Fuser:transformer_linear seems to contain extra changes that don't seem to be needed for the repro. From your description, it seems possible to have a repro patch that simply changes one matmul+add to linear and makes the numbers blow up. Is that right?

**Comment by cowanmeg** [comment]
Here is a smaller standalone test

```
TEST_F(DistributedTransformerTest, repro) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());
  auto dtype = DataType::BFloat16;
  const auto mesh = DeviceMesh::createForNumDevices(D);
  at::ScalarType at_dtype = data_type_to_aten(dtype);

  TensorView* x = makeContigConcreteTensor({D, B * S, 3 * E / D}, dtype);
  TensorView* w1 = makeContigConcreteTensor({D, E, E / D}, dtype);
  for (auto tv : {x, w1}) {
    tv->setDeviceMesh(mesh);
    tv->axis(0)->parallelize(ParallelType::DIDx);
  }

  fusion->addInput(x);
  fusion->addInput(w1);

  // x = castOp(DataType::Float, x);
  TensorView* qkv_cat =
      reshape(x, {D, B * S, 3 * E / D}, {D, B, S, 3 * E / D});
  std::vector<TensorView*> qkv = chunk(qkv_cat, 3, -1);
  for (auto i : c10::irange(3)) {
    qkv[i] = reshape(qkv[i], {D, B, S, E / D}, {D, B, S, H / D, E / H});
    qkv[i] = transpose(qkv[i], 2, 3);
    qkv[i] = castOp(dtype, qkv[i]);
    qkv[i]->setDeviceMesh(mesh);
    qkv[i]->axis(0)->parallelize(ParallelType::DIDx);
  }
  SdpfaFwdResult sdpa = sdpfa_fwd(
      qkv[0],
      qkv[1],
      qkv[2],
      IrBuilder::create<Val>(0.0),
      IrBuilder::create<Val>(true),
      IrBuilder::create<Val>(kSdpaScale));
  TensorView* sdpa_output = sdpa.output;
  TensorView* sdpa_transpose = transpose(sdpa_output, 2, 3);
  TensorView* sdpa_reshape =
      reshape(sdpa_transpose, {D, B, S, H / D, E / H}, {D, B * S, E / D});
  TensorView* local_matmul1 = matmul(sdpa_reshape, transpose(w1, 1, 2));
  TensorView* matmul1 = sum(local_matmul1, {0});

  fusion->addOutput(sdpa_output);
  fusion->addOutput(matmul1);

  const auto options =
      at::TensorOptions().dtype(at_dtype).device(communicator_->device());
  auto x_ = at::randn({B * S, 3 * E}, options) * kParamScale;
  auto w1_ = at::randn({E, E}, options) * kParamScale;

  at::manual_seed(getATenRandomSeed());
  auto qkv_ = x_.view({B, S, 3 * E}).split(E, 2);
  for (auto i = 0; i < 3; i++) {
    qkv_[i] = qkv_[i].reshape({B, S, H, E / H}).transpose(1, 2);
  }
  auto sdpa_out_ = at::_scaled_dot_product_flash_attention(
      qkv_[0], qkv_[1], qkv_[2], 0.0, true, false, kSdpaScale);
  auto sdpa_ = std::get<0>(sdpa_out_);
  auto y_ = sdpa_.transpose(1, 2).reshape({B * S, E});
  auto matmul1_ = at::matmul(y_, w1_.transpose(0, 1));

  std::vector<c10::IValue> inputs = {
      shardTensor(x_.view({B*S, 3, E}), 2, mesh).view({1, B*S, 3 * E / D}),
      shardTensor(w1_, 1, mesh)};

  std::vector<at::Tensor> expected_outputs = {
      shardTensor(sdpa_, 1, mesh),
      matmul1_};

  FusionExecutorCache fec(std::move(fusion));
  at::manual_seed(getATenRandomSeed());
  auto outputs = fec.runFusionWithInputs(inputs);
  validate(expected_outputs, outputs, {0.02, 0.02});
}
```

Adding the castOp of x, will removes the error. 

With cast
output[0] max error: 0
          max relative error: 0
          failing elements: 0, 0% of tensor
output[0] max error: 0
          max relative error: 0
          failing elements: 0, 0% of tensor
**output[1] max error: 0.000244141
          max relative error: 0.0062561
          failing elements: 0, 0% of tensor
output[1] max error: 0.000244141
          max relative error: 0.0062561
          failing elements: 0, 0% of tensor**


Without cast
output[0] max error: 0
          max relative error: 0
          failing elements: 0, 0% of tensor
output[0] max error: 0
          max relative error: 0
          failing elements: 0, 0% of tensor
**output[1] max error: 0.0375977
          max relative error: 0.960938
          failing elements: 136, 0.0691732% of tensor
output[1] max error: 0.0375977
          max relative error: 0.960938
          failing elements: 136, 0.0691732% of tensor**
