### ISSUE TITLE
Definition-time `simplifyExpr` with concretization axioms

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#320]
With dynamic resize, we have implemented a very basic system of trying to prove propositions at definition time (before concretization) if we have some constant inputs; for example, if we have constant pad values that sum to 2, we know that the padded extent will be `>= 2` even if we don't know the input extent. This allows us to avoid using symbolic operations in some common cases. Other ops like `cat` will pad using complicated expressions, so the first point of this issue is that **it might be advantageous to have more sophisticated theorem proving during definition**.

Currently NVFuser possesses a powerful system for simplifying expressions: `simplifyExpr`. It implements iterative term rewriting, starting with a provided set of assumptions that defaults to a collection of "axioms" from `IrContainer::axioms()` which are a collection of `Bool`s that are known to be `True`: namely this attests that parallelization dimensions are positive and thread and block IDs are non-negative.

There are more axioms that could empower this system. For example we know that any fusion input extents should be non-negative. During concretization, we analyze individual ops and look at scalars, extract their values and make a determination. These decision points are then predicates that can be considered constant for that concretization. For example, if we determine that the extent of a pad op is equal to 1, that will be true for any set of inputs sharing that concretization. The second point of this issue is in the other direction: that **axioms accumulated during definition and concretization might be useful during lowering**.

## Approaches

I think one way to enable this flexibly is to add the ability to append axioms to `IrContainer` by adding an `attestAxiom` method. Creation of a `TensorView` would add an axiom that each extent is non-negative. We can then use `simplifyExpr` directly during definition or lowering. We could then also sprinkle in more axioms to aid the system. Alternatively, we could just override `axioms()` for `Fusion` in order to also return the input extent nonnegative axioms, but this is less flexible.

**Comment by jacobhinkle** [comment]
cc @zasdfgbnm

**Comment by zasdfgbnm** [comment]
Love this idea.

**Comment by zasdfgbnm** [comment]
I think I will need the assumptions that all extents are non-negative in order to simplify vectorization factor. Self assign.

**Comment by zasdfgbnm** [comment]
@jacobhinkle Am I understanding correct that expr simplifier might also potentially be useful for analysis in concretization? If this is the case, I think we should have a pre-conretization pass to replace all equal extents with the same `Val*`, then another pre-concretization pass to insert axioms like `extent >= 0`, and during concretization, we should find all zero extents and convert their extents to compile time `0`, remove corresponding axioms, and convert all other axioms as `extent > 0`. If not, we should have a pre-conretization pass to replace all equal extents, and a post-concretization pass to insert `extent > 0`.

**Comment by jacobhinkle** [comment]
Yeah that's possible to do. The new pass seems very closely related to #382. In terms of new axioms, we could indeed do these after definition instead of during. I am thinking it may be useful to do a "partial concretization" pass, since one of the reasons I was thinking of this is for reshape: if we can prove that certain extents line up we can do the decomposition into `Keep`/`Squeeze`/`Merge` even before seeing inputs in some cases.

**Comment by zasdfgbnm** [comment]
Are you talking about detecting things like `view(tv, {i1, i2}, {i1*i2})`, if we can analyze it symbolically, then we don't need to know the actual value of `i1` and `i2` in order to know this is a merge. Generally, if you don't need the distributivity, you don't care about the sign of these values, see:
https://github.com/NVIDIA/Fuser/blob/8fbb7989ac3d270d9bb4bd4dc38bc839679d1889/csrc/expr_simplifier.h#L444-L460
So I don't think you need any assumption about the extents are non-negative. So probably in this case, we can just fill `extent > 0` after concretization.

**Comment by jacobhinkle** [comment]
Sorry to not be so clear here: in reshape a value of -1 means to fill in with whatever value is needed to preserve the number of elements. It can appear in at most one position but could be any of them, so step one is convert all inputs to where statements checking for that condition. That may challenge the proofs

**Comment by zasdfgbnm** [comment]
Could you post an example here? I expect `-1` should be replaced as things like `size1 * size2 * size3 / size4 / size5`? Where is the "where statement"?

**Comment by jacobhinkle** [comment]
Oh i meant in case the value was dynamic then we wouldn't know its value until passed. One way to address that is to require any symbolic reshape inputs to be constant.

**Comment by jacobhinkle** [comment]
For example, let's say the Fusion was defined like
```c++
auto tv0 = makeSymbolicTensor(2);  // [ iS0{i0}, iS1{i1} ]
fusion->addInput(tv0);
auto s0 = IrBuilder::create<Int>();
auto s1 = IrBuilder::create<Int>();
auto tv1 = reshape(tv0, {s0, s1});
fusion->addOutput(tv1);
```
The Fusion is dynamic so `tv1` has `Symbolic` rfactor domain `[ ?S2{i2}, ?S3{i3} ]` for some expressions `i2` and `i3`; let's say `i2=s0` and `i3=s1`. This is a problem if the user passes `s0, s1 = 2, -1` in which case the output should be size `2, (i0 * i1) / 2` and we should check that `i0*i1 % 2 == 0` instead of `s0 * s1 == i0 * i1`. This kind of usage can be disallowed by checking at concretization for -1, or it can be allowed by setting the extent of `tv1` at definition to `[ ?S2{where(i2 == -1, (i0 * i1) / i3, i2)}, ?S3{where(i3 == -1, (i0 * i1) / i2, i3)}]`. If we allow it, we would still probably need to check that there are not multiple -1s at concretization...

If we disallow inputs of `-1` we can just resolve the `-1` expressions at definition and then the output expressions are simple again.

**Comment by jacobhinkle** [comment]
> > detecting things like `view(tv, {i1, i2}, {i1*i2})`
> 
> Yeah exactly. That particular case is pretty simple since we always know how to decompose a reshape with a single output dimension. In the general case where you have `m` input sizes `s_i` and `n` output sizes `t_j` you can look at pairwise combinations of cumprod of the dimensions to form an `m` by `n` matrix of equations. If you can prove that the first `k-1` of those are false but `k` is true, then you can go ahead merge/split (or keep). Then go from other side and repeat. If you can prove any of the dimensions is 1, you can determine if it's a broadcast, etc.
> 
> It might not be worth the hassle but it seems like a common use case of reshape is to essentially just split or merge a single axis/pair of axes and this is one way to detect that. Another is a bit more brute force: just detect mul and div expressions and check for a few common cases like in #418.

**Comment by zasdfgbnm** [comment]
I do think resolving `-1` at definition time makes more sense, but I am not sure if this is related to what I am trying to figure out.

I am trying to figure out:
1. Will the assumption `extent >= 0` be useful for concretization analysis?
2. After concretization, can we assume `extent > 0`?

For 1, from the current information, what is needed in the analysis is mostly divisibility and factorization analysis, which does not care if the number is positive or not. So I think we do not need 1, so how to handle `-1` is not related.

For 2, I think we are moving towards that direction, it is just a matter of timeline and priority.

BTW, another unrelated topic: I don't think we are able to analysis view with zero extent. For example, `torch.empty((0, 6, 0)).view((0, 0))`, should I merge the `6` lhs or rhs? There is no deterministic answer. Probably with zero size tensors, we should just drop their definitions and replace it with a `FullOp`?
