### ISSUE TITLE
IterDomain cannot be both a broadcast and rfactor domain

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#346]
The `pad` op expands root `IterDomain`s by calling `resize` and marking them as rfactor IDs. The `IterType` of the resized `IterDomain` will be `Broadcast` if the extent is 1, which happens for example if the pad widths are negative and sum to one less than the input extent. In such cases, we hit an assertion in the `IterDomain` constructor that an rfactor domain cannot be marked `Broadcast`. There is currently a commented case that triggers this error in the `DynamicPadShmoo_CUDA` test in #258, but a minimal example is:
```c++
// Test setting an rfactor domain that is of IterType Broadcast
TEST_F(NVFuserTest, FusionBroadcastRFactorID_CUDA) {
  Fusion fusion;
  // Try to create an extent-1 Broadcast IterDomain that is marked rfactor
  IterDomainBuilder(fusion.zeroVal(), fusion.oneVal())
          .is_rfactor_domain(true)
          .iter_type(IterType::Broadcast)
          .build();
  // The above throws the following exception in .build():
  // IterDomain cannot be both a broadcast and rfactor domain.
  // Exception raised from IterDomain at /opt/pytorch/nvfuser/csrc/ir_nodes.cpp:2105
}
```

**Comment by naoyam** [comment]
Talked about this with @csarofeen a couple of weeks ago. The assertion is primarily just there because there's supposed to be no such case. It should be fine to remove the assertion now that we do have cases like you mentioned.

**Comment by jacobhinkle** [comment]
Sounds good. I'll replace it with a comment in #258 before merging.

**Comment by naoyam** [comment]
There may be other things to change, so it might make sense to create a new PR just for the change.

**Comment by jacobhinkle** [comment]
I rolled it into #258 since nothing else seemed to be needed for that test case.
