### ISSUE TITLE
Add `right_shift_arithmetic` op

### ISSUE THREAD

**Issue by kevinstephano** [NVIDIA/Fuser#361]
We are missing the operation `right_shift_arithmetic` that differs from `bitwise_right_shift` because it preserves the sign bit.

https://en.wikipedia.org/wiki/Arithmetic_shift

![image](https://github.com/NVIDIA/Fuser/assets/8293715/67ffb692-4c61-4148-924a-e9d8f27e900b)

**Comment by rdspring1** [comment]
Apparently, the right shift operator in CPP implements `right shift arithmetic`. I'm assuming CUDA has the same behavior.

> For negative a, the value of a >> b is implementation-defined (in most implementations, this performs arithmetic right shift, so that the result remains negative).
https://en.cppreference.com/w/cpp/language/operator_arithmetic
