### ISSUE TITLE
Performance Track

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#578]
moved to google doc.

**Comment by liqiangxl** [comment]
Initial test results on A100 using code at `Date:   Mon Jul 10 14:01:02 2023 -0700` with commit `3a850fffe9af36ef4f170a0f2d89bbb38313f7d0`. 
The bandwidth is based on kernel execution time reported by **torch.profiler and NVFUSER_DUMP**
**Case-1, Softmax Forward using Inner Persistent Heuristics.** 
`Tested on A100, fp16, vectorized by 8, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256]`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/23001820-80ef-41eb-9016-d8cd9cae202d)

`Tested on A100, fp16, vectorized by 4, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 4`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/01556d74-c8a5-4794-82f3-28cf3e34d0f9)

`Tested on A100, fp16, vectorized by 2, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 6`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/4517f214-6bb4-496a-8728-df4b706c96e4)


**Case-2, Softmax Backward using Inner Persistent Heuristics.** 
`Tested on A100, fp16, vectorized by 8, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256]`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/bab0d7da-52cc-4e8d-b57b-311303b78a9d)

`Tested on A100, fp16, vectorized by 4, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 4`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/a3f3fc01-4b3b-4d76-9c5b-ceffb3dc865e)

`Tested on A100, fp16, vectorized by 2, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 6`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/de5fd4c7-d96d-421c-9205-4627bf6eee62)


**Case-3, Layer Norm Forward using Inner Persistent Heuristics.** 
`Tested on A100, fp16, vectorized by 8, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256]`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/b64e0740-835d-44ea-afb5-aa7e9302c9b7)

`Tested on A100, fp16, vectorized by 4, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 4`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/ff3fadec-fbff-4de4-bfde-c1c2604737ea)

`Tested on A100, fp16, vectorized by 2, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 6`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/9594c2bc-ca9f-49f1-856d-213b45ed3bc1)

**Case-4, Layer Norm Backward using Combined InnerOuter Persistent Heuristics.** 
`Tested on A100, fp16, vectorized by 8, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256]`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/72dea00e-5e67-4ccf-bbf7-3537e99c15dd)

`Tested on A100, fp16, vectorized by 4, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 4`

`Tested on A100, fp16, vectorized by 2, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 6`

**Case-5, scale_mask_softmax_dropout using Inner Persistent Heuristics.** 
`Tested on A100, fp16, vectorized by 8, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256]`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/511d9d94-b033-4863-aab4-b21a05c9e5a0)

`Tested on A100, fp16, vectorized by 4, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 4`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/5504461b-394f-4ede-b22d-175a622b69bb)

`Tested on A100, fp16, vectorized by 2, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 6`
![image](https://github.com/NVIDIA/Fuser/assets/116412316/4294da0c-933a-4677-b1ae-8109c4d36f8c)


**Case-6, bias_dropout_add_layer_norm using Inner Persistent Heuristics.** 
`Tested on A100, fp16, vectorized by 8, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256]`


`Tested on A100, fp16, vectorized by 4, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 4`

`Tested on A100, fp16, vectorized by 2, batch size is 16 x SMs, Hidden sizes are 128 x [1, 2, 3, ..., 256] - 6`

**Comment by naoyam** [comment]
Can you please add more descriptions about the actual issues we discussed?

**Comment by naoyam** [comment]
Thanks for the update, but please document what we discussed about *each benchmark*. For example, what did we find for each benchmark? What is the main issue? What's our plan if any?

**Comment by liqiangxl** [comment]
Results on H100.
Case-1, Softmax Forward using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/e2e89535-edb0-4956-ba6e-040958a40b3f)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/0e0ed420-a3cc-4f75-bcc1-11bdf5bfc361)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/cbdfc25d-2db8-42e1-b941-3bb40ee59eb3)

Case-2, Softmax Backward using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/cc20d05d-2786-4961-a524-b6e34e6b945d)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/a05a73df-82c0-458e-820e-8d2069afd55d)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/4c23a678-c2de-4ce6-93d5-a84d5b774b4f)

Case-3, Layer Norm Forward using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/575b77e8-8a51-409e-a30b-7df07f3b45c6)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/2a0566fb-1a8b-461a-b786-26b04d46892c)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/e39a3d28-4fc7-44b9-878b-c29d8ca70199)

Case-4, Layer Norm Backward using Combined InnerOuter Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/03e1b27c-50b1-4998-9416-fc73fc5cf453)

Case-5, scale_mask_softmax_dropout using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/bfe6cc81-5ac5-4309-b6c2-658288af3e34)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/8b962a04-ec29-446f-bfdc-58e0602fac59)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/e0b5a665-2831-4b16-bdd1-e2a10b14922f)

Case-6, bias_dropout_add_layer_norm using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/2b74ab44-b1a6-4292-b5ff-562b2b1f8fef)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/a9fe4389-1c38-460e-b66d-8ccb0f53a17b)
![image](https://github.com/NVIDIA/Fuser/assets/116412316/d3a0aa86-a6ac-4886-8fc0-865f90f05598)

**Comment by liqiangxl** [comment]
Results on A100 with small batch size of 8. These are small latency bound cases. The bandwidth utilizations are smaller than 10%.

Case-1, Softmax Forward using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/22666793-5747-4db1-8931-66db66842106)
Case-2, Softmax Backward using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/310d8f48-143f-4068-94cf-9ae411a34bb4)

Case-3, Layer Norm Forward using Inner Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/585e0fc6-d8f3-4191-a074-3fcc0a41ec80)

Case-4, Layer Norm Backward using Combined InnerOuter Persistent Heuristics.
![image](https://github.com/NVIDIA/Fuser/assets/116412316/8edabd1e-c5ab-4685-b073-41629914bd5e)

Case-5, scale_mask_softmax_dropout using Inner Persistent Heuristics.
Case-6, bias_dropout_add_layer_norm using Inner Persistent Heuristics.
