### ISSUE TITLE
Dependency on NCCL/UCC is implicit in the build

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#608]
With our recent added support in distributed primitives, we introduced dependency against NCCL/UCC in our code base.

https://github.com/NVIDIA/Fuser/tree/main/csrc/multidevice
https://github.com/NVIDIA/Fuser/blob/fb9845e728136bc2ee7fd5b924440896303c1334/CMakeLists.txt#L140-L144

This part is not well tested against various build of pytorch (pytorch build with `USE_DISTRIBUTED=0` have been causing issue: i.e. https://github.com/NVIDIA/Fuser/pull/598#issuecomment-1639808010).

More over, the dependency on NCCL/UCC is currently required I believe. Which arguably isn't necessary.

A couple actionable items:
1. We should have our source and build file better organized and allow build like `USE_MULTIDEVICE=0` to avoid dependency on NCCL/UCC and future libraries required for multi device support.
2. Explicit documentation in the build guide and refactor on build system to allow easy installation of dependencies.

**Comment by wujingyue** [comment]
I believe this has been fixed with the NVFUSER_DISTRIBUTED macro. Please re-open it otherwise.
