### ISSUE TITLE
Multidevice build failure with gloo

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#612]
```
/home/nmaruyama/nvdl/nvfuser/rel2/third_party/gloo/gloo/math.h:20:22: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
  for (auto i = 0; i < n; i++) {
                   ~ ^ ~
/home/nmaruyama/nvdl/nvfuser/rel2/third_party/gloo/gloo/math.h:35:22: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
  for (auto i = 0; i < n; i++) {
                   ~ ^ ~
/home/nmaruyama/nvdl/nvfuser/rel2/third_party/gloo/gloo/math.h:50:22: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
  for (auto i = 0; i < n; i++) {
                   ~ ^ ~
/home/nmaruyama/nvdl/nvfuser/rel2/third_party/gloo/gloo/math.h:65:22: error: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
  for (auto i = 0; i < n; i++) {
```

This doesn't seem to happen when the gloo that comes as a submodule of PyTorch is used.

**Comment by samnordmann** [comment]
In my opinion we can stick for now to using gloo through PyTorch submodule

**Comment by samnordmann** [comment]
> Then why we have our own submodule? Isn't it meant to be used instead of the other one?

I don't know why, as far as I am concerned we don't need it. Also, in my opinion GLOO should not be the targeted backend for now and the future, we should prioritize UCC and NCCL

**Comment by jjsjann123** [comment]
we include some pytorch headers in our multidevice, which include gloo header.
PyTorch doesn't ship/package gloo with it, so we just need some way to find the header, hence the submodule.

**Comment by samnordmann** [comment]
> we include some pytorch headers in our multidevice, which include gloo header. PyTorch doesn't ship/package gloo with it, so we just need some way to find the header, hence the submodule.

What Gloo header are you referring to? Is it `torch/csrc/distributed/c10d/ProcessGroupGloo.hpp` ? I don't see any other one, am I missing smth ?

**Comment by jjsjann123** [comment]
Yes. `torch/csrc/distributed/c10d/ProcessGroupGloo.hpp` includes a bunch of other gloo headers and they are just nowhere to be found...

**Comment by zasdfgbnm** [comment]
We already added gloo as submodule. A better approach is to make a separate library to hide all dependencies on gloo, ucc, nccl, etc., so that nvfuser could just link to this separate library. See discussion https://github.com/NVIDIA/Fuser/pull/797#discussion_r1313380412
