### ISSUE TITLE
Issues/TODOs related to pipeline parallelism and multidevice support

### ISSUE THREAD

**Issue by samnordmann** [NVIDIA/Fuser#623]
Here is a list of issues/todos related to pipeline parallelism and multidevice support. Most of these points come from comments on this PR https://github.com/NVIDIA/Fuser/pull/483

# Multidevice support:

- [x] **Implement multi node support.** For now we only support devices on the same node
- [ ] **Implement asynchronous non-blocking collective communications.** For now, the only communications are blocking p2p send receive (we wait for completion right after posting the operation)
- [ ] #639
- [ ] **add multidevice tests in CI.**
- [ ] **measure performance of collectives**

# Pipeline/task parallelism

- [ ]  **Separate the pipeline logic and the multidevice support.** The pipeline parallelism (or task parallelism) can be reused for other applications.
    - class `PipelineStage` and `PipelineVal` and `PipelineCommunication`, maybe also `PipelinePrinter`, should be in `ir/` directory
    - `ir/` directory should be self contained, and should not have dependency on `multidevice/` directory
[discussion1](https://github.com/NVIDIA/Fuser/pull/483#discussion_r1242732963), [discussion2](https://github.com/NVIDIA/Fuser/pull/483#discussion_r1242759055)
- [ ]  **Make partition of DAG hierarchical/composable/recursive.** Design and implement an interface to partition a DAG into subgraphs with different level of granularity, without assuming how these partition will be used. Build out utilities for operating on these partitions. [discussion](https://github.com/NVIDIA/Fuser/pull/483#discussion_r1242759055)
- [ ] **Make the partitionning deeply integrated into fusion definition.** The pipeline descriptor should be owned by the fusion, and not be a separate thing sitting on the side, as in the current implementation. For example, we should be able to do `val->getPipelineStage()` , `val->addToPipelineStage(...)`, `val1->getPipelineStage()->mergeWith(val2->getPipelineStage())`, etc. for a `Val*`.
[discussion1](https://github.com/NVIDIA/Fuser/pull/483#discussion_r1253372845 ) [discussion2](https://github.com/NVIDIA/Fuser/pull/483#discussion_r1254642102)

# Communicator
- [ ] we need to think about how/where to instantiate a communicator in nvFuser, and what we expect from the user in the front-end. Since we get WORLD_SIZE from the communicator, it might be used even at the scheduling step https://github.com/NVIDIA/Fuser/pull/797#discussion_r1316524894
- [ ] **test UCC, GLOO and MPI ProcessGroup's backends.** Only NCCL has been tested for now
- [ ] **Link with UCC**, and/or openmpi. Maybe also NVshmem. Dockerize.

# Build/linkage
- make a separate library to hide all dependencies on gloo, ucc, nccl, etc., so that nvfuser could just link to this separate library. https://github.com/NVIDIA/Fuser/pull/797#discussion_r1313380412

# Utility functions

- [ ] Reimplement the Pipeline’s method:
      
   ```cpp
   /* returns a Fusion copied from the originalFusion but
              with I/O as the stage's I/O */
         std::unique_ptr<Fusion> Pipeline::stageToFusion(PipelineStage*& stage) const
   ```
        
   For now, we copy entirely the original fusion and then only change the inputs and outputs. It should be optimized by copying only the IRs needed for the traversal between the stage’s I/O. 
        
- [ ] (see [discussion](https://github.com/NVIDIA/Fuser/pull/483#discussion_r1254617189)) Implement a function
        
   ```cpp
   std::vector<shape_type> inferShape(
     std::vector<Val*> target_vals,
     const std::vector<shape_type> inputs,
      Fusion* fusion)
   ```
   that infer the shape for some vals `target_vals` given a fusion and some concrete `inputs`. `shape_type` is whatever type is usually used for shapes.

   This utility function would be used in the multidevice executor for allocating recv buffers when receiving tensors from other devices (these tensors are outputs of the previous stage and inputs of the next stage). What we do for now, is simply to allocate buffers for every inputs/outputs for every stage, which makes a lot of **garbage allocation.** Moreover, the allocation space is computed by running the fusion, through the following function (in `csrc/kernel_cache.h` )
        
   ```cpp
   //! Allocate the outputs of the Fusion given inputs
   //! TODO: re-implement
   std::vector<at::Tensor> FusionExecutorCache::allocOutputSpace(
      const at::ArrayRef<c10::IValue>& inputs) {
         return runFusionWithInputs(inputs);
   }
   ```
   This causes **garbage computation**.
        
- [ ] add a function
        
   ```cpp
   void PipelineStageDescriptor::addRange(Val* start, Val* end, Fusion* fusion)
   ```
        
   to add to a Pipeline Stage a range of a `fusion` (defined by the DAG traversal between `start` and `end`) rather than adding the `Val`s one by one as is currently done with the method void `void addVal(std::vector<Val*> vals)`

**Comment by wujingyue** [comment]
Thanks for the writing these down! I wasn't aware of this umbrella bug, but apparently the issues mentioned here have been fixed or obsolete. If they are not, feel free to file more specific issues.
