### ISSUE TITLE
Failures in `test_torchscript.py` using PyTorch main

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#624]
CI is currently failing since it uses `main` on PyTorch. Recently a change was merged to PyTorch (https://github.com/pytorch/pytorch/pull/105072) that fixes a bug where importing `jit_metaprogramming_utils` caused the default dtype to be set to `torch.float64` instead of the default `torch.float32`. This is a welcome change since that global change interfered with other tests. After this, we should be able to safely run `pytest python_tests/` without hacky changes to enforce the default "default" dtype.

Unfortunately some of the tests in `test_torchscript.py` broke with this change; namely `test_category_rule`, but also some others (listed below):
- `test_category_rule`
- `test_alias_pass_fix`
- `test_conv2d_bias`
- `test_flatten`
- `test_index_select_shape_expression`
- `test_linear`
- `test_nested_view`
- `test_shape_expression`
- `test_squeeze`
- `test_squeeze_negative_dim`
- `test_squeeze_zero`
- `test_unsqueeze`
- `test_view`
- `test_view_copy_graph_guard`
- `test_view_copy_graph_guard_double_fusion`

Most of these are not fixed by setting the default dtype back to `torch.float64`. For example `test_conv2d_bias` fails at `self.assertGraphContains(graph, FUSION_GROUP, True)`. It seems like the graph changed significantly: on nvfuser a1395f75db with PyTorch `2.1.0a0+gite132f09` we have
```
python_tests/test_torchscript.py::TestCudaFuser::test_conv2d_bias graph(%x.1 : Tensor,
      %w.1 : Tensor,
      %bias.1 : Tensor):
  %3 : int[] = prim::Constant[value=[1, 1]]()
  %4 : int[] = prim::Constant[value=[0, 0]]()
  %5 : int = prim::Constant[value=1]()
  %6 : NoneType = prim::Constant()
  %o.1 : Tensor = aten::conv2d(%x.1, %w.1, %6, %3, %4, %3, %5) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4117:16
  %8 : bool = prim::CudaFusionGuard[types=[Float(4, 2, 2, 2, strides=[8, 4, 2, 1], requires_grad=0, device=cuda:0), Float(2, strides=[1], requires_grad=0, device=cuda:0)]](%o.1, %bias.1)
  %9 : Tensor = prim::If(%8)
    block0():
      %10 : Tensor = prim::CudaFusionGroup_0[cache_id=0](%o.1, %bias.1)
      -> (%10)
    block1():
      %11 : Function = prim::Constant[name="fallback_function", fallback=1]()
      %12 : (Float(4, 2, 2, 2, strides=[8, 4, 2, 1], requires_grad=0, device=cuda:0)) = prim::CallFunction(%11, %o.1, %bias.1)
      %13 : Float(4, 2, 2, 2, strides=[8, 4, 2, 1], requires_grad=0, device=cuda:0) = prim::TupleUnpack(%12)
      -> (%13)
  return (%9)
with prim::CudaFusionGroup_0 = graph(%0 : Float(4, 2, 2, 2, strides=[8, 4, 2, 1], requires_grad=0, device=cuda:0),
      %1 : Float(2, strides=[1], requires_grad=0, device=cuda:0)):
  %2 : int = prim::Constant[value=-1]()
  %3 : Float(2, 1, strides=[1, 1], requires_grad=0, device=cuda:0) = aten::unsqueeze_copy(%1, %2)
  %4 : Float(2, 1, 1, strides=[1, 1, 1], requires_grad=0, device=cuda:0) = aten::unsqueeze_copy(%3, %2)
  %5 : Float(4, 2, 2, 2, strides=[8, 4, 2, 1], requires_grad=0, device=cuda:0) = prim::add_optional(%0, %4)
  %6 : Float(4, 2, 2, 2, strides=[8, 4, 2, 1], requires_grad=0, device=cuda:0) = aten::relu(%5) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4118:19
  return (%6)
```
But with current TOT pytorch `2.1.0a0+git232b96b` I am seeing
```
python_tests/test_torchscript.py::TestCudaFuser::test_conv2d_bias graph(%x.1 : Tensor,
      %w.1 : Tensor,
      %bias.1 : Tensor):
  %3 : int[] = prim::Constant[value=[1, 1]]()
  %4 : int[] = prim::Constant[value=[0, 0]]()
  %5 : int = prim::Constant[value=1]()
  %o.1 : Tensor = aten::conv2d(%x.1, %w.1, %bias.1, %3, %4, %3, %5) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4117:16
  %7 : Tensor = aten::relu(%o.1) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:4118:19
  return (%7)
```

**Comment by jjsjann123** [comment]
Thanks for investigating this.

So the issue with `test_category_rule` is that TorchScript is giving us a wrong graph where the dtype of tensor is marked incorrectly.
I was seeing this graph, even though the second tensor feed to the compiled graph is a `double`, instead of `float`
```
[DUMP graph_fuser.cpp:2509] Before Fusion:
[DUMP graph_fuser.cpp:2509] graph(%x.1 : Tensor,
[DUMP graph_fuser.cpp:2509]       %z.1 : float):
[DUMP graph_fuser.cpp:2509]   %2 : int = prim::Constant[value=1]()
[DUMP graph_fuser.cpp:2509]   %3 : Tensor = prim::profile[profiled_type=Long(4, 8, 32, 32, strides=[8192, 1024, 32, 1], requires_grad=0, device=cuda:0), seen_none=0](%x.1)
[DUMP graph_fuser.cpp:2509]   %o.1 : Tensor = aten::add(%3, %z.1, %2) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:893:20
[DUMP graph_fuser.cpp:2509]   %5 : Tensor = prim::profile[profiled_type=Float(4, 8, 32, 32, strides=[8192, 1024, 32, 1], requires_grad=0, device=cuda:0), seen_none=0](%o.1)
[DUMP graph_fuser.cpp:2509]   %o.5 : Tensor = aten::abs(%5) # /opt/pytorch/nvfuser/python_tests/test_torchscript.py:894:20
[DUMP graph_fuser.cpp:2509]   %7 : Tensor = prim::profile[profiled_type=Float(4, 8, 32, 32, strides=[8192, 1024, 32, 1], requires_grad=0, device=cuda:0), seen_none=0](%o.5)
[DUMP graph_fuser.cpp:2509]   return (%7)
```

forcing a fp32 instead of fp64 would just hide this problem for us. But frankly speaking, we don't need to cover it up. If TorchScript is broken, we can simply turn off this test or just not check the dtype and put a comment saying why.

**Comment by jjsjann123** [comment]
looks like my bias decomposition stopped working. I'm suspecting there's some issue with upstream's TorchScript profiling, since the decomposition relies on that.

This also feels consistent with the dtype issue on `test_category_rule`. :cry: I guess TorchScript is really being deprecated now.

**Comment by jjsjann123** [comment]
So for `test_conv2d_bias` let's just disable it. TorchScript is not supported by us neither. As long as we clear that those tests are not codegen issue, we can feel free to cross them out..
