### ISSUE TITLE
Build out `Expr::evaluate` for operators, and clean up unit tests

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#670]
During the nvFuser development process, one of our routine tasks is to create a fusion and then compare the output of our codegen with the ATen version of the fusion. Manually writing an ATen implementation can be both challenging and time-consuming. As an example, the test provided below requires 23 lines of carefully constructed ATen code:

```C++
// extracted from NVFuserTest.FusionLayerNormFusedOpsRedundantCast_CUDA
TEST_F(NVFuserTest, ExampleTest) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  auto fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  const float kEps = 1e-5;
  const int batch_size = 2048 * 8;
  const int hidden_size = 20480;
  {
    DataType dtype = DataType::Half;
    auto tv0 = makeContigTensor(1, dtype);
    auto tv1 = makeContigTensor(2, dtype);
    auto tv2 = makeContigTensor(1, dtype);
    auto tv3 = makeContigTensor(1, dtype);
    auto tv4 = makeContigTensor(1, dtype);

    fusion->addInput(tv0);
    fusion->addInput(tv1);
    fusion->addInput(tv2);
    fusion->addInput(tv3);
    fusion->addInput(tv4);
    auto tv5 = broadcast(tv0, {true, false});
    auto tv6 = castOp(DataType::Float, tv1);
    auto tv7 = castOp(DataType::Float, tv5);
    auto tv8 = add(tv6, tv7);
    auto tv9 = castOp(DataType::Half, tv8);
    auto tv10 = broadcast(tv2, {true, false});
    auto tv11 = castOp(DataType::Float, tv9);
    auto tv12 = castOp(DataType::Float, tv10);
    auto tv13 = add(tv11, tv12);
    auto tv14 = castOp(DataType::Half, tv13);
    auto tv15 = castOp(DataType::Float, tv14);
    auto tv16 = variance(tv15, {1}, false, false);
    auto tv17 = broadcast(tv16, {false, true});
    auto tv18 = sum(tv15, {1}, false);
    auto tv19 = broadcast(tv18, {false, true});

    nvfuser::Val* num_features = IrBuilder::create<Val>(1.0);
    num_features = mul(num_features, tv0->getLeafDomain()[0]->extent());
    auto s20 = num_features;

    auto s21 = reciprocal(s20);
    auto tv22 = mul(tv19, s21);
    auto s23 = IrBuilder::create<Val>(kEps);
    auto tv24 = add(tv17, s23);
    auto tv25 = rsqrt(tv24);
    auto tv26 = broadcast(tv22, {false, false});
    auto tv27 = castOp(DataType::Float, tv14);
    auto tv28 = sub(tv27, tv26);
    auto tv29 = broadcast(tv25, {false, false});
    auto tv30 = mul(tv28, tv29);
    auto tv31 = broadcast(tv4, {true, false});
    auto tv32 = castOp(DataType::Float, tv31);
    auto tv33 = mul(tv30, tv32);
    auto tv34 = broadcast(tv3, {true, false});
    auto tv35 = castOp(DataType::Float, tv34);
    auto tv36 = add(tv33, tv35);
    auto tv37 = castOp(DataType::Half, tv36);
    fusion->addOutput(tv37);
  }

  auto options = at::TensorOptions().dtype(at::kHalf).device(at::kCUDA, 0);
  std::vector<c10::IValue> inputs;
  std::vector<at::Tensor> outputs;

  {
    auto t0 = at::randn({hidden_size}, options);
    auto t1 = at::randn({batch_size, hidden_size}, options);
    auto t2 = at::randn({hidden_size}, options);
    auto t3 = at::randn({hidden_size}, options);
    auto t4 = at::randn({hidden_size}, options);
    inputs.emplace_back(t0);
    inputs.emplace_back(t1);
    inputs.emplace_back(t2);
    inputs.emplace_back(t3);
    inputs.emplace_back(t4);
    auto t5 = t0.unsqueeze(0).expand({batch_size, hidden_size});
    auto t6 = t1.to(at::kFloat);
    auto t7 = t5.to(at::kFloat);
    auto t8 = at::add(t6, t7);
    auto t9 = t8.to(at::kHalf);
    auto t10 = t2.unsqueeze(0).expand({batch_size, hidden_size});
    auto t11 = t9.to(at::kFloat);
    auto t12 = t10.to(at::kFloat);
    auto t13 = at::add(t11, t12);
    auto t14 = t13.to(at::kHalf);
    auto aten_outputs = at::native_layer_norm(t14, {hidden_size}, t4, t3, kEps);
    auto t33 = std::get<0>(aten_outputs);
    outputs.emplace_back(t33);
  }

  FusionExecutorCache fec(std::move(fusion_ptr));
  auto cg_outputs = fec.runFusionWithInputs(inputs);
  testValidate(fusion, cg_outputs, inputs, outputs, __LINE__, __FILE__);
}
```

Errors can easily occur when creating these implementations by hand, which can cause confusion during the debugging stage. For instance, if an incorrect ATen reference is used, causing a mismatch in your `testValidate`, you may mistakenly assume this is due to a bug in the codegen. This could lead to unnecessary time spent debugging the codegen.

We have developed a tool that automates the process of building ATen implementations. It can be found at https://github.com/NVIDIA/Fuser/blob/main/tools/cpp-repro-gen.py. However, this tool's output often requires manual adjustments to be functional. For example, it might create `at::gather` as the ATen reference code for `nvfuser::gather`, even though these two are completely separate things. They just happen to share the same name. To make the ATen code generated by `cpp-repro-gen.py` more usable, we would need to create a detailed pattern matching system for our fusion definitions and develop rules for converting them into ATen.

The main issue with `cpp-repro-gen.py` is that it acts like a mini-compiler. It takes the python fusion definition as a string, then translates this string into a C++ fusion definition and an ATen implementation as output. Since we don't currently have a stable API and IR definition, `cpp-repro-gen.py` may require updates whenever we modify our IR node definition. In general, we don't see `cpp-repro-gen.py` as a long-term solution for improving debuggability, and it isn't a good use of our time to keep refining `cpp-repro-gen.py`.

Recently, we incorporated a new class, `PolymorphicValue`, capable of storing data of various types such as `int64_t`, `double`, `at::Tensor`, etc. We also expanded our `ExpressionEvaluator` to handle all these data types. This enhancement allows us to contemplate the creation of an ATen backend for nvFuser IR, which can be evaluated by `ExpressionEvaluator`. To achieve this, we need to override the `Expr::evaluate` method for subclasses of `Expr`. If the evaluate method is overridden for all expressions in the fusion definition, then we can omit the ATen reference in `testValidate`. Consequently, `testValidate` will automatically utilize the `ExpressionEvaluator` to compute the ATen reference. An excellent example of how to override `Expr::evaluate` and clean up tests is provided in https://github.com/NVIDIA/Fuser/pull/575. For the `NVFuserTest.ExampleTest` example above, after the cleanup, the code should resemble:

```C++
// extracted from NVFuserTest.FusionLayerNormFusedOpsRedundantCast_CUDA
TEST_F(NVFuserTest, ExampleTest) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  auto fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  const float kEps = 1e-5;
  const int batch_size = 2048 * 8;
  const int hidden_size = 20480;
  {
    DataType dtype = DataType::Half;
    auto tv0 = makeContigTensor(1, dtype);
    auto tv1 = makeContigTensor(2, dtype);
    auto tv2 = makeContigTensor(1, dtype);
    auto tv3 = makeContigTensor(1, dtype);
    auto tv4 = makeContigTensor(1, dtype);

    fusion->addInput(tv0);
    fusion->addInput(tv1);
    fusion->addInput(tv2);
    fusion->addInput(tv3);
    fusion->addInput(tv4);
    auto tv5 = broadcast(tv0, {true, false});
    auto tv6 = castOp(DataType::Float, tv1);
    auto tv7 = castOp(DataType::Float, tv5);
    auto tv8 = add(tv6, tv7);
    auto tv9 = castOp(DataType::Half, tv8);
    auto tv10 = broadcast(tv2, {true, false});
    auto tv11 = castOp(DataType::Float, tv9);
    auto tv12 = castOp(DataType::Float, tv10);
    auto tv13 = add(tv11, tv12);
    auto tv14 = castOp(DataType::Half, tv13);
    auto tv15 = castOp(DataType::Float, tv14);
    auto tv16 = variance(tv15, {1}, false, false);
    auto tv17 = broadcast(tv16, {false, true});
    auto tv18 = sum(tv15, {1}, false);
    auto tv19 = broadcast(tv18, {false, true});

    nvfuser::Val* num_features = IrBuilder::create<Val>(1.0);
    num_features = mul(num_features, tv0->getLeafDomain()[0]->extent());
    auto s20 = num_features;

    auto s21 = reciprocal(s20);
    auto tv22 = mul(tv19, s21);
    auto s23 = IrBuilder::create<Val>(kEps);
    auto tv24 = add(tv17, s23);
    auto tv25 = rsqrt(tv24);
    auto tv26 = broadcast(tv22, {false, false});
    auto tv27 = castOp(DataType::Float, tv14);
    auto tv28 = sub(tv27, tv26);
    auto tv29 = broadcast(tv25, {false, false});
    auto tv30 = mul(tv28, tv29);
    auto tv31 = broadcast(tv4, {true, false});
    auto tv32 = castOp(DataType::Float, tv31);
    auto tv33 = mul(tv30, tv32);
    auto tv34 = broadcast(tv3, {true, false});
    auto tv35 = castOp(DataType::Float, tv34);
    auto tv36 = add(tv33, tv35);
    auto tv37 = castOp(DataType::Half, tv36);
    fusion->addOutput(tv37);
  }

  auto options = at::TensorOptions().dtype(at::kHalf).device(at::kCUDA, 0);
  auto t0 = at::randn({hidden_size}, options);
  auto t1 = at::randn({batch_size, hidden_size}, options);
  auto t2 = at::randn({hidden_size}, options);
  auto t3 = at::randn({hidden_size}, options);
  auto t4 = at::randn({hidden_size}, options);

  FusionExecutorCache fec(std::move(fusion_ptr));
  auto cg_outputs = fec.runFusionWithInputs({t0, t1, t2, t3, t4});
  testValidate(fusion, cg_outputs, {t0, t1, t2, t3, t4}, __LINE__, __FILE__);
}
```

Once we've fully developed `Expr::evaluate` for the majority of operators, we can start contemplating the retirement of `cpp-repro-gen.py`. In lieu of `cpp-repro-gen.py`, we should incorporate a method, `Fusion::printCpp()`, which will generate the necessary C++ code to recreate the fusion.

The potential benefits of expanding `Expr::evaluate` are not confined to simplifying unit tests. It could also potentially improve how we schedule fusions. For instance, if we encounter a `view` or `transpose` on fusion inputs or outputs, we may choose not to include these operations in the kernel, but rather hoist them to `ExpressionEvaluator`.

There's a specific aspect that warrants careful attention when developing `Expr::evaluate`: the ATen dependency. In the future, we may need to be able to build nvFuser without dependency on ATen. Therefore, it's preferable that we centralize any new code that depends on ATen. This way, we can easily guard these sections of code with macros in the future.

# Things to do

Search for `testValidate` in our unit tests to identify which tests use `testValidate`. For each test, remove the ATen reference. Most likely, we'll encounter error messages about missing `evaluate` implementations. We should then provide the correct implementations for these missing `evaluate` methods. Preferably, we should keep PRs small, tackling only a few tests/operations in each PR. Once all the tests have been rectified, let's reassess the situation and determine whether it would be worth our time to remove `cpp-repro-gen.py` and implement `Fusion::printCpp()`.

**Comment by Priya2698** [comment]
Closing this issue. `expr::evaluate` is implemented for most operators now and all the test files have been addressed.
