### ISSUE TITLE
indexing violates vectorization requirement

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#675]
Marking this as WIP, as I do not yet have a standalone cpp repro. The issue shows up when I try to enable vectorization across merged dimensions for transpose scheduler.

This is running a simple transpose `t0.transpose(1, 4).transpose(0, 3)`, where t0 is a contiguous tensor with size `(2, 2, 65536, 2, 2)`
launched with 1024 blocks with 128 threads.

Fusion IR prior to transformation.
```
groups:
g{0, 1}

edges:

group details:
g{(transpose)
inputs:
T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ] float
outputs:
T2_g[ iS13{i4}, iS11{i5}, iS12{i3}, iS10{i0}, iS14{i2} ] float


T1_l[ iS5{i0}, iS9{i5}, iS7{i3}, iS8{i4}, iS6{i2} ]
   = Set.Permute( T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ] )
(0)
T2_g[ iS13{i4}, iS11{i5}, iS12{i3}, iS10{i0}, iS14{i2} ]
   = Set.Permute( T1_l[ iS5{i0}, iS9{i5}, iS7{i3}, iS8{i4}, iS6{i2} ] )
(1)
}
```

Here's the transpose scheduler params:
```
===== Transpose Stats ========
inputs: T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ]
outputs: T2_g[ iS13{i4}, iS11{i5}, iS12{i3}, iS10{i0}, iS14{i2} ]
shape: 2 2 65536 2 2
num_elems: 1048576
n_input_tensors: 1
max_input_dtype_size: 4
group 1: T2_g[ iS13{i4}, iS11{i5}, iS12{i3}, iS10{i0}, iS14{i2} ]
reference1: T2_g[ iS13{i4}, iS11{i5}, iS12{i3}, iS10{i0}, iS14{i2} ]
inner_most_id1 position: 4 (in reference 1)
group 2: T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ]
reference2: T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ]
inner_most_id2 position: 1 (in reference 1)
small transposed dim, needs virtual inner-most dim


===== Transpose Parameters ========
Tag: Transpose heuristics Transpose Characteristics:
 BlckX: 128
 input tile size: 32
 output tile size: 32
 elements per tile: 1024
 elements per thread: 8
Unroll group 1, Factor: 8
Vectorize group 2, Factor: 4
Unroll group 2, Factor: 2
Virtual inner-most dim:
  split(2, 8)
  merge 4, 3 with innermost1
  merge 0, 2 with innermost2
====================================


TransformPrinter :

T0_g[ iS97{( ceilDiv(( ( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) ) * ( ceilDiv(( ( 8 * i0 ) * i2 ), 32) ) ), 1) )}, iS98{1}, iS102{( ceilDiv(( ceilDiv(( 32 * 32 ), 4) ), 128) )}, iS103{128}, iS101{4} ]
 root domain : (iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5})
 contiguity: t t t t t
  Split: iS2{i3} by factor 8 -> iS86{( ceilDiv(i3, 8) )}, iS87{8}, start offset: 0, stop offset: 0
  Merge: iS3{i4} and iS86{( ceilDiv(i3, 8) )} -> iS88{( i4 * ( ceilDiv(i3, 8) ) )}
  Merge: iS88{( i4 * ( ceilDiv(i3, 8) ) )} and iS4{i5} -> iS89{( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 )}
  Split: iS89{( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 )} by factor 32 -> iS90{( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) )}, iS91{32}, start offset: 0, stop offset: 0
  Merge: iS87{8} and iS0{i0} -> iS92{( 8 * i0 )}
  Merge: iS92{( 8 * i0 )} and iS1{i2} -> iS93{( ( 8 * i0 ) * i2 )}
  Split: iS93{( ( 8 * i0 ) * i2 )} by factor 32 -> iS94{( ceilDiv(( ( 8 * i0 ) * i2 ), 32) )}, iS95{32}, start offset: 0, stop offset: 0
  Merge: iS90{( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) )} and iS94{( ceilDiv(( ( 8 * i0 ) * i2 ), 32) )} -> iS96{( ( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) ) * ( ceilDiv(( ( 8 * i0 ) * i2 ), 32) ) )}
  Split: iS96{( ( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) ) * ( ceilDiv(( ( 8 * i0 ) * i2 ), 32) ) )} by factor 1 -> iS97{( ceilDiv(( ( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) ) * ( ceilDiv(( ( 8 * i0 ) * i2 ), 32) ) ), 1) )}, iS98{1}, start offset: 0, stop offset: 0
  Merge: iS95{32} and iS91{32} -> iS99{( 32 * 32 )}
  Split: iS99{( 32 * 32 )} by factor 4 -> iS100{( ceilDiv(( 32 * 32 ), 4) )}, iS101{4}, start offset: 0, stop offset: 0
  Split: iS100{( ceilDiv(( 32 * 32 ), 4) )} by factor 128 -> iS102{( ceilDiv(( ceilDiv(( 32 * 32 ), 4) ), 128) )}, iS103{128}, start offset: 0, stop offset: 0
 leaf domain : (iS97{( ceilDiv(( ( ceilDiv(( ( i4 * ( ceilDiv(i3, 8) ) ) * i5 ), 32) ) * ( ceilDiv(( ( 8 * i0 ) * i2 ), 32) ) ), 1) )}, iS98{1}, iS102{( ceilDiv(( ceilDiv(( 32 * 32 ), 4) ), 128) )}, iS103{128}, iS101{4})

```

Here's part of the generated code.
```
  int i2;
  i2 = 32 * (((nvfuser_index_t)blockIdx.x) / i1);
  int i3;
  i3 = ((nvfuser_index_t)threadIdx.x) % 8;
  int i4;
  i4 = 4 * i3;
  int i5;
  i5 = i4 + i2;
  int i6;
  i6 = i5 / T0.logical_size[4];
  int i7;
  i7 = ceilDiv(T0.logical_size[2], 8);
  int i8;
  i8 = T0.logical_size[4] * T0.logical_size[3];
  int i9;
  i9 = (((i8 * 8) * (i6 % i7)) + (T0.logical_size[4] * (i6 / i7))) + (i5 % T0.logical_size[4]);


    // ...
    #pragma unroll
    for(nvfuser_index_t i36 = 0; i36 < 2; ++i36) {
      int i37;
      i37 = i14 + (16 * (i36 + nvfuser_zero));
      int i38;
      i38 = i37 / T0.logical_size[1];
      loadGeneric<float, 4>( &T3[(i15 + (512 * i36))],  &T0[(((i9 + (i11 * (i38 % T0.logical_size[0]))) + (i10 * (i37 % T0.logical_size[1]))) + (i8 * (i38 / T0.logical_size[0])))]);
    }
```

So if we look at variable `i9` here, the second term looks suspicious. `(T0.logical_size[4] * (i6 / i7))`.
if we look at thread 99, block 652, printing out the index here we have `i9 == 71874` which doesn't align with 4.
```
 i0 32
 i1 1
 i2 3
 i3 12
 i4 20864
 i5 20876
 i6 10438
 i7 8192
 i8 4
 i9 71874
```

**Comment by jjsjann123** [comment]
cpp repro added:
https://github.com/NVIDIA/Fuser/blob/91b02001f73e6c033164119924d8a627d79a0346/test/test_gpu_view.cpp#L2450-L2569

**Comment by jjsjann123** [comment]
> Since i4 * ( ceilDiv(i3, 8) ) is not a contiguously merged domain, only i5 should have been used for the vectorization, but in this case the extent of i5 is just 2, so the maximum vectorization factor should be 2.

But wasn't (i4, i5) contiguous?!
If we look at `i4 * (ceilDiv(i3, 8)) * i5`, I guess it should have been `ceilDiv(i3, 8) * i4 * i5` instead, which would show how i4, i5 can be both used as vectorization, which would give us 4 instead of 2.
But wasn't the two expression equivalent? does the order of merge/split matter?

**Comment by naoyam** [comment]
> But wasn't (i4, i5) contiguous?!

They are contiguous, so if they are merged in that order, yes, that's a contiguous merge.

> If we look at i4 * (ceilDiv(i3, 8)) * i5, I guess it should have been ceilDiv(i3, 8) * i4 * i5 instead, which would show how i4, i5 can be both used as vectorization, which would give us 4 instead of 2.

Yes, if they were merged in that order, 4 would have been a valid factor.

> But wasn't the two expression equivalent? does the order of merge/split matter?

The order does matter. The index expression for a split is built as: `outer_loop_index * inner_extent + inner_loop_index`. You can vectorize split inner outputs but not outer outputs.

So, there seem two issues: 

- We should change the merge order
- Even for the current merge order, the vectorization analysis should correctly report the maximum factor of 2 instead of 4

**Comment by naoyam** [comment]
> > But wasn't (i4, i5) contiguous?!
> 
> They are contiguous, so if they are merged in that order, yes, that's a contiguous merge.
> 
> > If we look at i4 * (ceilDiv(i3, 8)) * i5, I guess it should have been ceilDiv(i3, 8) * i4 * i5 instead, which would show how i4, i5 can be both used as vectorization, which would give us 4 instead of 2.
> 
> Yes, if they were merged in that order, 4 would have been a valid factor.
> 
> > But wasn't the two expression equivalent? does the order of merge/split matter?
> 
> The order does matter. The index expression for a split is built as: `outer_loop_index * inner_extent + inner_loop_index`. You can vectorize split inner outputs but not outer outputs.
> 
> So, there seem two issues:
> 
> * We should change the merge order
> * Even for the current merge order, the vectorization analysis should correctly report the maximum factor of 2 instead of 4

Actually, I just realized the repro is manually scheduled, so I'm not sure if the transpose scheduler has the same issue.
