### ISSUE TITLE
Setting `fusion_id_` with parallel threads may cause non-deterministic kernel names

### ISSUE THREAD

**Issue by naoyam** [NVIDIA/Fuser#762]
`FusionExecutor::compileFusion` may be executed in parallel by multiple threads, so incrementing `fusion_id_` may result in data race. This can also lead to non-deterministic kernel numbers, which is inconvenient.

Per @rdspring1, this could be avoided by passing fusion IDs to `compileFusion`.

**Comment by rdspring1** [comment]
One solution is to replace the static `fusion_id_` variable in `FusionExecutor` with the current number of fusions in the python frontend `FusionCache`.

**Comment by rdspring1** [comment]
Fixed by https://github.com/NVIDIA/Fuser/pull/1125
