### ISSUE TITLE
Python interface feature request: pad

### ISSUE THREAD

**Issue by mruberry** [NVIDIA/Fuser#8]
Analogous to XLA's pad operation:

https://www.tensorflow.org/xla/operation_semantics#pad

**Comment by naoyam** [comment]
The edge padding should be straightforward to support by extending a prototype, but the interior padding needs some more work. Is it equally important?

**Comment by mruberry** [comment]
> The edge padding should be straightforward to support by extending a prototype, but the interior padding needs some more work. Is it equally important?

I think the edge padding is more important
