### ISSUE TITLE
Update manylinux container to use gcc 12

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#830]
```
manylinux_2_28 (AlmaLinux 8 based)
Toolchain: GCC 12
```

**Comment by xwang233** [comment]
this was just updated in our nightly build and github CI test

**Comment by zasdfgbnm** [comment]
Is our pipeline for pushing wheels to PyPI working? If so, then I think we can close this issue.

**Comment by xwang233** [comment]
Pipeline build & test are working now. Pushing was not tested but wasn't changed either.

We can wait until tomorrow morning to close this issue when the nightly wheels are pushed to pypi then.

**Comment by zasdfgbnm** [comment]
Looks like we are updating pypi packages normally: https://pypi.org/project/nvfuser-cu121/#history
