### ISSUE TITLE
Unexpected behavior in `OptOutMutator`

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#852]
Simple usage patterns of `OptOutMutator` give confusing behavior; I have run into these while exploring concretization of symbolic fusions. We should more clearly express any limitations on the expected usage of the class.

# Scope

`OptOutMutator` is the only friend class of `IrContainer` and it is a `friend` to `TensorView` and so it's one of a handful of classes that can modify the `TensorDomain` of a tensor.  `OptOutMutator` is currently used as a parent class for
- `ValReplacementMutator` : used by `replaceValue`
- `ValReplacement::SubstituteInExpr` : used by `ir_utils::replaceValInExpr(Expr* expr, Val* reference, Val* substitute)` which substitutes replaces the given expression if any of its inputs, outputs, or attributes is `reference`, replacing it with `substitute`.
- `DynamicTransformConcretizer` : used to concretize symbolic fusions by traversing and mutating `TensorView`s and their associated `IterDomain`s.

# Example of confusing behavior

Here is the current docstring for `OptOutMutator`:
```c++
// Class to perform mutations on Fusion IR. Exprs can simply be redefined, but
// when mutating values they have to be registered through registerMutation so
// that exprs can detect there's been a muatation and know to modify all
// instances of that Val. This means each Val should be mutated "consistently".
// Otherwise behavior may be difficult to understand as it depends on which
// order mutate is called in. This class expects user to topologically call the
// statments of interest so inputs are called and mutated before exprs depending
// on them.
//
// Warning: TensorViews need to be treated carefully. As we don't generally
// register their mutation when their tensor domains only change. If a TV needs
// to be swapped out, it needs to be registered as a "proper" mutation like
// other vals, on top of TensorDomain being updated in the mutated TensorView.
```
Here is one use case from `TensorView::cacheBefore` where an output (`this`) of an expression is mutated using `ir_utils::replaceValInExpr`:
```c++
  // Insert producer - Cache_Before (CB) - before this TV.
  // Before: Prev TV -> [Definition Op] -> This TV
  // After:  Prev TV -> [Definition Op] -> New CB TV -> [Set Op] -> This TV

  // Get inputs for origin expression
  auto expr_inputs = definition()->inputs();
  // Expr* producer_definition =
  ir_utils::replaceValInExpr(definition(), this, producer);
```
This seems to work, since we use `cacheBefore` heavily and we do not see any errors. However, consider the following simple example:
```c++
// Test that OptOutMutator mutates expressions in a predictable way
TEST_F(NVFuserTest, OptOutMutatorMutatedOutput) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion* fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  TensorView* tv0 = makeSymbolicTensor(1);
  fusion->addInput(tv0);

  auto tv1 = neg(tv0);

  auto tv2 = set(tv1);
  fusion->addOutput(tv2);

  auto tv3 = set(tv0);

  fusion->printMath(/*from_outputs_only*/ false);
/*
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T2_g[ iS2{i0} ], float

%kernel_math {
T1_l[ iS1{i0} ]
   = -T0_g[ iS0{i0} ];
T2_g[ iS2{i0} ]
   = Set( T1_l[ iS1{i0} ] )
T3_l[ iS3{i0} ]
   = Set( T0_g[ iS0{i0} ] )
}
*/

  OptOutMutator mut;
  mut.registerMutation(tv1, tv3);
  mut.mutate(tv1->definition());

  fusion->printMath(/*from_outputs_only*/ false);
/*
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T2_g[ iS2{i0} ], float

%kernel_math {
T2_g[ iS2{i0} ]
   = Set( T1_l[ iS1{i0} ] )
T3_l[ iS3{i0} ]
   = -T0_g[ iS0{i0} ];
}
*/

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({3}, options);

  FusionExecutor fe;
  fe.compileFusion(fusion);
/*
unknown file: Failure
C++ exception with description "thread_predicates_.find(tv_inp) != thread_predicates_.end() INTERNAL ASSERT FAILED at "/opt/pytor
ch/nvfuser/csrc/device_lower/analysis/thread_predicate.cpp":255, please report a bug with repro script to NVFuser at https://gith
ub.com/NVIDIA/Fuser/issues. Thread predicate map was not initialized, couldn't find T1_l[ iS5{( (( (( getMetaData(T0) )).logical_
size ))[0] )} ]
Exception raised from updateBitSet at /opt/pytorch/nvfuser/csrc/device_lower/analysis/thread_predicate.cpp:255 (most recent call
first):
*/

  auto outputs = fe.runFusion({t0});

  testValidate(fusion, outputs, {t0}, {t0}, __LINE__, __FILE__);
}
```
The `neg` op node was mutated, and its output `tv1` had been registered for mutation to `tv3`. When that happened, the definition was _transferred_ to `tv3`, which has the effect of redefining `tv3` to the original definition of `tv1`!

Compilation fails here; it seems that `T1` is removed from the fusion, and we were perhaps just lucky to avoid a segfault when printing the second time. In any event I would have expected to see the following mutated fusion:
```
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T2_g[ iS2{i0} ], float

%kernel_math {
T2_g[ iS2{i0} ]
   = Set( T3_l[ iS3{i0} ] )
T3_l[ iS3{i0} ]
   = Set( T0_g[ iS0{i0} ] )
}
```

# Suggested approach

I originally thought that we should just avoid mutating `Expr`s if only their outputs are registered for mutation, since this can have the effect of redefining the very `Val`s we had previously registered. However, the `cacheBefore` use case breaks in that case. We could salvage that by modifying `cacheBefore` to call `replaceValInExpr` on all uses of `this` instead. That is a typical pattern I use: replacing input and attribute vals in exprs, but not outputs. There may be other issues with this approach. I'm starting this issue to track this until we have a well-understood set of "guard rails" for mutating fusions.

**Comment by jacobhinkle** [comment]
Another trippy example:
```c++
TEST_F(NVFuserTest, OptOutMutatorRedefinedConstant) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion* fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  auto s0 = IrBuilder::create<Val>(DataType::Int);
  fusion->addInput(s0);
  auto s1 = neg(s0);
 
  auto tv0 = full({IrBuilder::create<Val>(2L)}, s1, DataType::Int);
  fusion->addOutput(tv0);
 
  fusion->printMath(/*from_outputs_only*/ false);
  /*
Inputs:
  i0, int64_t
Outputs:
  T0_g[ iS0{2} ], int64_t
 
%kernel_math {
i1 = -i0;
T0_g[ iS0{2} ]
   = full({2}, ( -i0 ));
}
  */
 
  // After the following mutation, it's reasonable to expect the input scalar s0
  // to be ignored, and the output to just be ones.
  OptOutMutator mut;
  mut.registerMutation(s1, fusion->oneVal(DataType::Int));
  mut.mutate(s1->definition());
 
  fusion->printMath(/*from_outputs_only*/ false);
  /*
Inputs:
  i0, int64_t
Outputs:
  T0_g[ iS0{2} ], int64_t
 
%kernel_math {
T0_g[ iS0{2} ]
   = full({2}, i1);
1 = -i0;
}
  */
  // ...
}
```
Notice the odd expression `1 = -i0` where `i0` is an input scalar. This does not compile: `i1` was removed from the `Fusion` but is still referenced in the definition of `T0_g`.

You might think these happen just because we only mutated a single statement, this particular definition. Instead, we could mutate all statements and see what happens. So we'd replace the `mut.mutate(s1->definition())` line with
```c++
  for (auto stmt : StmtSort::getStmts(fusion)) {        
    mut.dispatchMutate(stmt);
  }
```
This results in
```
Inputs:                                                                                                                    
  i0, int64_t                                                                                                              
Outputs:                                                                                                                   
  T0_g[ iS0{2} ], int64_t                                                                                                  
                                                                                                                           
%kernel_math {                                                                                                             
1 = -i0;                                                                                                                   
T0_g[ iS0{2} ]                                                                                                             
   = full({2}, ( -i0 ));                                                                                                   
}
```
Now, `fusion->oneVal()` is redefined as we saw above. Also, the fusion definition is intact: apparently we did not wind up replacing the argument to `full`. So what actually happened? When we mutated `tv1->definition()`, we redefined `oneVal()` to `-i0` and removed `i1` which was originally defined as `-i0`. Then, when we mutated the `fullOp`, aka `tv0->definition()`, we replaced `i1` with `oneVal()` which was redefined to have a definition of `-i0`. *The printout above is printing* `full({2}, fusion->oneVal());`.

**Comment by naoyam** [comment]
> I originally thought that we should just avoid mutating Exprs if only their outputs are registered for mutation, since this can have the effect of redefining the very Vals we had previously registered. However, the cacheBefore use case breaks in that case. 

For `cacheBefore`, instead of replacing the output of the definition, we could use `RecomputeTv` to replicate `this`, which gives a new tensor, and replace all use exprs of the original TV with the new replicated TV.

Is `cacheBefore` the only instance where this happens? If so, we may want to avoid replacing outputs.

**Comment by jacobhinkle** [comment]
> Is cacheBefore the only instance where this happens?

It's the only one I've come across but I will do more experimenting to find out. I agree having `mutate(Expr*)` not modify the outputs of expressions seems desirable.

**Comment by jacobhinkle** [comment]
> For `cacheBefore`, instead of replacing the output of the definition, we could use `RecomputeTv` to replicate `this`, which gives a new tensor, and replace all use exprs of the original TV with the new replicated TV.

This seems to work pretty well in most cases, though there are some failures in concretization and Welford tests. I will push the code and start a PR soon.

We may need an alternative interface for ops with multiple outputs. In the case of `WelfordOp`, calling `avg->cacheBefore()` will recompute the op and redefine the outputs, so if we follow that with `varsum->cacheBefore()` then `varsum` now has either a duplicate definition or a null definition (if we remove the original op). We could provide an escape hatch for those cases by making a new method `avg->cacheSiblingsBefore()` which would recompute the op once then return a vector of cached TVs representing all the siblings including `avg`. `cacheBefore` is only used in the schedulers,

**Comment by naoyam** [comment]
Maybe we could change `cacheBefore` to insert caches for all outputs instead of just the `this` tensor. I don't think this would make anything worse.

**Comment by jacobhinkle** [comment]
> Maybe we could change `cacheBefore` to insert caches for all outputs instead of just the `this` tensor. I don't think this would make anything worse.

Exactly. I am trying that now. I think it's the right way. We just need to be careful to find the cached siblings properly in the schedulers after that.
