### ISSUE TITLE
benchmark case failed

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#96]
(1) easy fix for `setupDivMaxSoftmaxDropoutForward`, just change `contiguity({true, false, false, true}` to `contiguity({true, c10::nullopt, c10::nullopt, true}`
(2) failed in `BiasDropoutAddLayernormBwd1_fp32` in assert:
```
      TORCH_INTERNAL_ASSERT(
          val.has_value(),
          "Tried to evaluate the extent, ",
          extent->toInlineString(),
          " for the ptype: ",
          p_type,
          " to set launch bounds but could not.");
```
works fine if skip this assert by:
```
      if(!val.has_value()) {
        continue;
      }
```

**Comment by zasdfgbnm** [comment]
For (2), might be related to my recent PR https://github.com/NVIDIA/Fuser/pull/86, and I am working on rewriting this part, so hopefully it will be fixed after I rewrite.

**Comment by zasdfgbnm** [comment]
I will self assign this issue, but since you already have the fix for `setupDivMaxSoftmaxDropoutForward`, could you post it as PR?

**Comment by liqiangxl** [comment]
sure

**Comment by zasdfgbnm** [comment]
Update:
1. This is not related to https://github.com/NVIDIA/Fuser/pull/86
2. Adding `, norm_params->lparams` to `compileFusion` also fix the issue.
