### ISSUE TITLE
Compilation issues with PolymorphicValue

### ISSUE THREAD

**Issue by nWEIdia** [NVIDIA/Fuser#971]
In building apex with this repo, I encountered the following compilation errors. 

/opt/pytorch/pytorch/../fuser/csrc/type.h(985): **error: no suitable user-defined conversion from "nvfuser::PolymorphicValue" to "T" exists
            value = PolymorphicValue(static_cast< T >  (value));**
                                                    ^
          detected during:
            instantiation of function "lambda [](auto)->auto [with <auto-1>=std::type_identity<std::complex<double>>]" at line 382 of /opt/pytorch/pytorch/../fuser/lib/dynamic_type/src/dynamic_type/type_traits.h
            instantiation of "auto dynamic_type::ForAllTypes<T, Ts...>::operator()(Fun) const [with T=std::complex<double>, Ts=<double, int64_t, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>>>>, Fun=lambda [](auto)->auto]" at line 385 of /opt/pytorch/pytorch/../fuser/lib/dynamic_type/src/dynamic_type/type_traits.h
            instantiation of "auto dynamic_type::ForAllTypes<T, Ts...>::operator()(Fun) const [with T=at::Tensor, Ts=<std::complex<double>, double, int64_t, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>>>>, Fun=lambda [](auto)->auto]" at line 385 of /opt/pytorch/pytorch/../fuser/lib/dynamic_type/src/dynamic_type/type_traits.h
            instantiation of "auto dynamic_type::ForAllTypes<T, Ts...>::operator()(Fun) const [with T=nvfuser::Opaque, Ts=<at::Tensor, std::complex<double>, double, int64_t, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>>>>, Fun=lambda [](auto)->auto]" at line 385 of /opt/pytorch/pytorch/../fuser/lib/dynamic_type/src/dynamic_type/type_traits.h
            instantiation of "auto dynamic_type::ForAllTypes<T, Ts...>::operator()(Fun) const [with T=nvfuser::Pointer, Ts=<nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>>>>, Fun=lambda [](auto)->auto]" at line 385 of /opt/pytorch/pytorch/../fuser/lib/dynamic_type/src/dynamic_type/type_traits.h
            instantiation of "auto dynamic_type::ForAllTypes<T, Ts...>::operator()(Fun) const [with T=nvfuser::StructHandle, Ts=<nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>>>>, Fun=lambda [](auto)->auto]" at line 385 of /opt/pytorch/pytorch/../fuser/lib/dynamic_type/src/dynamic_type/type_traits.h
            instantiation of "auto dynamic_type::ForAllTypes<T, Ts...>::operator()(Fun) const [with T=std::monostate, Ts=<nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool, std::vector<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>, std::allocator<dynamic_type::DynamicType<dynamic_type::Containers<std::vector>, nvfuser::StructHandle, nvfuser::Pointer, nvfuser::Opaque, at::Tensor, std::complex<double>, double, int64_t, bool>>>>, Fun=lambda [](auto)->auto]" at line 989
 
Is this a compiler issue?

**Comment by naoyam** [comment]
Which compiler did you use?

CC: @zasdfgbnm

**Comment by nWEIdia** [comment]
I am using  gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by naoyam** [comment]
Hmm, that should be fine. The dynamic value library tends to expose compiler issues especially with older versions of compilers, but 11.4 should work fine.

**Comment by nWEIdia** [comment]
Ok, good to know. 
I would provide more details tomorrow. Thanks!

**Comment by zasdfgbnm** [comment]
Per offline chat with @nWEIdia, the compiler is actually nvcc instead of gcc, which is known to have issue. We should avoid including nvfuser headers in `cu` files.

**Comment by nWEIdia** [comment]
cc @crcrpar on the need to change .cu to .cpp for instance_norm.
