### ISSUE TITLE
We shouldn't require allocation domain to be between root and leaf

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#986]
Our current implementation for swizzle is very hacky and broken: https://github.com/NVIDIA/Fuser/issues/554

Assume that we have a fusion
```
Tswizzled = T0
T1 = Tswizzled
```
the indexing we want for swizzle is like this
```
Tswizzled[swizzled_index] = T0[index]
T1[index] = Tswizzled[swizzled_index]
```
The most natural way to implement this behavior is by making allocation domain not required to be between root and leaf. Instead, for `Tswizzled`, we can have:
```
allocation domain: [I1, I2]
I3, I4 = swizzle2d(I1, I2)
root domain: [I3, I4]
... transformations ...
leaf domain: [..., BIDx, TIDx, Vec]
```
Then when indexing `Tswizzled` as consumer, we are already indexing into allocation domain, we will automatically get the swizzled index. When indexing `Tswizzled` as producer, we first replay `Tswizzled` as `T1`, which is trivial in this case. We do not need any hacks like "skipSwizzles" to support this.

**Comment by csarofeen** [comment]
I don't disagree that we might want to support allocation domains not between root and leaf, but I'm a bit confused on this example. I think swizzle is hacky, yes, but I don't know why it's hacky relative to allocation domain. I was mentioning swizzle with @naoyam recently in how we want to model it in IterDomain graph which demonstrates the very strange behavior of how swizzle is treated today.

**Comment by zasdfgbnm** [comment]
> hacky relative to allocation domain

What do you mean by this? I think what I am trying to say is, by using allocation domain, we can make it non-hacky.

**Comment by csarofeen** [comment]
Swizzle is hacky, but I'm not understanding how allocation domain could play a role in reducing the hackyness.

**Comment by zasdfgbnm** [comment]
> Swizzle is hacky, but I'm not understanding how allocation domain could play a role in reducing the hackyness.

If you have a fusion:
```
T1 = set(T0)
T2 = set(T1)
```
and you want to swizzle `T1`, with the current design, it will be scheduled like this:
<img width="610" alt="image" src="https://github.com/NVIDIA/Fuser/assets/1032377/d0552d79-3fcf-4905-b3a7-e3f7251f18b7">
When indexing T0, naturally, we should to replay T0 as T1, but because we do not want to swizzle T0, we need to skip swizzle in this replay. When indexing T1 as a producer, naturally, we would replay T1 as T2, which basically will remove swizzle from T1, but because we do want to swizzle T1, we should later "fix" this indexing by doing another round of indexing separately.

However, if instead we schedule the fusion like this:
<img width="634" alt="image" src="https://github.com/NVIDIA/Fuser/assets/1032377/5613e954-8228-4519-8aa9-b4d1770d681d">

Then when indexing T0, we just replay T0 as T1, which will just work because the swizzle op is in the producer side of root domain and will not be skipped. When indexing T1 as a producer, it will also just work, because we will replay T2's transformations on top of T1's root domain, and when we index from leaf to T1's allocation domain, swizzle will automatically be applied.

**Comment by wujingyue** [comment]
I'm onboard with @zasdfgbnm . Below is an illustration that helped me understand this case. I **think** it describes the same thing that @zasdfgbnm already. I attempted several other approaches to represent swizzling (e.g. as a transform from T1's root to T1's rfactor and as a transform from T2's rfactor to T1's root). None of them work as well. 

![Allocation Domain](https://github.com/NVIDIA/Fuser/assets/2772612/a710bffd-ffd9-4a23-8413-0ef220329661)

Question to @zasdfgbnm : I'm just not sure why `swizzle` in [your figure](https://user-images.githubusercontent.com/1032377/279535884-5613e954-8228-4519-8aa9-b4d1770d681d.png) is a function **from** allocation **to** rfactor. I think it should be in the other direction (and therefore `A1` in my illustration above).

**Comment by zasdfgbnm** [comment]
> Question to @zasdfgbnm : I'm just not sure why `swizzle` in [your figure](https://user-images.githubusercontent.com/1032377/279535884-5613e954-8228-4519-8aa9-b4d1770d681d.png) is a function **from** allocation **to** rfactor. I think it should be in the other direction (and therefore `A1` in my illustration above).

I actually think your figure makes more sense than mine. The reason I put my graph like that is because it seems to be more aligned with our current indexing, therefore less changes required. We definitely need to discuss this when we are about to work on this issue.

**Comment by csarofeen** [comment]
There's two types of swizzle, a swizzle that changes memory storage and one that changes the iteration space (z-curve). For the data layout swizzle this makes sense, for the iteration space swizzle it doesn't make sense. So as to being able to bury swizzles into allocation domains, yes that makes sense to me. It would be good for allocation domain improvements to follow @naoyam's refactoring IterDomains which make it much cleaner to arbitrarily set allocation domains, leaf domains, root domains, and rfactor domains so they don't all have to always be directly in line in the precise order they are today. This would also allow us to "undo" reshape/permute ops.

**Comment by zasdfgbnm** [comment]
> iteration space (z-curve)

This is no longer used in matmul scheduler. So I am not clear about the future of this. We may reconsider using it at some pointer, or we may completely abandon it.

**Comment by jjsjann123** [comment]
Do we still have a *need* to support complex allocation domain use case here?

I'm getting more concerned about the complexity of this request... If we don't have an urgent need to use it, does it make sense for us to keep the allocation domain simple as a permutation on rfactor/root.

**Comment by wujingyue** [comment]
Not from me at this moment. If we pursue #1502 option 2 (maybe 50% chance), step 2 will need to set a non-trivial allocation domain to concat's inputs. Anyhow, happy to brainstorm with you to find another way out.

**Comment by jjsjann123** [comment]
> Not from me at this moment. If we pursue #1502 option 2 (maybe 50% chance), step 2 will need to set a non-trivial allocation domain to concat's inputs. Anyhow, happy to brainstorm with you to find another way out.

IIUC, with option 2 from #1502, we just needed to have an allocation on a sliced buffer. I think it's still do-able with slice + permutation `rfactor domain -> (slice / permutation) -> leaf domain` and then we'll require alloc_domain to be a `permutation of maybe_leaf` I'll try to write up a separate issue to track the discussion of the new protocol.

I'm just trying to avoid supporting complex transformation applied on alloc_domain, it seems really hard at this point.

**Comment by wujingyue** [comment]
As discussed offline, @jjsjann123 and I found a way around so #1502 no longer needs "non-trivial" allocation domain.

**Comment by zasdfgbnm** [comment]
fixed
